### ISSUE TITLE
testing: Go Debug Adapter/substitute path with remote program test times out 

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#1043]
This happened only in the Release Nightly test.
Release Nightly test runs extra tests than other test workflows (Short/Long Tests).
So it is possible that they affect the load on the builder machine, but I am not sure if that's the only issue.

```
  1) Go Debug Adapter
       substitute path
         substitutePath with remote program
           stopped for a breakpoint set during initialization using remotePath (remote attach):
     Error: no event 'stopped' received after 20000 ms
  	at Timeout._onTimeout (node_modules/vscode-debugadapter-testsupport/lib/debugClient.js:233:28)
  	at listOnTimeout (internal/timers.js:531:17)
  	at processTimers (internal/timers.js:475:7)
```
https://github.com/golang/vscode-go/runs/1557899336?check_suite_focus=true
https://github.com/golang/vscode-go/runs/1570808090?check_suite_focus=true

Since the nightly release is blocked, I am temporarily going to skip this test for now.

**Comment by hyangah** [comment]
Today's nightly release passed, while I see the same failures in another internal CI that works like Short Test. So I guess the test is flaky.

**Comment by hyangah** [comment]
Still experiencing test failure
```

        1) stopped for a breakpoint set during initialization using substitutePath (remote attach)

Sending initializing request for remote attach setup.

Setting up attach request for {"name":"Attach","type":"go","request":"attach","mode":"remote","host":"127.0.0.1","port":34715,
"packagePathToGoModPathMap":{"/home/runner/go/src/test/testfixture":"",
"/home/runner/go/src/test/testfixture/baseTest":"",
"/home/runner/go/src/test/testfixture/gogetdocTestData":"",
"/home/runner/go/src/test/testfixture/completions":"",
"/home/runner/go/src/test/testfixture/testTags":""},
"apiVersion":2,"dlvLoadConfig":{"followPointers":true,"maxVariableRecurse":1,"maxStringLen":64,"maxArrayValues":64,"maxStructFields":-1},"showGlobalVariables":false,"cwd":"/home/runner/work/vscode-go/vscode-go/test/testdata/substitutePathTest492FkC/helloWorldServer",
"dlvToolPath":"/home/runner/go/bin/dlv",
"remotePath":"/home/runner/work/vscode-go/vscode-go/test/testdata/helloWorldServer",
"substitutePath":[{
  "from":"/home/runner/work/vscode-go/vscode-go/test/testdata/substitutePathTest492FkC/helloWorldServer",
  "to":"/home/runner/work/vscode-go/vscode-go/test/testdata/substitutePathTest492FkC/helloWorldServer"}]}.

Sending set breakpoints request for remote attach setup.

Sending configuration done request for remote attach setup.

        ✓ stopped for a breakpoint set during initialization using remotePath (remote attach) (13548ms)

```

not sure why the `packagePathToGoModPathMap` entry was populated. can be red herring.
