### ISSUE TITLE
exthost error golang.go provider FAILED

### ISSUE THREAD

**Issue by kelein** [golang/vscode-go#1048]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.15.5 darwin/amd64
- Run `gopls -v version` to get version of Gopls if you are using [the language server](https://github.com/golang/vscode-go/blob/master/docs/gopls.md).

```	
Build info
----------
golang.org/x/tools/gopls v0.6.0
    golang.org/x/tools/gopls@v0.6.1 h1:vD171EDBkyUVyp9B45IYXklV/VEfbHgX0FKw0Q0dO30=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/google/go-cmp@v0.5.1 h1:JFrFEBb2xKufg6XkJsJr+WbKb4FQlURi5RUcBveYu9k=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/mod@v0.3.0 h1:RM4zey1++hCTbCVQfnWeKs9/IEsaBLA8vTkd0WVtmH4=
    golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9 h1:SQFwaSi55rU7vdNs9Yr0Z324VNlrF+0wMqRXT4St8ck=
    golang.org/x/tools@v0.0.0-20201217163546-c88dec5c6b05 h1:4hzTNH658xirWc4MvAx9HK2/2hY6z42i1+lRK8OzeJE=
    golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1 h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=
    honnef.co/go/tools@v0.0.1-2020.1.6 h1:W18jzjh8mfPez+AwGLxmOImucz/IFjpNlrKVnaj2YVc=
    mvdan.cc/gofumpt@v0.0.0-20200927160801-5bfeb2e70dd6 h1:z+/YqapuV7VZPvBb3GYmuEJbA88M3PFUxaHilHYVCpQ=
    mvdan.cc/xurls/v2@v2.2.0 h1:NSZPykBXJFCetGZykLAxaL6SIpvbVy/UFEniIfHAa8A=
```

- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders

```
version: 1.52.1
commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
date: 2020-12-16T16:30:02.420Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.1.0
```

- Check your installed extensions to get the version of the VS Code Go extension

```
ID: golang.go
version: 0.19.1
```

- Run `go env` to get the go development environment details

```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/kelei/Library/Caches/go-build"
GOENV="/Users/kelei/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOMODCACHE="/usr/local/golang/pkg/mod"
GOOS="darwin"
GOPATH="/usr/local/golang"
GOPROXY="https://goproxy.io"
GOROOT="/usr/local/Cellar/go/1.15.5/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15.5/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build373493387=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

### Share the Go related settings you have added/edited

```
"go.testFlags": ["-v"],
"go.lintTool": "golint",
"go.lintOnSave": "file",
"go.useLanguageServer": true,
"go.formatTool": "goimports",
"go.gopath": "/usr/local/golang",
"go.languageServerFlags": ["-rpc.trace"],
"go.autocompleteUnimportedPackages": true,
"go.testEnvVars": {},
"[go]": {
  "editor.formatOnSave": true,
  "editor.codeActionsOnSave": {
    "source.organizeImports": true
  },
},
```

### Describe the bug

```
[2020-12-21 10:53:40.147] [exthost] [error] [golang.go] provider FAILED
[2020-12-21 10:53:40.147] [exthost] [error] Canceled: Canceled
	at LanguageClient.makeCancelError (~/.vscode/extensions/golang.go-0.19.1/dist/goMain.js:13018:24)
	at LanguageClient.handleFailedRequest (~/.vscode/extensions/golang.go-0.19.1/dist/goMain.js:13008:28)
	at ~/.vscode/extensions/golang.go-0.19.1/dist/goMain.js:11707:39
[2020-12-21 10:53:40.147] [exthost] [error] [golang.go] provider FAILED
[2020-12-21 10:53:40.147] [exthost] [error] Canceled: Canceled
	at LanguageClient.makeCancelError (~/.vscode/extensions/golang.go-0.19.1/dist/goMain.js:13018:24)
	at LanguageClient.handleFailedRequest (~/.vscode/extensions/golang.go-0.19.1/dist/goMain.js:13008:28)
	at ~/.vscode/extensions/golang.go-0.19.1/dist/goMain.js:11659:39
	at runNextTicks (internal/process/task_queues.js:59:5)
	at processImmediate (internal/timers.js:412:9)
```

### Steps to reproduce the behavior:

> output --> log(exthot)

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.

**Comment by hyangah** [comment]
@kelein Do you have any visible issue or problem in using the extension other than the verbose error logs?

**Comment by hyangah** [comment]
Upstream issue: https://github.com/microsoft/vscode-languageserver-node/issues/717
