### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by samj7792** [golang/vscode-go#1074]
gopls version: v0.6.1
gopls flags: 
extension version: 0.20.1
environment: Visual Studio Code

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>
Saving file causes glitched imports. To be honest I'm not totally sure.

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>
[Info  - 9:06:24 AM] 2020/12/31 09:06:24 go/packages.Load
	snapshot=0
	directory=/Users/samueljackson/Documents/Code/SJ/redux
	query=[builtin github.com/t1cg/SJ/redux/...]
	packages=11

[Error - 9:06:24 AM] 2020/12/31 09:06:24 creating workspace dir: mkdir /var/folders/vg/4t5qpjw57jx1rtfbd46t0dxw0000gn/T/gopls-3749.workspace: file exists

[Error - 9:06:24 AM] 2020/12/31 09:06:24 unable to compute error positions: no parsed file for file:///Users/samueljackson/Documents/Code/SJ/redux/api/customfunctions/post_login.go in github.com/t1cg/SJ/redux/api/customfunctions
	package="github.com/t1cg/SJ/redux/api/customfunctions"

golist_overlay.go:451: commonDir saw map[/Users/samueljackson/Documents/Code/SJ/redux/api/customFunctions:true /Users/samueljackson/Documents/Code/SJ/redux/api/customfunctions:true] for [/Users/samueljackson/Documents/Code/SJ/redux/api/customfunctions/get_record.go /Users/samueljackson/Documents/Code/SJ/redux/api/customfunctions/get_records.go /Users/samueljackson/Documents/Code/SJ/redux/api/customfunctions/post_register.go /Users/samueljackson/Documents/Code/SJ/redux/api/customFunctions/post_login.go]
[Error - 9:06:24 AM] Connection to server got closed. Server will not be restarted.
[Error - 9:06:24 AM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:94609:27)
	at Object.dispose (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:10537:35)
	at LanguageClient.handleConnectionClosed (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:12816:42)
	at LanguageClient.handleConnectionClosed (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:67230:15)
	at closeHandler (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:12803:18)
	at CallbackList.invoke (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22491:39)
	at Emitter.fire (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22553:36)
	at closeHandler (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:93821:26)
	at CallbackList.invoke (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22491:39)
	at Emitter.fire (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22553:36)
	at StreamMessageReader.fireClose (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:93208:27)
	at Socket.<anonymous> (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:93293:42)
	at Socket.emit (events.js:228:7)
	at Pipe.<anonymous> (net.js:664:12)
[Error - 9:06:24 AM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:94609:27)
	at Object.dispose (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:10537:35)
	at LanguageClient.handleConnectionClosed (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:12816:42)
	at LanguageClient.handleConnectionClosed (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:67230:15)
	at closeHandler (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:12803:18)
	at CallbackList.invoke (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22491:39)
	at Emitter.fire (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22553:36)
	at closeHandler (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:93821:26)
	at CallbackList.invoke (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22491:39)
	at Emitter.fire (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22553:36)
	at StreamMessageReader.fireClose (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:93208:27)
	at Socket.<anonymous> (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:93293:42)
	at Socket.emit (events.js:228:7)
	at Pipe.<anonymous> (net.js:664:12)
[Error - 9:06:24 AM] Request textDocument/documentLink failed.
Error: Connection got disposed.
	at Object.dispose (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:94609:27)
	at Object.dispose (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:10537:35)
	at LanguageClient.handleConnectionClosed (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:12816:42)
	at LanguageClient.handleConnectionClosed (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:67230:15)
	at closeHandler (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:12803:18)
	at CallbackList.invoke (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22491:39)
	at Emitter.fire (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22553:36)
	at closeHandler (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:93821:26)
	at CallbackList.invoke (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22491:39)
	at Emitter.fire (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22553:36)
	at StreamMessageReader.fireClose (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:93208:27)
	at Socket.<anonymous> (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:93293:42)
	at Socket.emit (events.js:228:7)
	at Pipe.<anonymous> (net.js:664:12)
[Error - 9:06:24 AM] Request textDocument/foldingRange failed.
Error: Connection got disposed.
	at Object.dispose (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:94609:27)
	at Object.dispose (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:10537:35)
	at LanguageClient.handleConnectionClosed (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:12816:42)
	at LanguageClient.handleConnectionClosed (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:67230:15)
	at closeHandler (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:12803:18)
	at CallbackList.invoke (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22491:39)
	at Emitter.fire (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22553:36)
	at closeHandler (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:93821:26)
	at CallbackList.invoke (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22491:39)
	at Emitter.fire (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22553:36)
	at StreamMessageReader.fireClose (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:93208:27)
	at Socket.<anonymous> (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:93293:42)
	at Socket.emit (events.js:228:7)
	at Pipe.<anonymous> (net.js:664:12)
[Error - 9:06:24 AM] Request textDocument/codeLens failed.
Error: Connection got disposed.
	at Object.dispose (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:94609:27)
	at Object.dispose (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:10537:35)
	at LanguageClient.handleConnectionClosed (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:12816:42)
	at LanguageClient.handleConnectionClosed (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:67230:15)
	at closeHandler (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:12803:18)
	at CallbackList.invoke (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22491:39)
	at Emitter.fire (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22553:36)
	at closeHandler (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:93821:26)
	at CallbackList.invoke (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22491:39)
	at Emitter.fire (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22553:36)
	at StreamMessageReader.fireClose (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:93208:27)
	at Socket.<anonymous> (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:93293:42)
	at Socket.emit (events.js:228:7)
	at Pipe.<anonymous> (net.js:664:12)
[Error - 9:06:24 AM] Request textDocument/codeLens failed.
Error: Connection got disposed.
	at Object.dispose (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:94609:27)
	at Object.dispose (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:10537:35)
	at LanguageClient.handleConnectionClosed (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:12816:42)
	at LanguageClient.handleConnectionClosed (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:67230:15)
	at closeHandler (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:12803:18)
	at CallbackList.invoke (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22491:39)
	at Emitter.fire (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22553:36)
	at closeHandler (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:93821:26)
	at CallbackList.invoke (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22491:39)
	at Emitter.fire (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22553:36)
	at StreamMessageReader.fireClose (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:93208:27)
	at Socket.<anonymous> (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:93293:42)
	at Socket.emit (events.js:228:7)
	at Pipe.<anonymous> (net.js:664:12)
[Error - 9:06:24 AM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:94609:27)
	at Object.dispose (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:10537:35)
	at LanguageClient.handleConnectionClosed (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:12816:42)
	at LanguageClient.handleConnectionClosed (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:67230:15)
	at closeHandler (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:12803:18)
	at CallbackList.invoke (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22491:39)
	at Emitter.fire (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22553:36)
	at closeHandler (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:93821:26)
	at CallbackList.invoke (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22491:39)
	at Emitter.fire (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:22553:36)
	at StreamMessageReader.fireClose (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:93208:27)
	at Socket.<anonymous> (/Users/samueljackson/.vscode/extensions/golang.go-0.20.1/dist/goMain.js:93293:42)
	at Socket.emit (events.js:228:7)
	at Pipe.<anonymous> (net.js:664:12)

Failed to auto-collect gopls trace: unrecognized crash pattern.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment]
@samj7792 Thank you so much for sharing the trace.

@stamblerre @findleyr It's still not clear what causes the connection between vscode and gopls to be disposed yet. Can  you please help checking 
  - whether the following condition was the root cause or a side-effect of repeated crash&restart
  - whether this is a fatal error or not. From the code ([session.go](https://github.com/golang/tools/blob/a543418bbed226001a4070d59e3948f32822fa7b/internal/lsp/cache/session.go#L255) and [check.go](https://github.com/golang/tools/blob/fd09bd90d85ca6c38cd19291b99dd54aed769555/internal/lsp/cache/check.go#L444) they don't look like a fatal error, but I don't know if this error later causes other problems in following operations.
  
```
[Info - 9:06:24 AM] 2020/12/31 09:06:24 go/packages.Load snapshot=0 directory=/Users/samueljackson/Documents/Code/SJ/redux query=[builtin github.com/t1cg/SJ/redux/...] packages=11

[Error - 9:06:24 AM] 2020/12/31 09:06:24 creating workspace dir: mkdir 
/var/folders/vg/4t5qpjw57jx1rtfbd46t0dxw0000gn/T/gopls-3749.workspace: file exists

[Error - 9:06:24 AM] 2020/12/31 09:06:24 unable to compute error positions: no parsed file for 
file:///Users/samueljackson/Documents/Code/SJ/redux/api/customfunctions/post_login.go in 
github.com/t1cg/SJ/redux/api/customfunctions
package="github.com/t1cg/SJ/redux/api/customfunctions"

golist_overlay.go:451: commonDir saw map[/Users/samueljackson/Documents/Code/SJ/redux/api/customFunctions:true 
/Users/samueljackson/Documents/Code/SJ/redux/api/customfunctions:true] for 
[/Users/samueljackson/Documents/Code/SJ/redux/api/customfunctions/get_record.go 
/Users/samueljackson/Documents/Code/SJ/redux/api/customfunctions/get_records.go 
/Users/samueljackson/Documents/Code/SJ/redux/api/customfunctions/post_register.go 
/Users/samueljackson/Documents/Code/SJ/redux/api/customFunctions/post_login.go]

[Error - 9:06:24 AM] Connection to server got closed. Server will not be restarted.
```

**Comment by findleyr** [comment]
> 2020/12/31 09:06:24 creating workspace dir: mkdir 
/var/folders/vg/4t5qpjw57jx1rtfbd46t0dxw0000gn/T/gopls-3749.workspace: file exists

We get this error because either this is not the first gopls instance started by the vscode process and an earlier instance was not shut down normally, or we are reusing a vscode pid and the gopls instance of the previous process was not cleaned up properly.  So most likely this is a side-effect of the gopls process having already crashed. This is not a fatal error.

**Comment by hyangah** [comment]
@findleyr That's what I thought initially. What about the `commonDir saw map ...` error message in check.go? After that, the connection to server got closed with no further logging.

@samj7792 Was that the first crash log message? Was there any server restart message before the section you shared with us?

**Comment by samj7792** [comment]
@hyangah I think that was the whole log. I'm new to using Golang, sorry I can't be more help. It seems like sometimes when saving it will delete parts of my code when trying to format things.

**Comment by findleyr** [comment]
@hyangah `commonDir saw map ...` is the fatal log message:
https://cs.opensource.google/go/x/tools/+/master:go/packages/golist_overlay.go;l=451;drc=d88ec18c69c70d818214bd2c98f3ce431ea4fd62

I'm not familiar with this code, but looking at the error it appears we're not handling case insensitivity correctly: customFunctions instead of customfunctions in the path to post_login.go. I'm guessing that this is HFS+, which (per my Googling) is case insensitive but case preserving.

I'm afraid this is not the only place where such an assumption is made.
