### ISSUE TITLE
Go vscode extension is not being installed

### ISSUE THREAD

**Issue by sangchul** [golang/vscode-go#1091]
### Describe the bug
I've used code-server 3.8.0 (vscode web version) for a long time with Go extension. but latest version of Go extension 0.20.2 is not installed 

```
$ code-server --install-extension golang.Go
Installing extensions...
Installing extension 'golang.go' v0.20.2...
Unexpected end of data
[2021-01-13T08:03:06.504Z] error vscode Failed Installing Extensions: golang.go
[2021-01-13T08:03:06.505Z] error vscode Error: Failed Installing Extensions: golang.go
    at J.installExtensions (/home1/irteamsu/packages/code-server-3.8.0-linux-amd64/lib/vscode/out/vs/server/entry.js:540:516)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async J.run (/home1/irteamsu/packages/code-server-3.8.0-linux-amd64/lib/vscode/out/vs/server/entry.js:538:205)
    at async /home1/irteamsu/packages/code-server-3.8.0-linux-amd64/lib/vscode/out/vs/server/entry.js:545:678
    at async process.<anonymous> (/home1/irteamsu/packages/code-server-3.8.0-linux-amd64/lib/vscode/out/vs/server/entry.js:553:912)
```

I tried other extensions to uninstall/install and they are fine.

Thanks in advance

**Comment by sangchul** [comment]
I've installed golang.Go@0.20.2 from vsix file.

**Comment by hyangah** [comment]
@sangchul Please reopen or open a new issue if download&clean-reinstall doesn't fix the problem. Thanks!
