### ISSUE TITLE
go-nightly not working

### ISSUE THREAD

**Issue by drrrMikado** [golang/vscode-go#1193]
### What version of Go, VS Code & VS Code Go extension are you using?
Go Version: 1.15.6
VS Code Version: 1.53.0
Go Nightly Version: 2021.2.414

### Describe the bug
go-nightly extension not working.But stable go extension can work.

### Steps to reproduce the behavior:
1. install go-nightly
2. editing any .go file

### Screenshots or recordings
In Output Log(Extension Host):
![image](https://user-images.githubusercontent.com/11224565/107018980-16ec8f00-67dc-11eb-8b9c-80635ca1872b.png)
Plain Text:
```
[2021-02-05 17:32:56.168] [exthost] [error] Activating extension golang.go-nightly failed due to an error:
[2021-02-05 17:32:56.172] [exthost] [error] TypeError: Invalid Version: null
	at new SemVer (c:\Users\User\.vscode\extensions\golang.go-nightly-2021.2.414\dist\goMain.js:9344:13)
	at compare (c:\Users\User\.vscode\extensions\golang.go-nightly-2021.2.414\dist\goMain.js:10188:32)
	at Object.gte (c:\Users\User\.vscode\extensions\golang.go-nightly-2021.2.414\dist\goMain.js:26481:30)
	at shouldShowGoWelcomePage (c:\Users\User\.vscode\extensions\golang.go-nightly-2021.2.414\dist\goMain.js:13815:19)
	at showGoWelcomePage (c:\Users\User\.vscode\extensions\golang.go-nightly-2021.2.414\dist\goMain.js:13801:9)
	at c:\Users\User\.vscode\extensions\golang.go-nightly-2021.2.414\dist\goMain.js:13450:9
	at Generator.next (<anonymous>)
	at fulfilled (c:\Users\User\.vscode\extensions\golang.go-nightly-2021.2.414\dist\goMain.js:13373:58)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Thanks, I hope it's understood because my English is very poor.

**Comment by stamblerre** [comment]
Fixed by https://go-review.googlesource.com/c/vscode-go/+/289969.

**Comment by hyangah** [comment]
Thank you for the report @drrrMikado 
v2021.2.516 is now available with the fix.
