### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by arashpayan** [golang/vscode-go#1244]
gopls version: v0.6.5
gopls flags: 
extension version: 0.22.1
environment: Visual Studio Code linux
initialization error: undefined
manual restart count: 0
total start count: 2

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

I was just reading code when the crash happened.

```
<pre>panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7bed97]

goroutine 13950 [running]:
go/types.(*Package).Path(...)
	  package.go:31
golang.org/x/tools/internal/lsp/source.HoverIdentifier(0xefd558, 0xc01ace18f0, 0xc01ac17680, 0x0, 0x0, 0x0)
	  hover.go:190  0x437
golang.org/x/tools/internal/lsp/source.Hover(0xefd558, 0xc01a050200, 0xf0e880, 0xc011540540, 0xf01038, 0xc000df8a80, 0x407c300000000000, 0x4036000000000000, 0xf06078, 0xc000df8a80, ...)
	  hover.go:64  0xdb
golang.org/x/tools/internal/lsp.(*Server).hover(0xc0001aa460, 0xefd558, 0xc01a050200, 0xc01acc1f80, 0x0, 0x0, 0x0)
	  hover.go:25  0x2ce
golang.org/x/tools/internal/lsp.(*Server).Hover(0xc0001aa460, 0xefd558, 0xc01a050200, 0xc01acc1f80, 0xc01acc1f80, 0x0, 0x0)
	  server_gen.go:100  0x49
golang.org/x/tools/internal/lsp/protocol.serverDispatch(0xefd558, 0xc01a050200, 0xf11108, 0xc0001aa460, 0xc01acc1f50, 0xefd750, 0xc01a050180, 0x65c22a, 0xeec8a0, 0xc000010020)
	  tsserver.go:299  0x1b85
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0xefd558, 0xc01a050200, 0xc01acc1f50, 0xefd750, 0xc01a050180, 0xc004ffca406c1a57, 0x549e7b56)
	  protocol.go:63  0xc5
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0xefd558, 0xc01a050200, 0xc01acc1f50, 0xefd750, 0xc01a050180, 0x0, 0x0)
	  lsprpc.go:560  0x452
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0xefd558, 0xc01a050200, 0xc01a058000, 0xefd750, 0xc01a050180, 0xc01abe3600, 0x443c96)
	  handler.go:35  0xd7
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc0002932c0, 0xc01a056480, 0xc000860130, 0xefd558, 0xc01a050200, 0xc01a058000, 0xefd750, 0xc01a050180)
	  handler.go:103  0x86
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x173
[Error - 2:30:01 AM] </pre>
```

**Comment by stamblerre** [comment]
Thank you for the report. I believe that this should be fixed in the next `gopls` release, v0.6.6, which will be available today.
