### ISSUE TITLE
testing: setBreakpoints tests failing in dlv-dap mode

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#1390]
Fixing async/await bugs in the test (https://go-review.googlesource.com/c/vscode-go/+/306549) surfaced this issue:

 ```
  1) Go Debug Adapter Tests (dlv-dap)
       setBreakpoints
         should set breakpoints during next:

      AssertionError [ERR_ASSERTION]: 'step' == 'next cancelled'
      + expected - actual

      -step
      +next cancelled
      
  	at /workspace/node_modules/vscode-debugadapter-testsupport/lib/debugClient.js:275:20
  	at runMicrotasks (<anonymous>)
  	at processTicksAndRejections (internal/process/task_queues.js:97:5)
  	at async Promise.all (index 1)


  2) Go Debug Adapter Tests (dlv-dap)
       setBreakpoints
         should set breakpoints during step out:

      AssertionError [ERR_ASSERTION]: 'breakpoint' == 'next cancelled'
      + expected - actual

      -breakpoint
      +next cancelled
      
  	at /workspace/node_modules/vscode-debugadapter-testsupport/lib/debugClient.js:275:20
  	at runMicrotasks (<anonymous>)
  	at processTicksAndRejections (internal/process/task_queues.js:97:5)
  	at async Promise.all (index 1)
 ``` 	
 cc @suzmue

**Comment by alichtl** [comment]
@polinasok - Do you know if there is a workaround for this? I'm able to attach the debugger to a remote process, step through code, and inspect variables, but am not able to set breakpoints. I've verified that main.go is source mapped via `substitutePath`,  and the breakpoints show as fine (solid red circles) in VS Code, but I don't see the setBreakpoint information sent over to Delve via DAP. I feel like I'm so close to having a fully-working debugging setup, and hope there's a workaround or easy fix for this. A full reproduction of the issue is at https://github.com/alichtl/go-remote-debug-delve and I'm running in Windows WSL2.

I'm building with: `go build -gcflags "all=-N -l" -o ./app`

Launching the remote process with: `dlv --listen=:2345 --headless=true --log=true --log-output=debugger,debuglineerr,gdbwire,lldbout,rpc --accept-multiclient --api-version=2 exec ./app`

And my launch.json file contains:
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Attach",
      "type": "go",
      "request": "attach",
      "mode": "remote",
      "debugAdapter": "dlv-dap",
      "substitutePath": [
        {
          "from": "${workspaceFolder}",
          "to": "/"
        }
      ],
      "port": 2345,
      "host": "127.0.0.1",
      "showLog": true,
      "trace": "log",
      "logOutput": "rpc",
      "stopOnEntry": true
    }
  ]
}
```

**Comment by firelizzard18** [comment]
@alichtl This is issue is specifically about vscode-go's tests failing so you may want to create a new issue. `"trace": "trace"` will give you the most verbose logging.
