### ISSUE TITLE
test: Go Debug Adapter Tests (dlv-dap) "set current working directory" is flaky

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#1439]
From https://source.cloud.google.com/results/invocations/59b0c6b1-b6e8-4d91-814e-9a8927cc2968/targets/golang%2Fvscode-go%2Fgcp_ubuntu%2Fpresubmit/log
```
  1 failing
  1) Go Debug Adapter Tests (dlv-dap)
       set current working directory
         should run program without cwd set (noDebug):
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/workspace/out/test/integration/goDebug.test.js)
  	at listOnTimeout (internal/timers.js:549:17)
  	at processTimers (internal/timers.js:492:7)
```
But DAP trace shows 
```
<- server: {"seq":0,"type":"event","event":"output","body":{"category":"stdout","output":"Goodbye, World.\n"}}
```

<details>
<summary>DAP Trace from the failed tests</summary>
```

      1) should run program without cwd set (noDebug)

should run program without cwd set (noDebug) FAILED: DAP Trace

>> accepted connection from client
-> server: {"type":"request","seq":1,"command":"initialize","arguments":{"adapterID":"go","linesStartAt1":true,"columnsStartAt1":true,"pathFormat":"path"}}

<- server: {"seq":0,"type":"event","event":"output","body":{"category":"console","output":"Running: /go/bin/dlv-dap dap --listen=127.0.0.1:33979 --log=true --log-output=dap\n"}}
<- server: {"seq":0,"type":"event","event":"output","body":{"category":"stdout","output":"DAP server listening at: 127.0.0.1:33979\n"}}

<- server: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"2021-04-19T20:54:18Z debug layer=dap DAP server pid = 11692\n"}}

<- server: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"2021-04-19T20:54:18Z debug layer=dap [<- from client]{\"seq\":1,\"type\":\"request\",\"command\":\"initialize\",\"arguments\":{\"adapterID\":\"go\",\"linesStartAt1\":true,\"columnsStartAt1\":true,\"pathFormat\":\"path\"}}\n"}}

<- server: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"2021-04-19T20:54:18Z debug layer=dap [-> to client]{\"seq\":0,\"type\":\"response\",\"request_seq\":1,\"success\":true,\"command\":\"initialize\",\"body\":{\"supportsConfigurationDoneRequest\":true,\"supportsConditionalBreakpoints\":true,\"supportTerminateDebuggee\":true,\"supportsDelayedStackTraceLoading\":true}}\n"}}

<- server: {"seq":0,"type":"response","request_seq":1,"success":true,"command":"initialize","body":{"supportsConfigurationDoneRequest":true,"supportsConditionalBreakpoints":true,"supportTerminateDebuggee":true,"supportsDelayedStackTraceLoading":true}}

-> server: {"type":"request","seq":2,"command":"launch","arguments":{"name":"Launch","type":"go","request":"launch","mode":"debug","program":"/workspace/test/testdata/cwdTest/cwdTest","noDebug":true,"debugAdapter":"dlv-dap","logOutput":"dap","showLog":true,"packagePathToGoModPathMap":{"/workspace/vscodego/go/src/test/testfixture":"/workspace/vscodego/go/src/test/testfixture","/workspace/vscodego/go/src/test/testfixture/baseTest":"","/workspace/vscodego/go/src/test/testfixture/gogetdocTestData":"","/workspace/vscodego/go/src/test/testfixture/completions":"","/workspace/vscodego/go/src/test/testfixture/testTags":"","/tmp/legacy0aLt4G/testfixture/baseTest":"/tmp/legacy0aLt4G/testfixture/baseTest","/tmp/legacy0aLt4G/testfixture/completions":"/tmp/legacy0aLt4G/testfixture/completions","/tmp/legacy0aLt4G/testfixture/testTags":"/tmp/legacy0aLt4G/testfixture/testTags"},"apiVersion":2,"dlvLoadConfig":{"followPointers":true,"maxVariableRecurse":1,"maxStringLen":64,"maxArrayValues":64,"maxStructFields":-1},"showGlobalVariables":false,"dlvToolPath":"/go/bin/dlv-dap"}}

<- server: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"2021-04-19T20:54:18Z debug layer=dap [<- from client]{\"seq\":2,\"type\":\"request\",\"command\":\"launch\",\"arguments\":{\"apiVersion\":2,\"debugAdapter\":\"dlv-dap\",\"dlvLoadConfig\":{\"followPointers\":true,\"maxArrayValues\":64,\"maxStringLen\":64,\"maxStructFields\":-1,\"maxVariableRecurse\":1},\"dlvToolPath\":\"/go/bin/dlv-dap\",\"logOutput\":\"dap\",\"mode\":\"debug\",\"name\":\"Launch\",\"noDebug\":true,\"packagePathToGoModPathMap\":{\"/tmp/legacy0aLt4G/testfixture/baseTest\":\"/tmp/legacy0aLt4G/testfixture/baseTest\",\"/tmp/legacy0aLt4G/testfixture/completions\":\"/tmp/legacy0aLt4G/testfixture/completions\",\"/tmp/legacy0aLt4G/testfixture/testTags\":\"/tmp/legacy0aLt4G/testfixture/testTags\",\"/workspace/vscodego/go/src/test/testfixture\":\"/workspace/vscodego/go/src/test/testfixture\",\"/workspace/vscodego/go/src/test/testfixture/baseTest\":\"\",\"/workspace/vscodego/go/src/test/testfixture/completions\":\"\",\"/workspace/vscodego/go/src/test/testfixture/gogetdocTestData\":\"\",\"/workspace/vscodego/go/src/test/testfixture/testTags\":\"\"},\"program\":\"/workspace/test/testdata/cwdTest/cwdTest\",\"request\":\"launch\",\"showGlobalVariables\":false,\"showLog\":true,\"type\":\"go\"}}\n"}}

<- server: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"2021-04-19T20:54:18Z debug layer=dap building binary at /workspace/test/testdata/cwdTest/cwdTest/__debug_bin\n"}}

<- server: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"2021-04-19T20:54:18Z debug layer=dap [-> to client]{\"seq\":0,\"type\":\"response\",\"request_seq\":2,\"success\":true,\"command\":\"launch\"}\n"}}

<- server: {"seq":0,"type":"response","request_seq":2,"success":true,"command":"launch"}

<- server: {"seq":0,"type":"event","event":"output","body":{"category":"console","output":"Process 11760 has exited with status 0\n","source":{}}}

<- server: {"seq":0,"type":"event","event":"terminated","body":{}}

<- server: {"seq":0,"type":"event","event":"output","body":{"category":"stdout","output":"Goodbye, World.\n"}}

<- server: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"2021-04-19T20:54:18Z debug layer=dap [-> to client]{\"seq\":0,\"type\":\"event\",\"event\":\"output\",\"body\":{\"category\":\"console\",\"output\":\"Process 11760 has exited with status 0\\n\",\"source\":{}}}\n2021-04-19T20:54:18Z debug layer=dap [-> to client]{\"seq\":0,\"type\":\"event\",\"event\":\"terminated\",\"body\":{}}\n"}}

-> server: {"type":"request","seq":3,"command":"disconnect"}

<- server: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"2021-04-19T20:55:18Z debug layer=dap [<- from client]{\"seq\":3,\"type\":\"request\",\"command\":\"disconnect\",\"arguments\":{}}\n2021-04-19T20:55:18Z debug layer=dap [-> to client]{\"seq\":0,\"type\":\"response\",\"request_seq\":3,\"success\":true,\"command\":\"disconnect\"}\n2021-04-19T20:55:18Z debug layer=dap DAP server stopping...\n"}}

<- server: {"seq":0,"type":"response","request_seq":3,"success":true,"command":"disconnect"}
```
</details>

**Comment by suzmue** [comment]
This actually seems like it's not a flake it is just wrong. The program is running in the wrong folder.

It is timing out because the OutputEvent did not match. I can add a check that will make it more obvious that it got the wrong message and fix the issue.

**Comment by suzmue** [comment]
This happens when the process termination message is sent before the stdout. The code only handles this well if the output is the first output message received.
