### ISSUE TITLE
test/integration/goDebug: remote attach test is flaky

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#1456]
The remote test is flaky and is blocking releases.

```
    remote attach

Sending initializing request for remote attach setup.

Setting up attach request for {"name":"Attach","type":"go","request":"attach","mode":"remote","host":"127.0.0.1","port":39411,"packagePathToGoModPathMap":{"/home/runner/go/src/test/testfixture":"/home/runner/go/src/test/testfixture","/home/runner/go/src/test/testfixture/baseTest":"","/home/runner/go/src/test/testfixture/gogetdocTestData":"","/home/runner/go/src/test/testfixture/completions":"","/home/runner/go/src/test/testfixture/testTags":"","/tmp/legacy8KOQJ6/testfixture/baseTest":"/tmp/legacy8KOQJ6/testfixture/baseTest","/tmp/legacy8KOQJ6/testfixture/completions":"/tmp/legacy8KOQJ6/testfixture/completions","/tmp/legacy8KOQJ6/testfixture/testTags":"/tmp/legacy8KOQJ6/testfixture/testTags"},"apiVersion":2,"dlvLoadConfig":{"followPointers":true,"maxVariableRecurse":1,"maxStringLen":64,"maxArrayValues":64,"maxStructFields":-1},"showGlobalVariables":false,"cwd":"${workspaceFolder}","debugAdapter":"legacy","dlvToolPath":"/home/runner/go/bin/dlv"}.

Sending configuration done request for remote attach setup.

      ✓ can connect and initialize using external dlv --headless --accept-multiclient=true --continue=true (10310ms)

      1) "after each" hook for "can connect and initialize using external dlv --headless --accept-multiclient=true --continue=true"
      ...

  1) Go Debug Adapter Tests (legacy)
       "after each" hook for "can connect and initialize using external dlv --headless --accept-multiclient=true --continue=true":
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/vscode-go/vscode-go/out/test/integration/goDebug.test.js)
  	at listOnTimeout (internal/timers.js:554:17)
  	at processTimers (internal/timers.js:497:7)
```

**Comment by suzmue** [comment]
Looks like the flaky issue is in the teardown logic, I'll send a patch to try to mitigate the issue.

**Comment by hyangah** [comment]
Skipping those tests didn't seem to be sufficient. I will retry to release nightly after @suzmue's pending changes to address the underlying issue and [cl/314589](https://go-review.googlesource.com/c/vscode-go/+/314589) are  submitted.
