### ISSUE TITLE
debug: dlv-dap logDest setup using <fd> doesn't work on windows

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#1472]
dlv-dap tests failed on windows due to this issue.
For golang/vscode-go#1407, we set up a pipe with a file descriptor and and ran delve with `--log-dest=<fd>`. This doesn't seem to work on windows. 

```
  2) Go Debug Adapter Tests (dlv-dap)
       initialize
         should return supported features:
     Error: Unexpected error from dlv dap on start: 'Failed to write to log, write delve-logs: The handle is invalid.
'
  	at stopWaitingForServerToStart (d:\a\vscode-go\vscode-go\out\src\goDebugFactory.js:361:28)
  	at Socket.<anonymous> (d:\a\vscode-go\vscode-go\out\src\goDebugFactory.js:375:21)
  	at addChunk (_stream_readable.js:295:12)
  	at readableAddChunk (_stream_readable.js:271:9)
  	at Socket.Readable.push (_stream_readable.js:212:10)
  	at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
 ``` 	

This will prevent Windows users from using dlv-dap, so this is a release blocker. We can temporarily disable this feature for windows users.

**Comment by hyangah** [comment]
Removing release-blocker since it's now disabled on windows.
