### ISSUE TITLE
debug: should cleanup when stopped test failing

### ISSUE THREAD

**Issue by suzmue** [golang/vscode-go#1481]
Delve version:
`go: downloading github.com/go-delve/delve v1.6.1-0.20210504195617-c5d58f494a26`

Failure:
```
  1) Go Debug Adapter Tests (dlv-dap)
       disconnect
         should cleanup when stopped:
     AssertionError [ERR_ASSERTION]: debug output /home/runner/work/vscode-go/vscode-go/test/testdata/loop/_loop_output wasn't cleaned up. {"dev":2049,"mode":33261,"nlink":1,"uid":1001,"gid":121,"rdev":0,"blksize":4096,"ino":169328,"size":1252233,"blocks":2448,"atimeMs":1620259059537.0925,"mtimeMs":1620259059533.0923,"ctimeMs":1620259059533.0923,"birthtimeMs":1620259059465.0862,"atime":"2021-05-05T23:57:39.537Z","mtime":"2021-05-05T23:57:39.533Z","ctime":"2021-05-05T23:57:39.533Z","birthtime":"2021-05-05T23:57:39.465Z"}
  	at Context.<anonymous> (out/test/integration/goDebug.test.js:1436:24)
  	at Generator.next (<anonymous>)
  	at fulfilled (out/test/integration/goDebug.test.js:5:58)

```

Log:
```
should cleanup when stopped FAILED: DAP Trace

>> accepted connection from client

-> server: {"type":"request","seq":1,"command":"initialize","arguments":{"adapterID":"go","linesStartAt1":true,"columnsStartAt1":true,"pathFormat":"path"}}

<- server: {"seq":0,"type":"event","event":"output","body":{"category":"console","output":"2021-05-05T23:57:39Z debug layer=dap [<- from client]{\"seq\":1,\"type\":\"request\",\"command\":\"initialize\",\"arguments\":{\"adapterID\":\"go\",\"linesStartAt1\":true,\"columnsStartAt1\":true,\"pathFormat\":\"path\"}}\n"}}

<- server: {"seq":0,"type":"event","event":"output","body":{"category":"console","output":"2021-05-05T23:57:39Z debug layer=dap [-> to client]{\"seq\":0,\"type\":\"response\",\"request_seq\":1,\"success\":true,\"command\":\"initialize\",\"body\":{\"supportsConfigurationDoneRequest\":true,\"supportsConditionalBreakpoints\":true,\"supportTerminateDebuggee\":true,\"supportsDelayedStackTraceLoading\":true}}\n"}}

<- server: {"seq":0,"type":"response","request_seq":1,"success":true,"command":"initialize","body":{"supportsConfigurationDoneRequest":true,"supportsConditionalBreakpoints":true,"supportTerminateDebuggee":true,"supportsDelayedStackTraceLoading":true}}

-> server: {"type":"request","seq":2,"command":"launch","arguments":{"name":"Launch","type":"go","request":"launch","mode":"debug","program":"/home/runner/work/vscode-go/vscode-go/test/testdata/loop","stopOnEntry":false,"output":"/home/runner/work/vscode-go/vscode-go/test/testdata/loop/_loop_output","debugAdapter":"dlv-dap","logOutput":"dap","showLog":true,"trace":"verbose","packagePathToGoModPathMap":{"/home/runner/go/src/test/testfixture":"/home/runner/go/src/test/testfixture","/home/runner/go/src/test/testfixture/baseTest":"","/home/runner/go/src/test/testfixture/gogetdocTestData":"","/home/runner/go/src/test/testfixture/completions":"","/home/runner/go/src/test/testfixture/testTags":"","/tmp/legacynN0wui/testfixture/baseTest":"/tmp/legacynN0wui/testfixture/baseTest","/tmp/legacynN0wui/testfixture/completions":"/tmp/legacynN0wui/testfixture/completions","/tmp/legacynN0wui/testfixture/testTags":"/tmp/legacynN0wui/testfixture/testTags"},"apiVersion":2,"dlvLoadConfig":{"followPointers":true,"maxVariableRecurse":1,"maxStringLen":64,"maxArrayValues":64,"maxStructFields":-1},"showGlobalVariables":false,"dlvToolPath":"/home/runner/go/bin/dlv-dap"}}

<- server: {"seq":0,"type":"event","event":"output","body":{"category":"console","output":"2021-05-05T23:57:39Z debug layer=dap [<- from client]{\"seq\":2,\"type\":\"request\",\"command\":\"launch\",\"arguments\":{\"apiVersion\":2,\"debugAdapter\":\"dlv-dap\",\"dlvLoadConfig\":{\"followPointers\":true,\"maxArrayValues\":64,\"maxStringLen\":64,\"maxStructFields\":-1,\"maxVariableRecurse\":1},\"dlvToolPath\":\"/home/runner/go/bin/dlv-dap\",\"logOutput\":\"dap\",\"mode\":\"debug\",\"name\":\"Launch\",\"output\":\"/home/runner/work/vscode-go/vscode-go/test/testdata/loop/_loop_output\",\"packagePathToGoModPathMap\":{\"/home/runner/go/src/test/testfixture\":\"/home/runner/go/src/test/testfixture\",\"/home/runner/go/src/test/testfixture/baseTest\":\"\",\"/home/runner/go/src/test/testfixture/completions\":\"\",\"/home/runner/go/src/test/testfixture/gogetdocTestData\":\"\",\"/home/runner/go/src/test/testfixture/testTags\":\"\",\"/tmp/legacynN0wui/testfixture/baseTest\":\"/tmp/legacynN0wui/testfixture/baseTest\",\"/tmp/legacynN0wui/testfixture/completions\":\"/tmp/legacynN0wui/testfixture/completions\",\"/tmp/legacynN0wui/testfixture/testTags\":\"/tmp/legacynN0wui/testfixture/testTags\"},\"program\":\"/home/runner/work/vscode-go/vscode-go/test/testdata/loop\",\"request\":\"launch\",\"showGlobalVariables\":false,\"showLog\":true,\"stopOnEntry\":false,\"trace\":\"verbose\",\"type\":\"go\"}}\n2021-05-05T23:57:39Z debug layer=dap building binary at /home/runner/work/vscode-go/vscode-go/test/testdata/loop/_loop_output\n"}}

<- server: {"seq":0,"type":"event","event":"output","body":{"category":"console","output":"2021-05-05T23:57:39Z debug layer=dap running program in /home/runner/work/vscode-go/vscode-go/test/testdata/loop\n\n"}}

<- server: {"seq":0,"type":"event","event":"output","body":{"category":"console","output":"2021-05-05T23:57:39Z debug layer=dap [-> to client]{\"seq\":0,\"type\":\"event\",\"event\":\"initialized\"}\n"}}

<- server: {"seq":0,"type":"event","event":"output","body":{"category":"console","output":"2021-05-05T23:57:39Z debug layer=dap [-> to client]{\"seq\":0,\"type\":\"response\",\"request_seq\":2,\"success\":true,\"command\":\"launch\"}\n"}}

<- server: {"seq":0,"type":"event","event":"initialized"}

<- server: {"seq":0,"type":"response","request_seq":2,"success":true,"command":"launch"}

-> server: {"type":"request","seq":3,"command":"configurationDone"}

<- server: {"seq":0,"type":"event","event":"output","body":{"category":"console","output":"2021-05-05T23:57:39Z debug layer=dap [<- from client]{\"seq\":3,\"type\":\"request\",\"command\":\"configurationDone\",\"arguments\":{}}\n"}}

<- server: {"seq":0,"type":"event","event":"output","body":{"category":"console","output":"2021-05-05T23:57:39Z debug layer=dap [-> to client]{\"seq\":0,\"type\":\"response\",\"request_seq\":3,\"success\":true,\"command\":\"configurationDone\"}\n"}}

<- server: {"seq":0,"type":"response","request_seq":3,"success":true,"command":"configurationDone"}

-> server: {"type":"request","seq":4,"command":"disconnect","arguments":{"restart":false}}

<- server: {"seq":0,"type":"event","event":"output","body":{"category":"console","output":"2021-05-05T23:57:39Z debug layer=dap [<- from client]{\"seq\":4,\"type\":\"request\",\"command\":\"disconnect\",\"arguments\":{}}\n"}}

<- server: {"seq":0,"type":"event","event":"output","body":{"category":"console","output":"2021-05-05T23:57:39Z debug layer=dap \"continue\" command stopped - reason \"manual\"\n2021-05-05T23:57:39Z debug layer=dap [-> to client]{\"seq\":0,\"type\":\"event\",\"event\":\"stopped\",\"body\":{\"reason\":\"pause\",\"threadId\":1,\"allThreadsStopped\":true}}\n"}}

<- server: {"seq":0,"type":"event","event":"output","body":{"category":"console","output":"2021-05-05T23:57:39Z debug layer=dap [-> to client]{\"seq\":0,\"type\":\"event\",\"event\":\"output\",\"body\":{\"category\":\"console\",\"output\":\"Detaching and terminating target process\\n\",\"source\":{}}}\n"}}
<- server: {"seq":0,"type":"event","event":"stopped","body":{"reason":"pause","threadId":1,"allThreadsStopped":true}}

<- server: {"seq":0,"type":"event","event":"output","body":{"category":"console","output":"Detaching and terminating target process\n","source":{}}}

adapter disposing

adapter disposed

<- server: {"seq":0,"type":"event","event":"output","body":{"category":"console","output":"2021-05-05T23:57:39Z debug layer=dap DAP server stopping...\n"}}
```

**Comment by suzmue** [comment]
@hyangah  I think this is fixed now?
