### ISSUE TITLE
"Go: Lint Workspace" fails if the previous lint returned no warnings or errors

### ISSUE THREAD

**Issue by BenLubar** [golang/vscode-go#1520]
### What version of Go, VS Code & VS Code Go extension are you using?
* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- `go version go1.16.4 linux/amd64`
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- ```
      Build info
      ----------
      golang.org/x/tools/gopls v0.6.11
          golang.org/x/tools/gopls@v0.6.11 h1:7S2k0xuVYc3secjy2uz0n+fGYxGJU6gXsLOmQ/r1HoI=
          github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
          github.com/google/go-cmp@v0.5.5 h1:Khx7svrCpmxxtHBq5j2mp/xVjsi8hQMfNLvJFAlrGgU=
          github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
          golang.org/x/mod@v0.4.2 h1:Gz96sIWK3OalVv/I/qNygP42zyoKp3xptRVCWRFEBvo=
          golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c h1:5KslGYwFpkhGh+Q16bwMP3cOontH8FOep7tGV86Y7SQ=
          golang.org/x/sys@v0.0.0-20210403161142-5e06dd20ab57 h1:F5Gozwx4I1xtr/sr/8CFbb57iKi3297KFs0QDbGN60A=
          golang.org/x/tools@v0.1.1-0.20210504170620-03ebc2c9fca8 h1:rTLms91GhM16y4sUcNGLdel0jJ8jXdQeXuN+7evgYiQ=
          golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1 h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=
          honnef.co/go/tools@v0.1.3 h1:qTakTkI6ni6LFD5sBwwsdSO+AQqbSIxOauHTTQKZ/7o=
          mvdan.cc/gofumpt@v0.1.1 h1:bi/1aS/5W00E2ny5q65w9SnKpWEF/UIOqDYBILpo9rA=
          mvdan.cc/xurls/v2@v2.2.0 h1:NSZPykBXJFCetGZykLAxaL6SIpvbVy/UFEniIfHAa8A=
      ```
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- ```
      1.56.2
      054a9295330880ed74ceaedda236253b4f39a335
      x64
      ```
* Check your installed extensions to get the version of the VS Code Go extension
	- `v0.25.0`
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- ```
      Checking configured tools....
      GOBIN: /home/ben/go/bin
      toolsGopath: 
      gopath: /home/ben/.golang-path
      GOROOT: /usr/local/go
      PATH: /usr/local/go/bin:/home/ben/.vscode-server/bin/054a9295330880ed74ceaedda236253b4f39a335/bin:/home/ben/.local/bin:/home/ben/bin:/home/ben/go/bin:/storage/_mxe/usr/bin:/home/ben/.cargo/bin:/home/ben/.vscode-server/bin/054a9295330880ed74ceaedda236253b4f39a335/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
      
         gopkgs: /home/ben/go/bin/gopkgs installed
         go-outline: /home/ben/go/bin/go-outline installed
         gotests: /home/ben/go/bin/gotests installed
         gomodifytags: /home/ben/go/bin/gomodifytags installed
         impl: /home/ben/go/bin/impl installed
         goplay: /home/ben/go/bin/goplay installed
         dlv: /home/ben/go/bin/dlv installed
         dlv-dap: /home/ben/go/bin/dlv-dap installed
         golangci-lint: /home/ben/go/bin/golangci-lint installed
         gopls: /home/ben/go/bin/gopls installed
      
      go env
      Workspace Folder (spy-cards): /home/ben/src/games/spy-cards
      	GO111MODULE=""
      	GOARCH="wasm"
      	GOBIN="/home/ben/go/bin"
      	GOCACHE="/home/ben/.cache/go-build"
      	GOENV="/home/ben/.config/go/env"
      	GOEXE=""
      	GOFLAGS=""
      	GOHOSTARCH="amd64"
      	GOHOSTOS="linux"
      	GOINSECURE=""
      	GOMODCACHE="/home/ben/.golang-path/pkg/mod"
      	GONOPROXY=""
      	GONOSUMDB=""
      	GOOS="js"
      	GOPATH="/home/ben/.golang-path"
      	GOPRIVATE=""
      	GOPROXY="https://proxy.golang.org,direct"
      	GOROOT="/usr/local/go"
      	GOSUMDB="sum.golang.org"
      	GOTMPDIR=""
      	GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
      	GOVCS=""
      	GOVERSION="go1.16.4"
      	GCCGO="gccgo"
      	GOWASM=""
      	AR="ar"
      	CC="gcc"
      	CXX="g++"
      	CGO_ENABLED="0"
      	GOMOD="/home/ben/src/games/spy-cards/go.mod"
      	CGO_CFLAGS="-g -O2"
      	CGO_CPPFLAGS=""
      	CGO_CXXFLAGS="-g -O2"
      	CGO_FFLAGS="-g -O2"
      	CGO_LDFLAGS="-g -O2"
      	PKG_CONFIG="pkg-config"
      	GOGCCFLAGS="-fPIC -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build512674815=/tmp/go-build -gno-record-gcc-switches"
      ```

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

```json
{
    "[go]": {
        "editor.formatOnSave": true,
        "editor.snippetSuggestions": "none"
    },
    "go.toolsManagement.autoUpdate": true,
    "go.toolsEnvVars": {
        "GOOS": "js",
        "GOARCH": "wasm"
    },
    "go.lintTool": "golangci-lint"
}
```

### Describe the bug
Running `Go: Lint Workspace` fails with an undescriptive error (screenshot below) if the previous (automatic?) run returned no warnings.

### Steps to reproduce the behavior:
1. Close all files.
2. Open a file in a package with no linter errors.
3. Ctrl+Shift+P -> Go: Lint Workspace
4. Notification in screenshot below appears.

Workaround: focus the "Output" pane before running Go: Lint Workspace. Not sure why this makes it work.

### Screenshots or recordings
![image](https://user-images.githubusercontent.com/4257305/119057995-22cb1e00-b993-11eb-96ab-8d6119a21af4.png)

**Comment by hyangah** [comment]
@BenLubar Indeed that error message isn't very helpful. When this happened, was there any log in Output channels (Go, Log (Extension Host) in particular)? 
And also please check if there is any other crash log in  Cmd+Shift+P -> Developer: Toggle Developer Tools -> Console.

**Comment by hyangah** [comment]
Thanks! Looks like this is the place that caused an exception.
https://github.com/golang/vscode-go/blob/9b2b1efcf9cd98005bcf14125c322feee922aec8/src/goLint.ts#L23 is the corresponding place.

```
[2021-05-21 11:00:56.024] [exthost] [error] TypeError: Cannot read property 'document' of undefined
	at Object.lintCode (/home/ben/.vscode-server/extensions/golang.go-0.25.0/dist/goMain.js:63940:16)
	at /home/ben/.vscode-server/extensions/golang.go-0.25.0/dist/goMain.js:64694:100
	at E._executeContributedCommand (/home/ben/.vscode-server/bin/054a9295330880ed74ceaedda236253b4f39a335/out/vs/server/remoteExtensionHostProcess.js:87:107932)
	at E.$executeContributedCommand (/home/ben/.vscode-server/bin/054a9295330880ed74ceaedda236253b4f39a335/out/vs/server/remoteExtensionHostProcess.js:87:108370)
	at l._doInvokeHandler (/home/ben/.vscode-server/bin/054a9295330880ed74ceaedda236253b4f39a335/out/vs/server/remoteExtensionHostProcess.js:91:12836)
	at l._invokeHandler (/home/ben/.vscode-server/bin/054a9295330880ed74ceaedda236253b4f39a335/out/vs/server/remoteExtensionHostProcess.js:91:12520)
	at l._receiveRequest (/home/ben/.vscode-server/bin/054a9295330880ed74ceaedda236253b4f39a335/out/vs/server/remoteExtensionHostProcess.js:91:11187)
	at l._receiveOneMessage (/home/ben/.vscode-server/bin/054a9295330880ed74ceaedda236253b4f39a335/out/vs/server/remoteExtensionHostProcess.js:91:9973)
	at /home/ben/.vscode-server/bin/054a9295330880ed74ceaedda236253b4f39a335/out/vs/server/remoteExtensionHostProcess.js:91:8074
	at fire (/home/ben/.vscode-server/bin/054a9295330880ed74ceaedda236253b4f39a335/out/vs/server/remoteExtensionHostProcess.js:57:1836)
	at S.fire (/home/ben/.vscode-server/bin/054a9295330880ed74ceaedda236253b4f39a335/out/vs/server/remoteExtensionHostProcess.js:65:15497)
	at /home/ben/.vscode-server/bin/054a9295330880ed74ceaedda236253b4f39a335/out/vs/server/remoteExtensionHostProcess.js:106:29764
	at fire (/home/ben/.vscode-server/bin/054a9295330880ed74ceaedda236253b4f39a335/out/vs/server/remoteExtensionHostProcess.js:57:1836)
	at S.fire (/home/ben/.vscode-server/bin/054a9295330880ed74ceaedda236253b4f39a335/out/vs/server/remoteExtensionHostProcess.js:65:15497)
	at t._receiveMessage (/home/ben/.vscode-server/bin/054a9295330880ed74ceaedda236253b4f39a335/out/vs/server/remoteExtensionHostProcess.js:65:20755)
	at /home/ben/.vscode-server/bin/054a9295330880ed74ceaedda236253b4f39a335/out/vs/server/remoteExtensionHostProcess.js:65:17641
	at fire (/home/ben/.vscode-server/bin/054a9295330880ed74ceaedda236253b4f39a335/out/vs/server/remoteExtensionHostProcess.js:57:1836)
	at acceptChunk (/home/ben/.vscode-server/bin/054a9295330880ed74ceaedda236253b4f39a335/out/vs/server/remoteExtensionHostProcess.js:65:12862)
	at /home/ben/.vscode-server/bin/054a9295330880ed74ceaedda236253b4f39a335/out/vs/server/remoteExtensionHostProcess.js:65:12210
	at fire (/home/ben/.vscode-server/bin/054a9295330880ed74ceaedda236253b4f39a335/out/vs/server/remoteExtensionHostProcess.js:57:1836)
	at /home/ben/.vscode-server/bin/054a9295330880ed74ceaedda236253b4f39a335/out/vs/server/remoteExtensionHostProcess.js:106:19017
	at afterWrite (internal/streams/writable.js:466:5)
	at onwrite (internal/streams/writable.js:446:7)
	at InflateRaw.afterTransform (internal/streams/transform.js:103:3)
	at Zlib.processCallback (zlib.js:586:8) go.lint.workspace
```
