### ISSUE TITLE
gopls: (master) crash hovering over imports 

### ISSUE THREAD

**Issue by OneOfOne** [golang/vscode-go#1526]
Messing around with the `dev.go2go` branch and I got this:

```
[Error - 2:09:18 PM] 2021/05/24 14:09:18 imports fixes: AllImportsFixes: /usr/src/go2/test/run.go:15:1: expected 'STRING', found '<<' (and 1250 more errors)
	file="/usr/src/go2/test/run.go"

panic: runtime error: slice bounds out of range [:-1]

goroutine 289 [running]:
golang.org/x/tools/internal/lsp.(*encoded).importSpec(0xc3d8c0, 0xc00081a060)
	/home/oneofone/code/go/src/golang.org/x/tools/internal/lsp/semantic.go:644 +0x17c
golang.org/x/tools/internal/lsp.(*encoded).inspector(0xc000360fa0, {0xe5c008, 0xc00081a090})
	/home/oneofone/code/go/src/golang.org/x/tools/internal/lsp/semantic.go:337 +0x16d
golang.org/x/tools/internal/lsp.(*encoded).semantics.func1({0xe5c008, 0xc00081a090})
	/home/oneofone/code/go/src/golang.org/x/tools/internal/lsp/semantic.go:128 +0x30
go/ast.inspector.Visit(0xc00038a780, {0xe5c008, 0xc00081a090})
	/usr/src/go/src/go/ast/walk.go:375 +0x31
go/ast.Walk({0xe4bca0, 0xc00038a780}, {0xe5c008, 0xc00081a090})
	/usr/src/go/src/go/ast/walk.go:50 +0x5f
go/ast.Walk({0xe4bca0, 0xc00038a780}, {0xe5bf40, 0xc00013f700})
	/usr/src/go/src/go/ast/walk.go:333 +0x1e49
```

**Comment by OneOfOne** [comment]
https://go-review.googlesource.com/c/tools/+/322291
