### ISSUE TITLE
debug: 'delve config in settings.json is added to debug config' fails

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#1566]
From https://source.cloud.google.com/results/invocations/9b152ba1-41b5-4a72-8a36-af608da4132f/targets/golang%2Fvscode-go%2Fgcp_ubuntu%2Fpresubmit/log for https://go-review.googlesource.com/c/vscode-go/+/327297

```
  1 failing
  1) Debug Configuration Merge User Settings
       merge 'go' config from settings.json
         delve config in settings.json is added to debug config:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 'legacy'
- 'dlv-dap'
      + expected - actual

      -legacy
      +dlv-dap
      
  	at /workspace/out/test/integration/goDebugConfiguration.test.js:202:20
  	at Generator.next (<anonymous>)
  	at fulfilled (out/test/integration/goDebugConfiguration.test.js:5:58)
```

This is a bug in the test - the extension uses `inspect` to check whether the debugAdapter
setting is set by users or not to choose the right default. The test injects a fake configuration
object that doesn't stub `inspect`, so the test fails. Workspace configuration's inspect is
readonly and can't be stubbed. We can consider to utilize [MockCfg](https://github.com/golang/vscode-go/blob/b70f3c00e82407ee70a8c1eeac2d6ceb0ffd9d29/test/integration/config.test.ts#L73), but
it can be a non-trivial change in the test code.

Since this is a release blocker, I propose to skip this test for now, manually check
the expected behavior with the release candidate, and fix the test later. What do you think @suzmue ?

**Comment by hyangah** [comment]
cl/327769 implements it. 
From https://go-review.googlesource.com/c/vscode-go/+/327772, I verified this works in the release branch too.
