### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by ashutshkumr** [golang/vscode-go#1741]
gopls version: v0.7.1
gopls flags: 
update flags: proxy
extension version: 0.27.1
go version: 1.17
environment: Visual Studio Code linux
initialization error: undefined
manual restart count: 0
total start count: 1

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

gopls stopped working all of a sudden and crash window opened up.

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

```
Error: Connection got disposed.
	at Object.dispose (/root/.vscode-server/extensions/golang.go-0.27.1/dist/goMain.js:78941:27)
	at Object.dispose (/root/.vscode-server/extensions/golang.go-0.27.1/dist/goMain.js:81092:35)
	at LanguageClient.handleConnectionClosed (/root/.vscode-server/extensions/golang.go-0.27.1/dist/goMain.js:83443:42)
	at LanguageClient.handleConnectionClosed (/root/.vscode-server/extensions/golang.go-0.27.1/dist/goMain.js:87235:15)
	at closeHandler (/root/.vscode-server/extensions/golang.go-0.27.1/dist/goMain.js:83430:18)
	at CallbackList.invoke (/root/.vscode-server/extensions/golang.go-0.27.1/dist/goMain.js:79071:39)
	at Emitter.fire (/root/.vscode-server/extensions/golang.go-0.27.1/dist/goMain.js:79133:36)
	at closeHandler (/root/.vscode-server/extensions/golang.go-0.27.1/dist/goMain.js:78153:26)
	at CallbackList.invoke (/root/.vscode-server/extensions/golang.go-0.27.1/dist/goMain.js:79071:39)
	at Emitter.fire (/root/.vscode-server/extensions/golang.go-0.27.1/dist/goMain.js:79133:36)
	at StreamMessageWriter.fireClose (/root/.vscode-server/extensions/golang.go-0.27.1/dist/goMain.js:80007:27)
	at Socket.<anonymous> (/root/.vscode-server/extensions/golang.go-0.27.1/dist/goMain.js:80040:42)
	at Socket.emit (events.js:315:20)
	at Pipe.<anonymous> (net.js:673:12)
[Error - 11:26:30 AM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (/root/.vscode-server/extensions/golang.go-0.27.1/dist/goMain.js:78941:27)
	at Object.dispose (/root/.vscode-server/extensions/golang.go-0.27.1/dist/goMain.js:81092:35)
	at LanguageClient.handleConnectionClosed (/root/.vscode-server/extensions/golang.go-0.27.1/dist/goMain.js:83443:42)
	at LanguageClient.handleConnectionClosed (/root/.vscode-server/extensions/golang.go-0.27.1/dist/goMain.js:87235:15)
	at closeHandler (/root/.vscode-server/extensions/golang.go-0.27.1/dist/goMain.js:83430:18)
	at CallbackList.invoke (/root/.vscode-server/extensions/golang.go-0.27.1/dist/goMain.js:79071:39)
	at Emitter.fire (/root/.vscode-server/extensions/golang.go-0.27.1/dist/goMain.js:79133:36)
	at closeHandler (/root/.vscode-server/extensions/golang.go-0.27.1/dist/goMain.js:78153:26)
	at CallbackList.invoke (/root/.vscode-server/extensions/golang.go-0.27.1/dist/goMain.js:79071:39)
	at Emitter.fire (/root/.vscode-server/extensions/golang.go-0.27.1/dist/goMain.js:79133:36)
	at StreamMessageWriter.fireClose (/root/.vscode-server/extensions/golang.go-0.27.1/dist/goMain.js:80007:27)
	at Socket.<anonymous> (/root/.vscode-server/extensions/golang.go-0.27.1/dist/goMain.js:80040:42)
	at Socket.emit (events.js:315:20)
	at Pipe.<anonymous> (net.js:673:12)
```

Failed to auto-collect gopls trace: unrecognized crash pattern.

**Comment by findleyr** [comment]
Hi, thanks for the report.

Unfortunately I think that stack is just the generic client-side connection failure.  If this happens again, you can try grabbing gopls output from View -> Output -> Tasks -> gopls (server)).

Closing as this isn't actionable right now. If you're able to get more information, please reopen.
