### ISSUE TITLE
debug: flaky legacy test failure

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#1777]
https://github.com/golang/vscode-go/runs/3613491562?check_suite_focus=true

```
disconnect

Sending initializing request for remote attach setup.

Unable to log remote console arguments Output omitted for a large object that exceeds the limits

Sending configuration done request for remote attach setup.

      ✓ disconnect should work for remote attach (12359ms)

      ✓ should disconnect while continuing on entry (907ms)

      1) should disconnect with multiple disconnectRequests

should disconnect with multiple disconnectRequests FAILED: Debug Adapter Trace

2021-9-15, 18:19:36.413 UTC

[18:19:36.413 UTC] From client: initialize({"adapterID":"go","linesStartAt1":true,"columnsStartAt1":true,"pathFormat":"path"})

[18:19:36.413 UTC] InitializeRequest

[18:19:36.413 UTC] To client: {"seq":0,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"supportsConditionalBreakpoints":true,"supportsConfigurationDoneRequest":true,"supportsSetVariable":true}}

[18:19:36.413 UTC] InitializeResponse

Unable to log remote console arguments Output omitted for a large object that exceeds the limits

[18:19:36.414 UTC] LaunchRequest

[18:19:36.420 UTC] Using GOPATH: /home/runner/go

[18:19:36.420 UTC] Using GOROOT: /opt/hostedtoolcache/go/1.16.8/x64

[18:19:36.420 UTC] Using PATH: /opt/hostedtoolcache/go/1.16.8/x64/bin:/opt/hostedtoolcache/node/14.17.6/x64/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/runner/work/vscode-go/vscode-go/node_modules/.bin:/home/runner/go/bin:/opt/hostedtoolcache/node/14.17.6/x64/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/runner/.local/bin:/opt/pipx_bin:/usr/share/rust/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

[18:19:36.420 UTC] Current working directory: /home/runner/work/vscode-go/vscode-go/test/testdata/loop

[18:19:36.420 UTC] Running: /home/runner/go/bin/dlv debug --headless=true --listen=127.0.0.1:37148 --api-version=2 --log=true --log-output=rpc,debugger --output=/home/runner/work/vscode-go/vscode-go/test/testdata/loop/__debug_bin_39

[18:19:36.612 UTC] To client: {"seq":0,"type":"event","event":"output","body":{"category":"stdout","output":"API server listening at: 127.0.0.1:37148\n"}}

[18:19:36.613 UTC] To client: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"2021-09-15T18:19:36Z debug layer=rpc API server pid = 13166\n2021-09-15T18:19:36Z info layer=debugger launching process with args: [/home/runner/work/vscode-go/vscode-go/test/testdata/loop/__debug_bin_39]\n"}}

[18:19:36.817 UTC] To client: {"seq":0,"type":"event","event":"initialized"}

[18:19:36.818 UTC] InitializeEvent

[18:19:36.818 UTC] To client: {"seq":0,"type":"response","request_seq":2,"command":"launch","success":true}

[18:19:36.820 UTC] From client: configurationDone(undefined)

[18:19:36.820 UTC] ConfigurationDoneRequest

[18:19:36.874 UTC] To client: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"2021-09-15T18:19:36Z debug layer=rpc <- RPCServer.GetVersion(api.GetVersionIn{})\n2021-09-15T18:19:36Z debug layer=rpc -> *api.GetVersionOut{\"DelveVersion\":\"Version: 1.7.1\\nBuild: $Id: 3bde2354aafb5a4043fd59838842c4cd4a8b6f0b $\",\"APIVersion\":2,\"Backend\":\"native\",\"TargetGoVersion\":\"Go cmd/compile go1.16.8\",\"MinSupportedVersionOfGo\":\"1.15.0\",\"MaxSupportedVersionOfGo\":\"1.17.0\"} error: \"\"\n"}}

[18:19:36.875 UTC] To client: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"2021-09-15T18:19:36Z debug layer=rpc (async 2) <- RPCServer.State(rpc2.StateIn{\"NonBlocking\":true})\n"}}

[18:19:36.878 UTC] To client: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"2021-09-15T18:19:36Z debug layer=rpc (async 2) -> rpc2.StateOut{\"State\":{\"Pid\":0,\"Running\":false,\"Recording\":false,\"CoreDumping\":false,\"currentThread\":{\"id\":13213,\"pc\":4620256,\"file\":\"/opt/hostedtoolcache/go/1.16.8/x64/src/runtime/rt0_linux_amd64.s\",\"line\":8,\"function\":{\"name\":\"_rt0_amd64_linux\",\"value\":4620256,\"type\":0,\"goType\":0,\"optimized\":true},\"goroutineID\":0,\"ReturnValues\":null,\"CallReturn\":false},\"Threads\":[{\"id\":13213,\"pc\":4620256,\"file\":\"/opt/hostedtoolcache/go/1.16.8/x64/src/runtime/rt0_linux_amd64.s\",\"line\":8,\"function\":{\"name\":\"_rt0_amd64_linux\",\"value\":4620256,\"type\":0,\"goType\":0,\"optimized\":true},\"goroutineID\":0,\"ReturnValues\":null,\"CallReturn\":false}],\"NextInProgress\":false,\"WatchOutOfScope\":[],\"exited\":false,\"exitStatus\":0,\"When\":\"\"}} error: \"\"\n"}}

[18:19:36.879 UTC] Changing DebugState from Halted to Running

[18:19:36.879 UTC] To client: {"seq":0,"type":"response","request_seq":3,"command":"configurationDone","success":true}

[18:19:36.879 UTC] ConfigurationDoneResponse {"seq":35,"type":"response","request_seq":3,"command":"configurationDone","success":true}

[18:19:36.879 UTC] From client: disconnect({"restart":false})

[18:19:36.880 UTC] DisconnectRequest

[18:19:36.880 UTC] Closing Delve.

[18:19:36.880 UTC] HaltRequest

[18:19:36.880 UTC] From client: disconnect({"restart":false})

[18:19:36.880 UTC] DisconnectRequest

[18:19:36.880 UTC] Skip disconnectRequestHelper as Delve's connection is already closed.

[18:19:36.880 UTC] DisconnectRequest to parent to shut down protocol server.

[18:19:36.881 UTC] To client: {"seq":0,"type":"response","request_seq":5,"command":"disconnect","success":true}

[18:19:36.881 UTC] DisconnectResponse

[18:19:36.881 UTC] To client: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"2021-09-15T18:19:36Z debug layer=rpc (async 3) <- RPCServer.Command(api.DebuggerCommand{\"name\":\"continue\",\"ReturnInfoLoadConfig\":null})\n"}}

[18:19:36.881 UTC] To client: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"2021-09-15T18:19:36Z debug layer=debugger continuing\n"}}

[18:19:36.883 UTC] To client: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"2021-09-15T18:19:36Z debug layer=rpc (async 4) <- RPCServer.Command(api.DebuggerCommand{\"name\":\"halt\",\"ReturnInfoLoadConfig\":null})\n2021-09-15T18:19:36Z debug layer=debugger halting\n"}}

[18:19:36.899 UTC] To client: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"2021-09-15T18:19:36Z debug layer=rpc (async 3) -> rpc2.CommandOut{\"State\":{\"Pid\":0,\"Running\":false,\"Recording\":false,\"CoreDumping\":false,\"currentThread\":{\"id\":13213,\"pc\":4534196,\"file\":\"/opt/hostedtoolcache/go/1.16.8/x64/src/runtime/symtab.go\",\"line\":979,\"function\":{\"name\":\"runtime.step\",\"value\":4534144,\"type\":0,\"goType\":0,\"optimized\":true},\"goroutineID\":1,\"ReturnValues\":null,\"CallReturn\":false},\"currentGoroutine\":{\"id\":1,\"currentLoc\":{\"pc\":4534196,\"file\":\"/opt/hostedtoolcache/go/1.16.8/x64/src/runtime/symtab.go\",\"line\":979,\"function\":{\"name\":\"runtime.step\",\"value\":4534144,\"type\":0,\"goType\":0,\"optimized\":true}},\"userCurrentLoc\":{\"pc\":4534196,\"file\":\"/opt/hostedtoolcache/go/1.16.8/x64/src/runtime/symtab.go\",\"line\":979,\"function\":{\"name\":\"runtime.step\",\"value\":4534144,\"type\":0,\"goType\":0,\"optimized\":true}},\"goStatementLoc\":{\"pc\":4606868,\"file\":\"/opt/hostedtoolcache/go/1.16.8/x64/src/runtime/asm_amd64.s\",\"line\":226,\"function\":{\"name\":\"runtime.rt0_go\",\"value\":4606560,\"type\":0,\"goType\":0,\"optimized\":true}},\"startLoc\":{\"pc\":4419680,\"file\":\"/opt/hostedtoolcache/go/1.16.8/x64/src/runtime/proc.go\",\"line\":115,\"function\":{\"name\":\"runtime.main\",\"value\":4419680,\"type\":0,\"goType\":0,\"optimized\":true}},\"threadID\":13213,\"status\":2,\"waitSince\":0,\"waitReason\":0,\"unreadable\":\"\"},\"Threads\":[{\"id\":13213,\"pc\":4534196,\"file\":\"/opt/hostedtoolcache/go/1.16.8/x64/src/runtime/symtab.go\",\"line\":979,\"function\":{\"name\":\"runtime.step\",\"value\":4534144,\"type\":0,\"goType\":0,\"optimized\":true},\"goroutineID\":1,\"ReturnValues\":null,\"CallReturn\":false},{\"id\":13216,\"pc\":4622386,\"file\":\"/opt/hostedtoolcache/go/1.16.8/x64/src/runtime/sys_linux_amd64.s\",\"line\":612,\"function\":{\"name\":\"runtime.clone\",\"value\":4622304,\"type\":0,\"goType\":0,\"optimized\":true},\"goroutineID\":0,\"ReturnValues\":null,\"CallReturn\":false}],\"NextInProgress\":false,\"WatchOutOfScope\":[],\"exited\":false,\"exitStatus\":0,\"When\":\"\"}} error: \"\"\n"}}

[18:19:36.906 UTC] To client: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"2021-09-15T18:19:36Z debug layer=rpc (async 4) -> rpc2.CommandOut{\"State\":{\"Pid\":0,\"Running\":false,\"Recording\":false,\"CoreDumping\":false,\"currentThread\":{\"id\":13213,\"pc\":4534196,\"file\":\"/opt/hostedtoolcache/go/1.16.8/x64/src/runtime/symtab.go\",\"line\":979,\"function\":{\"name\":\"runtime.step\",\"value\":4534144,\"type\":0,\"goType\":0,\"optimized\":true},\"goroutineID\":1,\"ReturnValues\":null,\"CallReturn\":false},\"currentGoroutine\":{\"id\":1,\"currentLoc\":{\"pc\":4534196,\"file\":\"/opt/hostedtoolcache/go/1.16.8/x64/src/runtime/symtab.go\",\"line\":979,\"function\":{\"name\":\"runtime.step\",\"value\":4534144,\"type\":0,\"goType\":0,\"optimized\":true}},\"userCurrentLoc\":{\"pc\":4534196,\"file\":\"/opt/hostedtoolcache/go/1.16.8/x64/src/runtime/symtab.go\",\"line\":979,\"function\":{\"name\":\"runtime.step\",\"value\":4534144,\"type\":0,\"goType\":0,\"optimized\":true}},\"goStatementLoc\":{\"pc\":4606868,\"file\":\"/opt/hostedtoolcache/go/1.16.8/x64/src/runtime/asm_amd64.s\",\"line\":226,\"function\":{\"name\":\"runtime.rt0_go\",\"value\":4606560,\"type\":0,\"goType\":0,\"optimized\":true}},\"startLoc\":{\"pc\":4419680,\"file\":\"/opt/hostedtoolcache/go/1.16.8/x64/src/runtime/proc.go\",\"line\":115,\"function\":{\"name\":\"runtime.main\",\"value\":4419680,\"type\":0,\"goType\":0,\"optimized\":true}},\"threadID\":13213,\"status\":2,\"waitSince\":0,\"waitReason\":0,\"unreadable\":\"\"},\"Threads\":[{\"id\":13213,\"pc\":4534196,\"file\":\"/opt/hostedtoolcache/go/1.16.8/x64/src/runtime/symtab.go\",\"line\":979,\"function\":{\"name\":\"runtime.step\",\"value\":4534144,\"type\":0,\"goType\":0,\"optimized\":true},\"goroutineID\":1,\"ReturnValues\":null,\"CallReturn\":false},{\"id\":13216,\"pc\":4622386,\"file\":\"/opt/hostedtoolcache/go/1.16.8/x64/src/runtime/sys_linux_amd64.s\",\"line\":612,\"function\":{\"name\":\"runtime.clone\",\"value\":4622304,\"type\":0,\"goType\":0,\"optimized\":true},\"goroutineID\":0,\"ReturnValues\":null,\"CallReturn\":false}],\"NextInProgress\":false,\"WatchOutOfScope\":[],\"exited\":false,\"exitStatus\":0,\"When\":\"\"}} error: \"\"\n"}}

[18:19:36.908 UTC] continue state {"Pid":0,"Running":false,"Recording":false,"CoreDumping":false,"currentThread":{"id":13213,"pc":4534196,"file":"/opt/hostedtoolcache/go/1.16.8/x64/src/runtime/symtab.go","line":979,"function":{"name":"runtime.step","value":4534144,"type":0,"goType":0,"optimized":true},"goroutineID":1,"ReturnValues":null,"CallReturn":false},"currentGoroutine":{"id":1,"currentLoc":{"pc":4534196,"file":"/opt/hostedtoolcache/go/1.16.8/x64/src/runtime/symtab.go","line":979,"function":{"name":"runtime.step","value":4534144,"type":0,"goType":0,"optimized":true}},"userCurrentLoc":{"pc":4534196,"file":"/opt/hostedtoolcache/go/1.16.8/x64/src/runtime/symtab.go","line":979,"function":{"name":"runtime.step","value":4534144,"type":0,"goType":0,"optimized":true}},"goStatementLoc":{"pc":4606868,"file":"/opt/hostedtoolcache/go/1.16.8/x64/src/runtime/asm_amd64.s","line":226,"function":{"name":"runtime.rt0_go","value":4606560,"type":0,"goType":0,"optimized":true}},"startLoc":{"pc":4419680,"file":"/opt/hostedtoolcache/go/1.16.8/x64/src/runtime/proc.go","line":115,"function":{"name":"runtime.main","value":4419680,"type":0,"goType":0,"optimized":true}},"threadID":13213,"status":2,"waitSince":0,"waitReason":0,"unreadable":""},"Threads":[{"id":13213,"pc":4534196,"file":"/opt/hostedtoolcache/go/1.16.8/x64/src/runtime/symtab.go","line":979,"function":{"name":"runtime.step","value":4534144,"type":0,"goType":0,"optimized":true},"goroutineID":1,"ReturnValues":null,"CallReturn":false},{"id":13216,"pc":4622386,"file":"/opt/hostedtoolcache/go/1.16.8/x64/src/runtime/sys_linux_amd64.s","line":612,"function":{"name":"runtime.clone","value":4622304,"type":0,"goType":0,"optimized":true},"goroutineID":0,"ReturnValues":null,"CallReturn":false}],"NextInProgress":false,"WatchOutOfScope":[],"exited":false,"exitStatus":0,"When":""}

[18:19:36.908 UTC] handleReenterDebug(breakpoint).

[18:19:36.908 UTC] DetachRequest

[18:19:36.914 UTC] To client: {"seq":0,"type":"event","event":"output","body":{"category":"stderr","output":"2021-09-15T18:19:36Z debug layer=rpc <- RPCServer.ListGoroutines(rpc2.ListGoroutinesIn{\"Start\":0,\"Count\":1,\"Filters\":null,\"GroupBy\":0,\"GroupByKey\":\"\",\"MaxGroupMembers\":0,\"MaxGroups\":0})\n2021-09-15T18:19:36Z debug layer=rpc -> *rpc2.ListGoroutinesOut{\"Goroutines\":[{\"id\":1,\"currentLoc\":{\"pc\":4534196,\"file\":\"/opt/hostedtoolcache/go/1.16.8/x64/src/runtime/symtab.go\",\"line\":979,\"function\":{\"name\":\"runtime.step\",\"value\":4534144,\"type\":0,\"goType\":0,\"optimized\":true}},\"userCurrentLoc\":{\"pc\":4534196,\"file\":\"/opt/hostedtoolcache/go/1.16.8/x64/src/runtime/symtab.go\",\"line\":979,\"function\":{\"name\":\"runtime.step\",\"value\":4534144,\"type\":0,\"goType\":0,\"optimized\":true}},\"goStatementLoc\":{\"pc\":4606868,\"file\":\"/opt/hostedtoolcache/go/1.16.8/x64/src/runtime/asm_amd64.s\",\"line\":226,\"function\":{\"name\":\"runtime.rt0_go\",\"value\":4606560,\"type\":0,\"goType\":0,\"optimized\":true}},\"startLoc\":{\"pc\":4419680,\"file\":\"/opt/hostedtoolcache/go/1.16.8/x64/src/runtime/proc.go\",\"line\":115,\"function\":{\"name\":\"runtime.main\",\"value\":4419680,\"type\":0,\"goType\":0,\"optimized\":true}},\"threadID\":13213,\"status\":2,\"waitSince\":0,\"waitReason\":0,\"unreadable\":\"\"}],\"Nextg\":-1,\"Groups\":null,\"TooManyGroups\":false} error: \"\"\n2021-09-15T18:19:36Z debug layer=rpc <- RPCServer.Detach(rpc2.DetachIn{\"Kill\":true})\n2021-09-15T18:19:36Z debug layer=debugger detaching\n"}}

[18:19:36.915 UTC] To client: {"seq":0,"type":"event","event":"stopped","body":{"reason":"breakpoint","threadId":1,"allThreadsStopped":true}}

[18:19:36.915 UTC] StoppedEvent("breakpoint")

      ✓ should disconnect after continue (774ms)
...


  1 failing

  1) Go Debug Adapter Tests (legacy)
       disconnect
         should disconnect with multiple disconnectRequests:
     Error: no event 'terminated' received after 20000 ms
  	at Timeout._onTimeout (node_modules/vscode-debugadapter-testsupport/lib/debugClient.js:233:28)
  	at listOnTimeout (internal/timers.js:554:17)
  	at processTimers (internal/timers.js:497:7)

```

**Comment by hyangah** [comment]
Duplicate of #1995
