### ISSUE TITLE
testExplorer: fix tests

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#1788]
Following tests are still failing with `workspace.fs.dirs.get is not a function or its return value is not iterable` errors on windows 
at 171cc61

<details>>
```
   12) Go Test Explorer
       Document opened
         In workspace:
     TypeError: workspace.fs.dirs.get is not a function or its return value is not iterable
  	at walk (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:34:54)
  	at walk (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:45:13)
  	at Object.populateModulePathCache (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:52:5)
  	at newExplorer (d:\a\vscode-go\vscode-go\out\test\integration\goTest.explore.test.js:32:20)
  	at d:\a\vscode-go\vscode-go\out\test\integration\goTest.explore.test.js:96:44
  	at Generator.next (<anonymous>)
  	at d:\a\vscode-go\vscode-go\out\test\integration\goTest.explore.test.js:8:71
  	at new Promise (<anonymous>)
  	at __awaiter (d:\a\vscode-go\vscode-go\out\test\integration\goTest.explore.test.js:4:12)
  	at Context.<anonymous> (d:\a\vscode-go\vscode-go\out\test\integration\goTest.explore.test.js:94:30)
  	at processImmediate (internal/timers.js:461:21)

  13) Go Test Explorer
       Document opened
         Outside workspace:
     TypeError: workspace.fs.dirs.get is not a function or its return value is not iterable
  	at walk (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:34:54)
  	at walk (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:45:13)
  	at Object.populateModulePathCache (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:52:5)
  	at newExplorer (d:\a\vscode-go\vscode-go\out\test\integration\goTest.explore.test.js:32:20)
  	at d:\a\vscode-go\vscode-go\out\test\integration\goTest.explore.test.js:96:44
  	at Generator.next (<anonymous>)
  	at d:\a\vscode-go\vscode-go\out\test\integration\goTest.explore.test.js:8:71
  	at new Promise (<anonymous>)
  	at __awaiter (d:\a\vscode-go\vscode-go\out\test\integration\goTest.explore.test.js:4:12)
  	at Context.<anonymous> (d:\a\vscode-go\vscode-go\out\test\integration\goTest.explore.test.js:94:30)
  	at processImmediate (internal/timers.js:461:21)

  14) Go Test Explorer
       Document edited
         Add test:
     TypeError: workspace.fs.dirs.get is not a function or its return value is not iterable
  	at walk (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:34:54)
  	at walk (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:45:13)
  	at Object.populateModulePathCache (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:52:5)
  	at newExplorer (d:\a\vscode-go\vscode-go\out\test\integration\goTest.explore.test.js:32:20)
  	at d:\a\vscode-go\vscode-go\out\test\integration\goTest.explore.test.js:154:44
  	at Generator.next (<anonymous>)
  	at d:\a\vscode-go\vscode-go\out\test\integration\goTest.explore.test.js:8:71
  	at new Promise (<anonymous>)
  	at __awaiter (d:\a\vscode-go\vscode-go\out\test\integration\goTest.explore.test.js:4:12)
  	at Context.<anonymous> (d:\a\vscode-go\vscode-go\out\test\integration\goTest.explore.test.js:152:30)
  	at processImmediate (internal/timers.js:461:21)

  15) Go Test Explorer
       Document edited
         Remove test:
     TypeError: workspace.fs.dirs.get is not a function or its return value is not iterable
  	at walk (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:34:54)
  	at walk (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:45:13)
  	at Object.populateModulePathCache (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:52:5)
  	at newExplorer (d:\a\vscode-go\vscode-go\out\test\integration\goTest.explore.test.js:32:20)
  	at d:\a\vscode-go\vscode-go\out\test\integration\goTest.explore.test.js:154:44
  	at Generator.next (<anonymous>)
  	at d:\a\vscode-go\vscode-go\out\test\integration\goTest.explore.test.js:8:71
  	at new Promise (<anonymous>)
  	at __awaiter (d:\a\vscode-go\vscode-go\out\test\integration\goTest.explore.test.js:4:12)
  	at Context.<anonymous> (d:\a\vscode-go\vscode-go\out\test\integration\goTest.explore.test.js:152:30)
  	at processImmediate (internal/timers.js:461:21)

  16) Go Test Explorer
       settings
         packageDisplayMode
           "before each" hook for "flat":
     TypeError: workspace.fs.dirs.get is not a function or its return value is not iterable
  	at walk (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:34:54)
  	at walk (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:45:13)
  	at Object.populateModulePathCache (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:52:5)
  	at newExplorer (d:\a\vscode-go\vscode-go\out\test\integration\goTest.explore.test.js:32:20)
  	at Context.<anonymous> (d:\a\vscode-go\vscode-go\out\test\integration\goTest.explore.test.js:205:34)
  	at processImmediate (internal/timers.js:461:21)

  17) Go Test Explorer
       settings
         alwaysRunBenchmarks
           "before each" hook for "false":
     TypeError: workspace.fs.dirs.get is not a function or its return value is not iterable
  	at walk (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:34:54)
  	at walk (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:45:13)
  	at Object.populateModulePathCache (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:52:5)
  	at newExplorer (d:\a\vscode-go\vscode-go\out\test\integration\goTest.explore.test.js:32:20)
  	at Context.<anonymous> (d:\a\vscode-go\vscode-go\out\test\integration\goTest.explore.test.js:252:28)
  	at processImmediate (internal/timers.js:461:21)

  18) Go Test Explorer
       settings
         showDynamicSubtestsInEditor
           "before each" hook for "false":
     TypeError: workspace.fs.dirs.get is not a function or its return value is not iterable
  	at walk (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:34:54)
  	at walk (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:45:13)
  	at Object.populateModulePathCache (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:52:5)
  	at newExplorer (d:\a\vscode-go\vscode-go\out\test\integration\goTest.explore.test.js:32:20)
  	at Context.<anonymous> (d:\a\vscode-go\vscode-go\out\test\integration\goTest.explore.test.js:297:28)
  	at processImmediate (internal/timers.js:461:21)

  19) Go Test Resolver
       Root
         Basic module:
     TypeError: workspace.fs.dirs.get is not a function or its return value is not iterable
  	at walk (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:34:54)
  	at walk (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:45:13)
  	at Object.populateModulePathCache (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:52:5)
  	at setup (d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:26:20)
  	at d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:191:48
  	at Generator.next (<anonymous>)
  	at d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:8:71
  	at new Promise (<anonymous>)
  	at __awaiter (d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:4:12)
  	at Context.<anonymous> (d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:189:31)
  	at processImmediate (internal/timers.js:461:21)

  20) Go Test Resolver
       Root
         Basic workspace:
     TypeError: workspace.fs.dirs.get is not a function or its return value is not iterable
  	at walk (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:34:54)
  	at walk (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:45:13)
  	at Object.populateModulePathCache (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:52:5)
  	at setup (d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:26:20)
  	at d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:191:48
  	at Generator.next (<anonymous>)
  	at d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:8:71
  	at new Promise (<anonymous>)
  	at __awaiter (d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:4:12)
  	at Context.<anonymous> (d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:189:31)
  	at processImmediate (internal/timers.js:461:21)

  21) Go Test Resolver
       Root
         Module and workspace:
     TypeError: workspace.fs.dirs.get is not a function or its return value is not iterable
  	at walk (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:34:54)
  	at walk (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:45:13)
  	at Object.populateModulePathCache (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:52:5)
  	at setup (d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:26:20)
  	at d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:191:48
  	at Generator.next (<anonymous>)
  	at d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:8:71
  	at new Promise (<anonymous>)
  	at __awaiter (d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:4:12)
  	at Context.<anonymous> (d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:189:31)
  	at processImmediate (internal/timers.js:461:21)

  22) Go Test Resolver
       Root
         Module in workspace:
     TypeError: workspace.fs.dirs.get is not a function or its return value is not iterable
  	at walk (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:34:54)
  	at walk (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:45:13)
  	at Object.populateModulePathCache (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:52:5)
  	at setup (d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:26:20)
  	at d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:191:48
  	at Generator.next (<anonymous>)
  	at d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:8:71
  	at new Promise (<anonymous>)
  	at __awaiter (d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:4:12)
  	at Context.<anonymous> (d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:189:31)
  	at processImmediate (internal/timers.js:461:21)

  23) Go Test Resolver
       Module
         Empty:
     TypeError: workspace.fs.dirs.get is not a function or its return value is not iterable
  	at walk (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:34:54)
  	at walk (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:45:13)
  	at Object.populateModulePathCache (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:52:5)
  	at setup (d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:26:20)
  	at d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:191:48
  	at Generator.next (<anonymous>)
  	at d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:8:71
  	at new Promise (<anonymous>)
  	at __awaiter (d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:4:12)
  	at Context.<anonymous> (d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:189:31)
  	at processImmediate (internal/timers.js:461:21)

  24) Go Test Resolver
       Module
         Root package:
     TypeError: workspace.fs.dirs.get is not a function or its return value is not iterable
  	at walk (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:34:54)
  	at walk (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:45:13)
  	at Object.populateModulePathCache (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:52:5)
  	at setup (d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:26:20)
  	at d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:191:48
  	at Generator.next (<anonymous>)
  	at d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:8:71
  	at new Promise (<anonymous>)
  	at __awaiter (d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:4:12)
  	at Context.<anonymous> (d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:189:31)
  	at processImmediate (internal/timers.js:461:21)

  25) Go Test Resolver
       Module
         Sub packages:
     TypeError: workspace.fs.dirs.get is not a function or its return value is not iterable
  	at walk (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:34:54)
  	at walk (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:45:13)
  	at Object.populateModulePathCache (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:52:5)
  	at setup (d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:26:20)
  	at d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:191:48
  	at Generator.next (<anonymous>)
  	at d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:8:71
  	at new Promise (<anonymous>)
  	at __awaiter (d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:4:12)
  	at Context.<anonymous> (d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:189:31)
  	at processImmediate (internal/timers.js:461:21)

  26) Go Test Resolver
       Module
         Nested packages:
     TypeError: workspace.fs.dirs.get is not a function or its return value is not iterable
  	at walk (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:34:54)
  	at walk (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:45:13)
  	at Object.populateModulePathCache (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:52:5)
  	at setup (d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:26:20)
  	at d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:191:48
  	at Generator.next (<anonymous>)
  	at d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:8:71
  	at new Promise (<anonymous>)
  	at __awaiter (d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:4:12)
  	at Context.<anonymous> (d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:189:31)
  	at processImmediate (internal/timers.js:461:21)

  27) Go Test Resolver
       Package
         Empty:
     TypeError: workspace.fs.dirs.get is not a function or its return value is not iterable
  	at walk (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:34:54)
  	at walk (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:45:13)
  	at Object.populateModulePathCache (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:52:5)
  	at setup (d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:26:20)
  	at d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:191:48
  	at Generator.next (<anonymous>)
  	at d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:8:71
  	at new Promise (<anonymous>)
  	at __awaiter (d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:4:12)
  	at Context.<anonymous> (d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:189:31)
  	at processImmediate (internal/timers.js:461:21)

  28) Go Test Resolver
       Package
         Flat:
     TypeError: workspace.fs.dirs.get is not a function or its return value is not iterable
  	at walk (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:34:54)
  	at walk (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:45:13)
  	at Object.populateModulePathCache (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:52:5)
  	at setup (d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:26:20)
  	at d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:191:48
  	at Generator.next (<anonymous>)
  	at d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:8:71
  	at new Promise (<anonymous>)
  	at __awaiter (d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:4:12)
  	at Context.<anonymous> (d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:189:31)
  	at processImmediate (internal/timers.js:461:21)

  29) Go Test Resolver
       Package
         Sub package:
     TypeError: workspace.fs.dirs.get is not a function or its return value is not iterable
  	at walk (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:34:54)
  	at walk (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:45:13)
  	at Object.populateModulePathCache (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:52:5)
  	at setup (d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:26:20)
  	at d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:191:48
  	at Generator.next (<anonymous>)
  	at d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:8:71
  	at new Promise (<anonymous>)
  	at __awaiter (d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:4:12)
  	at Context.<anonymous> (d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:189:31)
  	at processImmediate (internal/timers.js:461:21)

  30) Go Test Resolver
       File
         Empty:
     TypeError: workspace.fs.dirs.get is not a function or its return value is not iterable
  	at walk (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:34:54)
  	at walk (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:45:13)
  	at Object.populateModulePathCache (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:52:5)
  	at setup (d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:26:20)
  	at d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:191:48
  	at Generator.next (<anonymous>)
  	at d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:8:71
  	at new Promise (<anonymous>)
  	at __awaiter (d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:4:12)
  	at Context.<anonymous> (d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:189:31)
  	at processImmediate (internal/timers.js:461:21)

  31) Go Test Resolver
       File
         One of each:
     TypeError: workspace.fs.dirs.get is not a function or its return value is not iterable
  	at walk (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:34:54)
  	at walk (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:45:13)
  	at Object.populateModulePathCache (d:\a\vscode-go\vscode-go\out\test\integration\goTest.utils.js:52:5)
  	at setup (d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:26:20)
  	at d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:191:48
  	at Generator.next (<anonymous>)
  	at d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:8:71
  	at new Promise (<anonymous>)
  	at __awaiter (d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:4:12)
  	at Context.<anonymous> (d:\a\vscode-go\vscode-go\out\test\integration\goTest.resolve.test.js:189:31)
  	at processImmediate (internal/timers.js:461:21)
 ``` 	
 </details>

**Comment by hyangah** [comment]
FIxed and reenabled all tests on windows. Closing
![Screen Shot 2022-07-21 at 5 30 51 PM](https://user-images.githubusercontent.com/4999471/180318658-6ddb505f-015d-4775-82e8-42b58dadde9f.png)
.
