### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by serip88** [golang/vscode-go#1827]
gopls version: v0.7.2
gopls flags: 
update flags: proxy
extension version: 0.28.1
go version: 1.17
environment: Visual Studio Code darwin
initialization error: undefined
issue timestamp: Tue, 05 Oct 2021 07:11:39 GMT
restart history:
Tue, 05 Oct 2021 06:25:20 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11bea20]

goroutine 3790 [running]:
go/types.(*Checker).handleBailout(0xc006cc6dc0, 0xc00112b698)
	  check.go:245  0x8b
panic({0x1852680, 0x1fa1dc0})
	  panic.go:1038  0x215
go/ast.(*Ident).Pos(0xc00112ae28)
	  ast.go:469
go/types.spanOf({0x1a80880, 0x0})
	  errors.go:243  0x134
go/types.(*Checker).newError(0xc006cc6dc0, {0x1a80880, 0x0}, 0x27, 0x0, {0xc00734c100, 0x33})
	  errors.go:154  0x4f
go/types.(*Checker).error(0x18169e0, {0x1a80880, 0x0}, 0x0, {0xc00734c100, 0xb})
	  errors.go:173  0x35
go/types.(*Checker).errorf(0xc006cc6dc0, {0x1a80880, 0x0}, 0xc002dfc611, {0x1970abf, 0xc0005cd607}, {0x0, 0x0, 0x0})
	  errors.go:177  0x68
go/types.(*Checker).collectObjects.func1({0x1a81fa0, 0xc002eb7e90})
	  resolver.go:279  0xbfd
go/types.(*Checker).walkDecl(0x800000000000, {0x1a94c60, 0xc00291e0c0}, 0xc001e7f568)
	  decl.go:431  0x1c7
go/types.(*Checker).walkDecls(0xc0005cd607, {0xc00291e480, 0x3, 0x1}, 0x0)
	  decl.go:418  0x6a
go/types.(*Checker).collectObjects(0xc006cc6dc0)
	  resolver.go:252  0x225
go/types.(*Checker).checkFiles(0xc006cc6dc0, {0xc004c62e18, 0xc0063356d0, 0x2})
	  check.go:263  0xb5
go/types.(*Checker).Files(...)
	  check.go:250
golang.org/x/tools/internal/lsp/cache.doTypeCheck({0x1a97a58, 0xc0051cc7c0}, 0xc0042c0400, 0xc000d032c0, 0x2, 0xc005178ab0, 0x0)
	  check.go:536  0x893
golang.org/x/tools/internal/lsp/cache.typeCheck({0x1a97a58, 0xc0051cc7c0}, 0xc0042c0400, 0xc000d032c0, 0x2, 0xc005178ab0)
	  check.go:313  0xe5
golang.org/x/tools/internal/lsp/cache.(*snapshot).buildPackageHandle.func1({0x1a97a58, 0xc0051cc7c0}, {0x1a80e80, 0xc0042c0400})
	  check.go:124  0x23e
golang.org/x/tools/internal/memoize.(*Handle).run.func1()
	  memoize.go:322  0xa9
created by golang.org/x/tools/internal/memoize.(*Handle).run
	  memoize.go:315  0x1bd
[Error - 2:11:22 PM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by h4midr** [comment]
I have the same issue today

**Comment by h4midr** [comment]
in my case fixed with these steps
- update the Golang to the latest version (1.17.1)
- reinstall the `gopls`
  - `go install golang.org/x/tools/gopls@latest`

**Comment by hyangah** [comment]
Thanks @h4midr 
I cannot find anything immediately related to this crash from the golang/go 1.17.1 milestone. 
@serip88 Can you try to update go to 1.17.1 and rebuild gopls? You are already using the latest gopls, but need to be rebuilt with the new go version if fix exists in 1.17.1 go/types and go/ast packages.

**Comment by findleyr** [comment]
This is a regression in Go 1.17, that was fixed in 1.17.1: https://golang.org/issue/48082.
