### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by zsyaoo** [golang/vscode-go#2007]
gopls version: v0.7.4
gopls flags: 
update flags: proxy
extension version: 0.30.0
go version: 1.17.6
environment: code-server linux
initialization error: undefined
issue timestamp: Tue, 11 Jan 2022 03:17:07 GMT
restart history:
Tue, 11 Jan 2022 02:36:07 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

Failed to auto-collect gopls trace: unrecognized crash pattern.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by zsyaoo** [comment]
[Error - 10:39:25 AM] Connection to server got closed. Server will not be restarted.
[Error - 10:39:25 AM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:4909:25)
	at Object.dispose (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:9694:35)
	at LanguageClient2.handleConnectionClosed (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:11902:38)
	at LanguageClient2.handleConnectionClosed (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:14311:15)
	at closeHandler (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:11890:16)
	at CallbackList.invoke (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:3025:35)
	at Emitter.fire (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:3076:34)
	at closeHandler (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:4171:24)
	at CallbackList.invoke (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:3025:35)
	at Emitter.fire (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:3076:34)
	at StreamMessageWriter.fireClose (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:3477:27)
	at Socket.<anonymous> (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:3508:42)
	at Socket.emit (events.js:400:28)
	at Pipe.<anonymous> (net.js:686:12)
[Error - 10:39:25 AM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:4909:25)
	at Object.dispose (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:9694:35)
	at LanguageClient2.handleConnectionClosed (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:11902:38)
	at LanguageClient2.handleConnectionClosed (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:14311:15)
	at closeHandler (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:11890:16)
	at CallbackList.invoke (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:3025:35)
	at Emitter.fire (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:3076:34)
	at closeHandler (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:4171:24)
	at CallbackList.invoke (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:3025:35)
	at Emitter.fire (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:3076:34)
	at StreamMessageWriter.fireClose (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:3477:27)
	at Socket.<anonymous> (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:3508:42)
	at Socket.emit (events.js:400:28)
	at Pipe.<anonymous> (net.js:686:12)
[Error - 10:39:25 AM] Request textDocument/documentLink failed.
Error: Connection got disposed.
	at Object.dispose (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:4909:25)
	at Object.dispose (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:9694:35)
	at LanguageClient2.handleConnectionClosed (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:11902:38)
	at LanguageClient2.handleConnectionClosed (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:14311:15)
	at closeHandler (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:11890:16)
	at CallbackList.invoke (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:3025:35)
	at Emitter.fire (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:3076:34)
	at closeHandler (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:4171:24)
	at CallbackList.invoke (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:3025:35)
	at Emitter.fire (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:3076:34)
	at StreamMessageWriter.fireClose (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:3477:27)
	at Socket.<anonymous> (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:3508:42)
	at Socket.emit (events.js:400:28)
	at Pipe.<anonymous> (net.js:686:12)
[Error - 10:39:25 AM] Request textDocument/foldingRange failed.
Error: Connection got disposed.
	at Object.dispose (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:4909:25)
	at Object.dispose (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:9694:35)
	at LanguageClient2.handleConnectionClosed (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:11902:38)
	at LanguageClient2.handleConnectionClosed (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:14311:15)
	at closeHandler (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:11890:16)
	at CallbackList.invoke (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:3025:35)
	at Emitter.fire (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:3076:34)
	at closeHandler (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:4171:24)
	at CallbackList.invoke (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:3025:35)
	at Emitter.fire (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:3076:34)
	at StreamMessageWriter.fireClose (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:3477:27)
	at Socket.<anonymous> (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:3508:42)
	at Socket.emit (events.js:400:28)
	at Pipe.<anonymous> (net.js:686:12)
[Error - 10:39:25 AM] Request textDocument/codeLens failed.
Error: Connection got disposed.
	at Object.dispose (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:4909:25)
	at Object.dispose (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:9694:35)
	at LanguageClient2.handleConnectionClosed (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:11902:38)
	at LanguageClient2.handleConnectionClosed (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:14311:15)
	at closeHandler (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:11890:16)
	at CallbackList.invoke (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:3025:35)
	at Emitter.fire (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:3076:34)
	at closeHandler (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:4171:24)
	at CallbackList.invoke (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:3025:35)
	at Emitter.fire (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:3076:34)
	at StreamMessageWriter.fireClose (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:3477:27)
	at Socket.<anonymous> (/root/.local/share/code-server/extensions/golang.go-0.30.0/dist/goMain.js:3508:42)
	at Socket.emit (events.js:400:28)
	at Pipe.<anonymous> (net.js:686:12)

**Comment by suzmue** [comment]
Hi @zsyaoo,  Could you let us know what you were doing when you saw this crash? Thanks!

**Comment by zsyaoo** [comment]
> Hi @zsyaoo, Could you let us know what you were doing when you saw this crash? Thanks!

I use code-server in browser to view kubernetes code,when i  use left click jump method it show the err!

**Comment by suzmue** [comment]
What is the memory limit on your container? It's possible that gopls was using too much memory and was killed so the memory limit should be high for it to work.

**Comment by zsyaoo** [comment]
> 



> What is the memory limit on your container? It's possible that gopls was using too much memory and was killed so the memory limit should be high for it to work.

2 cpu 4G memory

**Comment by findleyr** [comment]
That seems like a likely culprit. It typically takes 3-6GB of memory to work on Kubernetes. This is something that we plan to work on long-term, but for now can you increase the memory limits of your container?

Unfortunately, I don't think there's anything we can do anything to make the failure more clearer here.

**Comment by findleyr** [comment]
Closing this as unactionable. The most straightforward fix for this is reducing gopls' memory usage, which is tracked in many other issues, and something we hope to work on next quarter.
