### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by christopherhui** [golang/vscode-go#2047]
gopls version: v0.7.5
gopls flags: 
update flags: proxy
extension version: 0.31.0
go version: 1.16.7
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Tue, 01 Feb 2022 20:16:47 GMT
restart history:
Tue, 01 Feb 2022 20:15:56 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

Seems like it works for the first minute, then crashes afterwards.

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

Error: Connection got disposed.
	at Object.dispose (/home/g/gkhui/.vscode-server/extensions/golang.go-0.31.0/dist/goMain.js:4909:25)
	at Object.dispose (/home/g/gkhui/.vscode-server/extensions/golang.go-0.31.0/dist/goMain.js:9694:35)
	at LanguageClient2.handleConnectionClosed (/home/g/gkhui/.vscode-server/extensions/golang.go-0.31.0/dist/goMain.js:11902:38)
	at LanguageClient2.handleConnectionClosed (/home/g/gkhui/.vscode-server/extensions/golang.go-0.31.0/dist/goMain.js:14311:15)
	at closeHandler (/home/g/gkhui/.vscode-server/extensions/golang.go-0.31.0/dist/goMain.js:11890:16)
	at CallbackList.invoke (/home/g/gkhui/.vscode-server/extensions/golang.go-0.31.0/dist/goMain.js:3025:35)
	at Emitter.fire (/home/g/gkhui/.vscode-server/extensions/golang.go-0.31.0/dist/goMain.js:3076:34)
	at closeHandler (/home/g/gkhui/.vscode-server/extensions/golang.go-0.31.0/dist/goMain.js:4171:24)
	at CallbackList.invoke (/home/g/gkhui/.vscode-server/extensions/golang.go-0.31.0/dist/goMain.js:3025:35)
	at Emitter.fire (/home/g/gkhui/.vscode-server/extensions/golang.go-0.31.0/dist/goMain.js:3076:34)
	at StreamMessageReader.fireClose (/home/g/gkhui/.vscode-server/extensions/golang.go-0.31.0/dist/goMain.js:3218:27)
	at Socket.<anonymous> (/home/g/gkhui/.vscode-server/extensions/golang.go-0.31.0/dist/goMain.js:3301:42)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)

Failed to auto-collect gopls trace: unrecognized crash pattern.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment]
Hi, thanks for the report. Are you able to attache the crashing stack from gopls? (found by navigating to View -> Output -> Tasks -> gopls (server)).

**Comment by christopherhui** [comment]
I attached it below
[gooutput.log](https://github.com/golang/vscode-go/files/7983535/gooutput.log)

**Comment by hyangah** [comment]
Thank you @christopherhui for sharing the log.
Looks like gopls ran out of memory and crashed.  

```
runtime: out of memory: cannot allocate 4194304-byte block (131039232 in use)
fatal error: out of memory

goroutine 3639 [running]:
runtime.throw(0xe9f96f, 0xd)
	/cs/local/lib/pkg/go-1.16.7/src/runtime/panic.go:1117 +0x72 fp=0xc007de30e8 sp=0xc007de30b8 pc=0x439b12
runtime.(*mcache).refill(0x7ffb6829d5b8, 0x16)
	/cs/local/lib/pkg/go-1.16.7/src/runtime/mcache.go:164 +0x285 fp=0xc007de3130 sp=0xc007de30e8 pc=0x41a165
runtime.(*mcache).nextFree(0x7ffb6829d5b8, 0x16, 0x0, 0xc007de3210, 0x5cb77f)
...
```

`gopls` is known to be relatively memory intensive, but the current usage the runtime reported is not on high side. Are you currently running in a container or a memory-constrained environment? Is it possible to increase the limit?

**Comment by findleyr** [comment]
Closing as this doesn't look actionable (other than the fact that we should reduce gopls' memory footprint, but that is covered by many other issues...)
