### ISSUE TITLE
"Test listPackages" test is flaky

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#2095]
Now the following test occasionally fails.
It can be related to the migration to the `go list` from `gopkgs` (#258) 

https://github.com/golang/vscode-go/runs/5467025890?check_suite_focus=true
<pre>
  1) Go Extension Tests (GOPATH mode)
       Test listPackages:
     Error: Timeout of 20000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/vscode-go/vscode-go/out/test/integration/extension.test.js)
  	at listOnTimeout (internal/timers.js:554:17)
  	at processTimers (internal/timers.js:497:7)

Error: 1 tests failed.
	at /home/runner/work/vscode-go/vscode-go/out/test/integration/index.js:58:27
	at done (/home/runner/work/vscode-go/vscode-go/node_modules/mocha/lib/mocha.js:1068:7)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
[main 2022-03-08T15:59:33.812Z] Waiting for extension host with pid 4559 to exit.
[main 2022-03-08T15:59:33.832Z] Extension host with pid 4559 exited with code: 1, signal: null.
</pre>

**Comment by hyangah** [comment]
@jamalc Even `go list` is slow, not completing within 20s isn't normal. I guess a bug in the test or a race condition.  Do you have time to look into it? (make sure to use a clean `GOPATH` if you investigate it in a local machine)
