### ISSUE TITLE
debug: Debug Configuration tests failing on release branch

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#2215]
This is v0.33.0 release blocker and needs to be fixed.

cc @suzmue @polinasok 

 ```
  3 failing
  1) Debug Configuration Merge User Settings
       merge 'go' config from settings.json
         default settings are applied:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 'legacy'
- 'dlv-dap'
      + expected - actual

      -legacy
      +dlv-dap
      
  	at Context.<anonymous> (out/test/integration/goDebugConfiguration.test.js:183:20)

  2) Debug Configuration Default DebugAdapter
       default debugAdapter should be 'dlv-dap':

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 'legacy'
- 'dlv-dap'
      + expected - actual

      -legacy
      +dlv-dap
      
  	at Context.<anonymous> (out/test/integration/goDebugConfiguration.test.js:731:16)

  3) Debug Configuration Default DebugAdapter
       default debugAdapter for remote mode should be 'legacy' when not in Preview mode:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 'dlv-dap'
- 'legacy'
      + expected - actual

      -dlv-dap
      +legacy
      
  	at Context.<anonymous> (out/test/integration/goDebugConfiguration.test.js:745:16)

Error: 3 tests failed.
	at /workspace/out/test/integration/index.js:58:27
	at done (/workspace/node_modules/mocha/lib/mocha.js:1068:7)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
[main 2022-04-25T22:03:12.498Z] Extension host with pid 356 exited with code: 1, signal: null.
Exit code:   1
Done
```

**Comment by polinasok** [comment]
I looked more into the issue with `extensionInfo` potentially not being initialized in test mode. I can't see it ddirectly in the debugger stopped in a test, but I can see it if I copy things over to a local variable or print to console. It changes when I manually change `preview` manually in `package.json`. 
<img width="1196" alt="image" src="https://user-images.githubusercontent.com/51177946/165233177-bf0b0918-5d86-4667-97aa-2f1314e67097.png">
That said, it might be a better approach to stub it out (the way it is done with getGoConfig) instead of relying no the release vs non-release environment and manually changing `package.json` for testing.
