### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by bigpigeon** [golang/vscode-go#2231]
gopls version: v0.8.3 (go1.18)
gopls flags: 
update flags: proxy
extension version: 0.33.0
go version: 1.18
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Sat, 07 May 2022 07:36:54 GMT
restart history:
Fri, 06 May 2022 06:34:07 GMT: activation (enabled: true)
Fri, 06 May 2022 06:36:06 GMT: config change (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

Rename function name failure, got  “Connection got disposed.” event

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

goroutine 11224 [running]:
golang.org/x/tools/refactor/satisfy.(*Finder).expr(0xc00808b890, {0x10557d8?, 0xc00bb299e0?})
	/home/jia/go/pkg/mod/golang.org/x/tools@v0.1.11-0.20220407163324-91bcfb1bdf9c/refactor/satisfy/find.go:472 +0xccf
golang.org/x/tools/refactor/satisfy.(*Finder).expr(0xc00808b890, {0x1055d48?, 0xc00bb29a10?})
	/home/jia/go/pkg/mod/golang.org/x/tools@v0.1.11-0.20220407163324-91bcfb1bdf9c/refactor/satisfy/find.go:411 +0x793
golang.org/x/tools/refactor/satisfy.(*Finder).expr(0xc00808b890, {0x1055988?, 0xc0102b3980?})
	/home/jia/go/pkg/mod/golang.org/x/tools@v0.1.11-0.20220407163324-91bcfb1bdf9c/refactor/satisfy/find.go:446 +0xd98
golang.org/x/tools/refactor/satisfy.(*Finder).expr(0xc00808b890, {0x1055a48?, 0xc0102b3b00?})
	/home/jia/go/pkg/mod/golang.org/x/tools@v0.1.11-0.20220407163324-91bcfb1bdf9c/refactor/satisfy/find.go:369 +0xfb5
golang.org/x/tools/refactor/satisfy.(*Finder).expr(0xc00808b890, {0x10560d8?, 0xc008bfd2a0?})
	/home/jia/go/pkg/mod/golang.org/x/tools@v0.1.11-0.20220407163324-91bcfb1bdf9c/refactor/satisfy/find.go:453 +0x45a
golang.org/x/tools/refactor/satisfy.(*Finder).call(0xc00808b890, 0xc00905dac0, {0xc00a640050, 0x1, 0x1542fe0?})
	/home/jia/go/pkg/mod/golang.org/x/tools@v0.1.11-0.20220407163324-91bcfb1bdf9c/refactor/satisfy/find.go:183 +0x492
golang.org/x/tools/refactor/satisfy.(*Finder).exprN(0xc00808b890, {0x1055988?, 0xc0102b3b40?})
	/home/jia/go/pkg/mod/golang.org/x/tools@v0.1.11-0.20220407163324-91bcfb1bdf9c/refactor/satisfy/find.go:136 +0x147
golang.org/x/tools/refactor/satisfy.(*Finder).stmt(0xc00808b890, {0x1055808?, 0xc0102b3b80?})
	/home/jia/go/pkg/mod/golang.org/x/tools@v0.1.11-0.20220407163324-91bcfb1bdf9c/refactor/satisfy/find.go:517 +0x8fc
golang.org/x/tools/refactor/satisfy.(*Finder).stmt(0xc00808b890, {0x1055928?, 0xc00bb29d10?})
	/home/jia/go/pkg/mod/golang.org/x/tools@v0.1.11-0.20220407163324-91bcfb1bdf9c/refactor/satisfy/find.go:572 +0xbc5
golang.org/x/tools/refactor/satisfy.(*Finder).Find(0xc00808b890, 0xc017be0af0?, {0xc020dc1600, 0x14, 0x1?})
	/home/jia/go/pkg/mod/golang.org/x/tools@v0.1.11-0.20220407163324-91bcfb1bdf9c/refactor/satisfy/find.go:111 +0x1c5
golang.org/x/tools/internal/lsp/source.(*renamer).satisfy(0xc000320000)
	/home/jia/go/pkg/mod/golang.org/x/tools@v0.1.11-0.20220407163324-91bcfb1bdf9c/internal/lsp/source/rename_check.go:800 +0xdc
golang.org/x/tools/internal/lsp/source.(*renamer).checkMethod(0xc000320000, 0xc00b56f040)
	/home/jia/go/pkg/mod/golang.org/x/tools@v0.1.11-0.20220407163324-91bcfb1bdf9c/internal/lsp/source/rename_check.go:718 +0x2d4
golang.org/x/tools/internal/lsp/source.(*renamer).check(0xc000320000, {0x105dbe8, 0xc00b56f040?})
	/home/jia/go/pkg/mod/golang.org/x/tools@v0.1.11-0.20220407163324-91bcfb1bdf9c/internal/lsp/source/rename_check.go:46 +0x16b
golang.org/x/tools/internal/lsp/source.Rename({0x1057068?, 0xc007be20c0?}, {0x105fb20, 0xc00b699c20}, {0x10573b0, 0xc0089e83c0}, {0x20db3638?, 0xc0?}, {0xc010f6c320, 0xe})
	/home/jia/go/pkg/mod/golang.org/x/tools@v0.1.11-0.20220407163324-91bcfb1bdf9c/internal/lsp/source/rename.go:148 +0x945
golang.org/x/tools/internal/lsp.(*Server).rename(0xc96240?, {0x1057068, 0xc007be20c0}, 0xc0078fa000)
	/home/jia/go/pkg/mod/golang.org/x/tools@v0.1.11-0.20220407163324-91bcfb1bdf9c/internal/lsp/rename.go:20 +0x10d
golang.org/x/tools/internal/lsp.(*Server).Rename(0xc00f17a480?, {0x1057068?, 0xc007be20c0?}, 0xc96240?)
	/home/jia/go/pkg/mod/golang.org/x/tools@v0.1.11-0.20220407163324-91bcfb1bdf9c/internal/lsp/server_gen.go:224 +0x25
golang.org/x/tools/internal/lsp/protocol.serverDispatch({0x1057068, 0xc007be20c0}, {0x1063690, 0xc000148240}, 0xc00808a0c0, {0x1057308, 0xc007be2000})
	/home/jia/go/pkg/mod/golang.org/x/tools@v0.1.11-0.20220407163324-91bcfb1bdf9c/internal/lsp/protocol/tsserver.go:592 +0xbba
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1({0x1057068, 0xc007be20c0}, 0xc00808a0c0, {0x1057308, 0xc007be2000})
	/home/jia/go/pkg/mod/golang.org/x/tools@v0.1.11-0.20220407163324-91bcfb1bdf9c/internal/lsp/protocol/protocol.go:154 +0x90
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1({0x1057068, 0xc007be20c0}, 0xc00808a0c0, {0x1057308?, 0xc007be2000?})
	/home/jia/go/pkg/mod/golang.org/x/tools@v0.1.11-0.20220407163324-91bcfb1bdf9c/internal/lsp/lsprpc/lsprpc.go:512 +0xa43
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1({0x1057068, 0xc007be20c0}, 0xc017a82f00, {0x1057308?, 0xc007be2000?})
	/home/jia/go/pkg/mod/golang.org/x/tools@v0.1.11-0.20220407163324-91bcfb1bdf9c/internal/jsonrpc2/handler.go:35 +0xf6
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2()
	/home/jia/go/pkg/mod/golang.org/x/tools@v0.1.11-0.20220407163324-91bcfb1bdf9c/internal/jsonrpc2/handler.go:103 +0xa3
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	/home/jia/go/pkg/mod/golang.org/x/tools@v0.1.11-0.20220407163324-91bcfb1bdf9c/internal/jsonrpc2/handler.go:100 +0x20a
[Error - 3:36:45 PM] Connection to server got closed. Server will not be restarted.
[Error - 3:36:45 PM] Request textDocument/rename failed.
Error: Connection got disposed.
	at Object.dispose (/home/jia/.vscode/extensions/golang.go-0.33.0/dist/goMain.js:4909:25)
	at Object.dispose (/home/jia/.vscode/extensions/golang.go-0.33.0/dist/goMain.js:9694:35)
	at LanguageClient2.handleConnectionClosed (/home/jia/.vscode/extensions/golang.go-0.33.0/dist/goMain.js:11902:38)
	at LanguageClient2.handleConnectionClosed (/home/jia/.vscode/extensions/golang.go-0.33.0/dist/goMain.js:14311:15)
	at closeHandler (/home/jia/.vscode/extensions/golang.go-0.33.0/dist/goMain.js:11890:16)
	at CallbackList.invoke (/home/jia/.vscode/extensions/golang.go-0.33.0/dist/goMain.js:3025:35)
	at Emitter.fire (/home/jia/.vscode/extensions/golang.go-0.33.0/dist/goMain.js:3076:34)
	at closeHandler (/home/jia/.vscode/extensions/golang.go-0.33.0/dist/goMain.js:4171:24)
	at CallbackList.invoke (/home/jia/.vscode/extensions/golang.go-0.33.0/dist/goMain.js:3025:35)
	at Emitter.fire (/home/jia/.vscode/extensions/golang.go-0.33.0/dist/goMain.js:3076:34)
	at StreamMessageReader.fireClose (/home/jia/.vscode/extensions/golang.go-0.33.0/dist/goMain.js:3218:27)
	at Socket.<anonymous> (/home/jia/.vscode/extensions/golang.go-0.33.0/dist/goMain.js:3301:42)
	at Socket.emit (node:events:402:35)
	at Pipe.<anonymous> (node:net:687:12)

Failed to auto-collect gopls trace: no gopls log.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by jamalc** [comment]
Thanks for the report. Are you able to share the log you see in the gopls output channel leading up to the crash?
![106151310-3899a680-614a-11eb-9be7-42f2ae0592c9](https://user-images.githubusercontent.com/18269441/167738307-a772a587-9f8d-4e5d-9650-b01b4127b92d.png)
