### ISSUE TITLE
Go Test Runner Subtest test fails frequently

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#2239]
https://source.cloud.google.com/results/invocations/5f1b38c8-ede0-45e0-890b-550fd3c17ea8/targets

```
1 failing
  1) Go Test Runner
       Subtest
         discover and run:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/workspace/out/test/integration/goTest.run.test.js)
  	at listOnTimeout (node:internal/timers:557:17)
  	at processTimers (node:internal/timers:500:7)

Error: 1 tests failed.
	at /workspace/out/test/integration/index.js:62:27
	at done (/workspace/node_modules/mocha/lib/mocha.js:1068:7)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
[main 2022-05-12T20:49:14.183Z] Waiting for extension host with pid 374 to exit.
[main 2022-05-12T20:49:14.202Z] Extension host with pid 374 exited with code: 1, signal: null.
Exit code:   1
Done
```

**Comment by jamalc** [comment]
Did this start with refactoring or has it been an issue in the past?

**Comment by hyangah** [comment]
https://source.cloud.google.com/results/invocations/6def41d7-75ab-456b-9262-e94eb6c894a9/targets/golang%2Fvscode-go%2Fgcp_ubuntu%2Fpresubmit/log is a test run from our release branch which doesn't have the refactoring cls yet. So, I think this increased flakiness is unrelated to the refactoring changes.
