### ISSUE TITLE
gopls: crash on GitHub codespaces

### ISSUE THREAD

**Issue by gmeligio** [golang/vscode-go#2294]
gopls version: v0.8.4 (go1.18.2)
gopls flags: 
update flags: local
extension version: 0.33.1
go version: 1.18.2
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Fri, 17 Jun 2022 15:55:37 GMT
restart history:
Fri, 17 Jun 2022 15:49:51 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

1. Opened a GitHub repository in a Codespace.
2. Added code in a new line in .go file.
3. Press Ctrl+S to save the file.
4. gopls crashed.

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace and error messages from that window and paste it in this issue.

```log
[Error - 3:55:25 PM] Request textDocument/documentLink failed.
Error: Connection got disposed.
    at Object.dispose (/home/codespace/.vscode-remote/extensions/golang.go-0.33.1/dist/goMain.js:4909:25)
    at Object.dispose (/home/codespace/.vscode-remote/extensions/golang.go-0.33.1/dist/goMain.js:9694:35)
    at LanguageClient2.handleConnectionClosed (/home/codespace/.vscode-remote/extensions/golang.go-0.33.1/dist/goMain.js:11902:38)
    at LanguageClient2.handleConnectionClosed (/home/codespace/.vscode-remote/extensions/golang.go-0.33.1/dist/goMain.js:14311:15)
    at closeHandler (/home/codespace/.vscode-remote/extensions/golang.go-0.33.1/dist/goMain.js:11890:16)
    at CallbackList.invoke (/home/codespace/.vscode-remote/extensions/golang.go-0.33.1/dist/goMain.js:3025:35)
    at Emitter.fire (/home/codespace/.vscode-remote/extensions/golang.go-0.33.1/dist/goMain.js:3076:34)
    at closeHandler (/home/codespace/.vscode-remote/extensions/golang.go-0.33.1/dist/goMain.js:4171:24)
    at CallbackList.invoke (/home/codespace/.vscode-remote/extensions/golang.go-0.33.1/dist/goMain.js:3025:35)
    at Emitter.fire (/home/codespace/.vscode-remote/extensions/golang.go-0.33.1/dist/goMain.js:3076:34)
    at StreamMessageReader.fireClose (/home/codespace/.vscode-remote/extensions/golang.go-0.33.1/dist/goMain.js:3218:27)
    at Socket.<anonymous> (/home/codespace/.vscode-remote/extensions/golang.go-0.33.1/dist/goMain.js:3301:42)
    at Socket.emit (node:events:402:35)
    at Socket.emit (node:domain:475:12)
    at Pipe.<anonymous> (node:net:687:12)
```

Failed to auto-collect gopls trace: unrecognized crash pattern.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

[go_fail.log](https://github.com/golang/vscode-go/files/8929031/go_fail.log)

**Comment by dle8** [comment]
What is the memory limit of the container that you ran gopls from? If the code is open sourced, can you provide the repo url?

**Comment by gmeligio** [comment]
Thank you for answering.

This was the file I was trying to modify.
https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/elasticbeanstalk/application_version.go

The codespace has 8 GB of RAM. 

![Screenshot_20220621_230756](https://user-images.githubusercontent.com/22875166/174897668-43d11495-431b-4a68-aea8-d814bf58d37b.png)

**Comment by hyangah** [comment]
From codespace, I see gopls taking up 3.5~4.5G of memory in stable state and gopls is loading ~600 packages. In addition to this, I see other node processes (including vscode itself's), daemons, default linter (staticcheck), and other go commands fighting for resources.

I tried to turn off linter and use `"gopls": { "build.memoryMode": "DegradeClosed" }`. That lowered gopls's own memory usage slightly lower (~3.3G). However, when I run a test, the go compiler or test itself easily use more memory (1.2G for link!) and push the total memory usage near the limit - if we are not too unlucky (ha!), the processes are threshing, if unlucky, gopls or other random processes seem to get killed. 

I guess terraform-provider-aws repo is too big for this extension & gopls to handle within the container. 

High memory use in gopls is [a known issue](https://github.com/golang/go/issues?q=is%3Aissue+is%3Aopen+label%3Agopls%2Fperformance). Unfortunately,  I don't see any immediate solution to mitigate the issue.

**Comment by gmeligio** [comment]
Thank you for the investigation. I understand the issue. I didn't know it could consume so much memory. It could be related to the package count, but I've worked in the past with other big repos like https://github.com/aws/aws-cdk/ with TypeScript in a codespace with almost no issues. I haven't looked into the gopls internals and don't know another way to help either.

In the meantime, it works great on the desktop, and I will use it there. If possible, I want to leave this issue open for the use case of memory improvement in a codespace.

**Comment by hyangah** [comment]
Closing this issue - I hope other GitHub codespaces users who encounter the same issue find this issue useful, while the gopls team is working on its scale issue.

Thanks @gmeligio
