### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by csuzhangxc** [golang/vscode-go#2321]
gopls version: v0.8.4
gopls flags: 
update flags: proxy
extension version: 0.29.0
go version: 1.18.1
environment: code-server linux
initialization error: undefined
issue timestamp: Wed, 06 Jul 2022 07:10:29 GMT
restart history:
Wed, 06 Jul 2022 07:09:30 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: interface conversion: interface {} is *cache.parseWorkData, not *cache.parseModData

goroutine 214 [running]:
golang.org/x/tools/internal/lsp/cache.(*parseModHandle).parse(0x842280%3F, {0xbab180%3F, 0x4000492b00%3F}, 0x44%3F)
	  mod.go:42  0x98
golang.org/x/tools/internal/lsp/cache.(*snapshot).ParseMod(0x40002938c0, {0xbab180, 0x4000492b00}, {0xbab4c8, 0x4000209aa0})
	  mod.go:101  0x270
golang.org/x/tools/internal/lsp.modLinks({0xbab180, 0x4000492b00}, {0xbb3868, 0x40002938c0}, {0xbab4c8%3F, 0x4000209aa0%3F})
	  link.go:48  0x60
golang.org/x/tools/internal/lsp.(*Server).documentLink(0x4000740ea0%3F, {0xbab180, 0x4000492b00}, 0x400079a630%3F)
	  link.go:35  0xfc
golang.org/x/tools/internal/lsp.(*Server).DocumentLink(0x400082c300%3F, {0xbab180%3F, 0x4000492b00%3F}, 0x7ea2a0%3F)
	  server_gen.go:120  0x28
golang.org/x/tools/internal/lsp/protocol.serverDispatch({0xbab180, 0x4000492b00}, {0xbb6fe0, 0x40004ce6c0}, 0x4000740e70, {0xbab420, 0x4000492a00})
	  tsserver.go:677  0x2468
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1({0xbab180, 0x4000492b00}, 0x4000740e70, {0xbab420, 0x4000492a00})
	  protocol.go:157  0x70
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1({0xbab180, 0x4000492b00}, 0x4000740e70, {0xbab420%3F, 0x4000492a00%3F})
	  lsprpc.go:511  0x7d4
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1({0xbab180, 0x4000492b00}, 0x4000206a38, {0xbab420%3F, 0x4000492a00%3F})
	  handler.go:35  0xfc
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2()
	  handler.go:103  0x90
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x1ec
[Error - 7:10:13 AM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment]
Thank you for reporting this. Transferring to the gopls issue tracker.
