### ISSUE TITLE
gopls "Nonexistent formatter" test on windows frequently fails

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#2454]
From the trace, it looks like the test fails to teardown the gopls on time.

```
  1) Go Extension Tests With Gopls
       "after all" hook for "Nonexistent formatter":
     Error: Stopping the server timed out
  	at d:\a\vscode-go\vscode-go\node_modules\vscode-languageclient\lib\common\client.js:898:23
  	at async Env.teardown (d:\a\vscode-go\vscode-go\out\test\gopls\extension.test.js:135:9)

Error: 1 tests failed.
	at d:\a\vscode-go\vscode-go\out\test\gopls\index.js:59:27
	at done (d:\a\vscode-go\vscode-go\node_modules\mocha\lib\mocha.js:1068:7)
[main 2022-09-12T19:39:40.988Z] Waiting for extension host with pid 6368 to exit.
[main 2022-09-12T19:39:41.054Z] Extension host with pid 6368 exited with code: 0, signal: null.
Exit code:   1
Done
```

**Comment by findleyr** [comment]
Did this start after https://go.dev/cl/416594? That CL caused gopls to actually wait for outstanding work during shutdown.

**Comment by hyangah** [comment]
With the change, the test doesn't fail, but so far I don't see captured logs (no activity??)
Moving this out of v0.36.0 milestone.
