### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by elvinchan** [golang/vscode-go#2574]
gopls version: v0.11.0 (go1.17.13)
gopls flags: 
update flags: proxy
extension version: 0.36.0
go version: 1.17.13
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Fri, 16 Dec 2022 07:59:44 GMT
restart history:
Thu, 15 Dec 2022 01:43:33 GMT: activation (enabled: true)
Thu, 15 Dec 2022 01:53:45 GMT: installation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: runtime error: slice bounds out of range [:1618] with capacity 1617

goroutine 146 [running]:
golang.org/x/tools/gopls/internal/lsp/cache.fixArrayType(0xc003c36390, {0xfd3ab0, 0xc0057d6300}, 0x0, {0xc000dd8a00, 0x0, 0x651})
	  parse.go:996  0x31c
golang.org/x/tools/gopls/internal/lsp/cache.fixAST.func1({0xfd3970, 0xc003c36390}, {0xfd3ab0, 0xc0057d6300})
	  parse.go:568  0x23f
golang.org/x/tools/gopls/internal/lsp/cache.walkASTWithParent.func1({0xfd3970, 0xc003c36390})
	  parse.go:628  0xcc
go/ast.inspector.Visit(0xc0057eb5f0, {0xfd3970, 0xc003c36390})
	  walk.go:375  0x31
go/ast.Walk({0xfc2ac0, 0xc0057eb5f0}, {0xfd3970, 0xc003c36390})
	  walk.go:50  0x5f
go/ast.walkExprList({0xfc2ac0, 0xc0057eb5f0}, {0xc0057d6080, 0x4, 0xc006170c90})
	  walk.go:24  0x87
go/ast.Walk({0xfc2ac0, 0xc0057eb5f0}, {0xfd3ab0, 0xc0057d6300})
	  walk.go:137  0x92b
go/ast.Walk({0xfc2ac0, 0xc0057eb5f0}, {0xfd3ce0, 0xc00447e790})
	  walk.go:197  0xf3a
go/ast.walkStmtList({0xfc2ac0, 0xc0057eb5f0}, {0xc004cbd000, 0xf, 0xc006170c90})
	  walk.go:30  0x87
go/ast.Walk({0xfc2ac0, 0xc0057eb5f0}, {0xfd3a60, 0xc0064482a0})
	  walk.go:225  0xedf
go/ast.Walk({0xfc2ac0, 0xc0057eb5f0}, {0xfd3dd0, 0xc00447e7a0})
	  walk.go:98  0x18fc
go/ast.Walk({0xfc2ac0, 0xc0057eb5f0}, {0xfd3ab0, 0xc0057d6380})
	  walk.go:136  0x90b
go/ast.Walk({0xfc2ac0, 0xc0057eb5f0}, {0xfd3e48, 0xc00447e280})
	  walk.go:211  0x23e
go/ast.walkStmtList({0xfc2ac0, 0xc0057eb5f0}, {0xc006b79700, 0x5, 0x203000})
	  walk.go:30  0x87
go/ast.Walk({0xfc2ac0, 0xc0057eb5f0}, {0xfd3a60, 0xc004563b60})
	  walk.go:225  0xedf
go/ast.Inspect(...)
	  walk.go:387
golang.org/x/tools/gopls/internal/lsp/cache.walkASTWithParent({0xfd3a60, 0xc004563b60}, 0xc003c31540)
	  parse.go:611  0xac
golang.org/x/tools/gopls/internal/lsp/cache.fixAST({0xfd8fe0, 0xc006170c90}, {0xfd3a60, 0xc004563b60}, 0xc003d4f440, {0xc000dd8a00, 0x651, 0x651})
	  parse.go:557  0x147
golang.org/x/tools/gopls/internal/lsp/cache.fixAST.func1({0xfd3998, 0xc003c07d00}, {0xfd3a60, 0xc004563b60})
	  parse.go:562  0x1af
golang.org/x/tools/gopls/internal/lsp/cache.walkASTWithParent.func1({0xfd3998, 0xc003c07d00})
	  parse.go:628  0xcc
go/ast.inspector.Visit(0xc0057eb260, {0xfd3998, 0xc003c07d00})
	  walk.go:375  0x31
go/ast.Walk({0xfc2ac0, 0xc0057eb260}, {0xfd3998, 0xc003c07d00})
	  walk.go:50  0x5f
go/ast.walkStmtList({0xfc2ac0, 0xc0057eb260}, {0xc006b79700, 0x5, 0xc006170c90})
	  walk.go:30  0x87
go/ast.Walk({0xfc2ac0, 0xc0057eb260}, {0xfd3a60, 0xc004563b60})
	  walk.go:225  0xedf
go/ast.Walk({0xfc2ac0, 0xc0057eb260}, {0xfd3da8, 0xc004563b90})
	  walk.go:346  0x7dc
go/ast.walkDeclList({0xfc2ac0, 0xc0057eb260}, {0xc003ada4c0, 0x3, 0x203000})
	  walk.go:36  0x87
go/ast.Walk({0xfc2ac0, 0xc0057eb260}, {0xfd3d58, 0xc006b79780})
	  walk.go:355  0x15c5
go/ast.Inspect(...)
	  walk.go:387
golang.org/x/tools/gopls/internal/lsp/cache.walkASTWithParent({0xfd3d58, 0xc006b79780}, 0xc003c31130)
	  parse.go:611  0xac
golang.org/x/tools/gopls/internal/lsp/cache.fixAST({0xfd8fe0, 0xc006170c90}, {0xfd3d58, 0xc006b79780}, 0xc003d4f440, {0xc000dd8a00, 0x651, 0x651})
	  parse.go:557  0x147
golang.org/x/tools/gopls/internal/lsp/cache.parseGoImpl({0xfd8fe0, 0xc0061b7860}, 0xc00054aa10, {0xfd9210, 0xc00054aa10}, 0x2)
	  parse.go:195  0x9c5
golang.org/x/tools/gopls/internal/lsp/cache.peekOrParse({0xfd8fe0, 0xc0061b7860}, 0xc004ae701a, {0xfd9210, 0xc00054aa10}, 0xc6ab0bb0658abb4e)
	  snapshot.go:2236  0x8e
golang.org/x/tools/gopls/internal/lsp/cache.metadataChanges({0xfd8fe0, 0xc0061b7860}, 0xc00054aa10, {0x7f4645d2f098, 0xc002a7c510}, {0xfd9210, 0xc00054aa10})
	  snapshot.go:2210  0x44a
golang.org/x/tools/gopls/internal/lsp/cache.(*snapshot).clone(0xc000374840, {0xfd9718, 0xc003bdf610}, {0xfd8fe0, 0xc0002dff20}, 0xc0061b6780, 0x0)
	  snapshot.go:1851  0x1631
golang.org/x/tools/gopls/internal/lsp/cache.(*View).invalidateContent(0xc000144000, {0xfd8fe0, 0xc0002be6c0}, 0x3d, 0x0)
	  view.go:793  0x194
golang.org/x/tools/gopls/internal/lsp/cache.(*Session).DidModifyFiles(0xc0007510a0, {0xfd8fe0, 0xc0002be6c0}, {0xc002d8f900, 0x1, 0x1})
	  session.go:545  0x3ca
golang.org/x/tools/gopls/internal/lsp.(*Server).processModifications(0xc0002c2000, {0xfd8fe0, 0xc0002be6c0}, {0xc002d8f8b0, 0x1, 0x1}, 0x0, 0xc005a1e360)
	  text_synchronization.go:304  0x255
golang.org/x/tools/gopls/internal/lsp.(*Server).didModifyFiles(0xc0002c2000, {0xfd8fe0, 0xc0002be6c0}, {0xc002d8f8b0, 0xc003c04090, 0xc4c7a0}, 0x0)
	  text_synchronization.go:228  0x577
golang.org/x/tools/gopls/internal/lsp.(*Server).didOpen(0xc0002c2000, {0xfd8fe0, 0xc0002be6c0}, 0xc0016f81c0)
	  text_synchronization.go:97  0x273
golang.org/x/tools/gopls/internal/lsp.(*Server).DidOpen(0xc000351000, {0xfd8fe0, 0xc0002be6c0}, 0xc4c7a0)
	  server_gen.go:88  0x25
golang.org/x/tools/gopls/internal/lsp/protocol.serverDispatch({0xfd8fe0, 0xc0002be6c0}, {0x100ae38, 0xc0002c2000}, 0xc005e4be00, {0xfd9328, 0xc0002be600})
	  tsserver.go:323  0xeda
golang.org/x/tools/gopls/internal/lsp/protocol.ServerHandler.func1({0xfd8fe0, 0xc0002be6c0}, 0xc005e4be00, {0xfd9328, 0xc0002be600})
	  protocol.go:157  0x90
golang.org/x/tools/gopls/internal/lsp/lsprpc.handshaker.func1({0xfd8fe0, 0xc0002be6c0}, 0xc005e4be00, {0xfd9328, 0xc0002be600})
	  lsprpc.go:519  0xa7c
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1({0xfd8fe0, 0xc0002be6c0}, 0xc0003f1d70, {0xfd9328, 0xc0002be600})
	  handler.go:35  0xf6
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2()
	  handler.go:103  0xa3
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x20f
[Error - 3:59:25 PM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment]
Hi, thanks for the report. Can you tell us anything about the code you were editing when you encountered this crash?

**Comment by findleyr** [comment]
IIRC there was a scenario in Go 1.17 where the end position of a BadExpr could overflow the file, as it appears to have done here. Unfortunately I'm having trouble finding it, or reproducing this crash in a unit test.

In the meantime, I would recommend upgrading to Go 1.19.

**Comment by elvinchan** [comment]
After I upgrade to Go 1.19, it no longer appear ^^
