### ISSUE TITLE
test/integration/statusbar: updateGoVarsFromConfig is flaky

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#261]
<pre>
  1) #updateGoVarsFromConfig()
       should recognize the adjusted goroot using go.alternateTools:

      AssertionError [ERR_ASSERTION]: 'Go 2.0.0' == 'Go 3.0.0'
      + expected - actual

      -Go 2.0.0
      +Go 3.0.0
      
  	at Suite.<anonymous> (out/test/integration/statusbar.test.js:125:16)
  	at Generator.next (<anonymous>)
  	at fulfilled (out/test/integration/statusbar.test.js:10:58)
</pre>

**Comment by hyangah** [comment]
@mcjcloud It seems like this test is currently not running - using `async` for setup in mocha never seemed to work. 
Looks like the bin path is cached and the fake go binary used in testing is never picked up. So, the test is completely broken.
Will move to v0.17.0 milestone to keep investigating.
