### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by buth** [golang/vscode-go#2801]
gopls version: v0.12.2 (go1.20.4)
gopls flags: 
update flags: proxy
extension version: 0.38.0
go version: 1.20.4
environment: Visual Studio Code darwin
initialization error: undefined
issue timestamp: Tue, 06 Jun 2023 01:34:11 GMT
restart history:
Tue, 06 Jun 2023 01:29:42 GMT: manual (enabled: true)
Tue, 06 Jun 2023 01:30:36 GMT: manual (enabled: true)
Tue, 06 Jun 2023 01:30:44 GMT: manual (enabled: true)
Tue, 06 Jun 2023 01:30:47 GMT: manual (enabled: true)
Tue, 06 Jun 2023 01:31:01 GMT: manual (enabled: true)
Tue, 06 Jun 2023 01:31:34 GMT: manual (enabled: true)
Tue, 06 Jun 2023 01:32:02 GMT: manual (enabled: true)
Tue, 06 Jun 2023 01:32:14 GMT: manual (enabled: true)
Tue, 06 Jun 2023 01:32:44 GMT: manual (enabled: true)
Tue, 06 Jun 2023 01:33:04 GMT: manual (enabled: true)
Tue, 06 Jun 2023 01:34:09 GMT: manual (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

The following code immediately caused a crash.

```go
package crash

type a[K any] *[]K

func (*a[K]) a() {}
```

<pre>panic: interface conversion: types.Object is nil, not *types.Func

goroutine 181 [running]:
golang.org/x/tools/internal/typeparams.OriginMethod(0x14000758660)
	  common.go:108  0x14c
golang.org/x/tools/gopls/internal/lsp/source/methodsets.(*indexBuilder).build.func2(0x140000491c0, 0x14000758660)
	  methodsets.go:248  0x1c4
golang.org/x/tools/gopls/internal/lsp/source/methodsets.methodSetInfo({0x10383ecf0, 0x1400015cc40}, 0x14000775718)
	  methodsets.go:309  0x1f0
golang.org/x/tools/gopls/internal/lsp/source/methodsets.(*indexBuilder).build(0x14000775a68, 0x14000048a00, 0x1400009c6e0)
	  methodsets.go:261  0x4f0
golang.org/x/tools/gopls/internal/lsp/source/methodsets.NewIndex(...)
	  methodsets.go:98
golang.org/x/tools/gopls/internal/lsp/cache.typeCheckImpl({0x1038427c8, 0x1400074bf50}, 0x102c206f0%3F, {{0x14000122dc8, 0x18}, {0x14000122dc8, 0x18}, {0x140002825d0, 0x5}, {0x14000226510, ...}, ...})
	  check.go:1269  0x1b4
golang.org/x/tools/gopls/internal/lsp/cache.(*typeCheckBatch).checkPackage(0x1400042fec8%3F, {0x1038427c8, 0x1400074b380}, 0x14000744360)
	  check.go:634  0x190
golang.org/x/tools/gopls/internal/lsp/cache.(*typeCheckBatch).handleSyntaxPackage(0x1400009c690, {0x1038427c8, 0x1400074b380}, 0x0%3F, {0x14000122dc8, 0x18})
	  check.go:518  0x3d0
golang.org/x/tools/gopls/internal/lsp/cache.(*snapshot).forEachPackageInternal.func2()
	  check.go:401  0x34
golang.org/x/sync/errgroup.(*Group).Go.func1()
	  errgroup.go:75  0x5c
created by golang.org/x/sync/errgroup.(*Group).Go
	  errgroup.go:72  0xa0
[Error - 9:34:09 PM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment]
Thank you for the report. We will fix this gopls crash.

Moving to the Go issue tracker, since it is a gopls issue.
