### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by rossb83** [golang/vscode-go#2823]
gopls version: v0.12.2 (go1.20.4)
gopls flags: -logfile /home/user/gopls.log -rpc.trace
update flags: off
extension version: 0.38.0-upstream-0.1.7-uber
go version: 1.20.4
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Sun, 18 Jun 2023 04:57:07 GMT
restart history:
Sun, 18 Jun 2023 04:56:23 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: cannot export package unsafe

goroutine 2285 [running]:
golang.org/x/tools/internal/gcimporter.iexportCommon.func1()
	  iexport.go:93  0x8a
panic({0xd82ea0, 0x114f800})
	  panic.go:884  0x213
golang.org/x/tools/internal/gcimporter.(*iexporter).pushDecl(0xc004730000, {0x11617f8, 0xc000037270})
	  iexport.go:395  0xf6
golang.org/x/tools/internal/gcimporter.iexportCommon({0x1151100, 0xc002cd1a10}, 0xc004f8aa40, 0x0, 0x1, 0x2, {0xc005ff5ca8, 0x1, 0xc002cd1980%3F})
	  iexport.go:124  0x93a
golang.org/x/tools/internal/gcimporter.IExportShallow(0xdc6300%3F, 0xc000036230)
	  iexport.go:43  0x75
golang.org/x/tools/gopls/internal/lsp/cache.(*typeCheckBatch).checkPackage.func1()
	  check.go:646  0x2b1
created by golang.org/x/tools/gopls/internal/lsp/cache.(*typeCheckBatch).checkPackage
	  check.go:638  0x305
[Error - 4:56:54 AM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment]
Thank you for the report.

This is an interesting crash. There is code explicitly guarding against exporting unsafe in this control flow, but it checks only the package ID, not package path, which could theoretically misidentify a variant of the "unsafe" package.. However, there should not be any variants of the `"unsafe"` package. An exception to this is PGO variants, but these were explicitly avoided in #60456, and in any case you are using go1.20.

So, I think I can probably fix this, but I don't know how to repro.

Can you share anything about the code you were editing when you encountered this crash?

Do you have anything interesting in your `settings.json`?
