### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by TristanSpeakEasy** [golang/vscode-go#2866]
gopls version: v0.12.4 (go1.20.5)
gopls flags: 
update flags: proxy
extension version: 0.39.0
go version: 1.20.5
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Wed, 12 Jul 2023 01:49:36 GMT
restart history:
Mon, 10 Jul 2023 06:01:44 GMT: activation (enabled: true)
Wed, 12 Jul 2023 00:24:00 GMT: manual (enabled: true)
Wed, 12 Jul 2023 00:38:53 GMT: manual (enabled: true)
Wed, 12 Jul 2023 00:49:51 GMT: manual (enabled: true)
Wed, 12 Jul 2023 01:15:40 GMT: manual (enabled: true)
Wed, 12 Jul 2023 01:42:51 GMT: manual (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0xc3be7c]

goroutine 30894 [running]:
golang.org/x/tools/gopls/internal/lsp/cache.(*View).Options(0x115b080%3F)
	  view.go:405  0x3c
golang.org/x/tools/gopls/internal/lsp/cache.(*Session).DidModifyFiles(0xc0001229c0, {0x115b080, 0xc0037fd8f0}, {0xc00df32000, 0xcb, 0x0%3F})
	  session.go:455  0x1085
golang.org/x/tools/gopls/internal/lsp.(*Server).didModifyFiles(0xc00039a4e0, {0x115b080%3F, 0xc0037fd8f0}, {0xc00e7ceb90, 0x1, 0x1}, 0x2)
	  text_synchronization.go:273  0x513
golang.org/x/tools/gopls/internal/lsp.(*Server).didChangeWatchedFiles(0xd5d700%3F, {0x115b080%3F, 0xc00442d860%3F}, 0xc00680fc08)
	  text_synchronization.go:189  0x315
golang.org/x/tools/gopls/internal/lsp.(*Server).DidChangeWatchedFiles(0xc00ddd6000%3F, {0x115b080%3F, 0xc00442d860%3F}, 0xd5d700%3F)
	  server_gen.go:60  0x25
golang.org/x/tools/gopls/internal/lsp/protocol.serverDispatch({0x115b080, 0xc00442d860}, {0x116bcd0, 0xc00039a4e0}, 0xc0037fd830, {0x115b2e8, 0xc00442d7a0})
	  tsserver.go:646  0x5444
golang.org/x/tools/gopls/internal/lsp/protocol.ServerHandler.func1({0x115b080, 0xc00442d860}, 0xc0037fd830, {0x115b2e8, 0xc00442d7a0})
	  protocol.go:157  0x90
golang.org/x/tools/gopls/internal/lsp/lsprpc.handshaker.func1({0x115b080, 0xc00442d860}, 0xc0037fd830, {0x115b2e8%3F, 0xc00442d7a0%3F})
	  lsprpc.go:519  0x9f9
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1({0x115b080, 0xc00442d860}, 0xc00d5081c8, {0x115b2e8%3F, 0xc00442d7a0%3F})
	  handler.go:35  0xf6
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2()
	  handler.go:103  0xa3
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x20a
[Error - 11:49:23 AM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment]
Thanks for the report! @TristanSpeakEasy 
We will transfer this to the gopls issue tracker.
