### ISSUE TITLE
gopls: Go workspaces are no longer working correctly

### ISSUE THREAD

**Issue by Josh-Ring-SD** [golang/vscode-go#2884]
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
	- go1.20.6 linux/amd64
* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
	- Build info
----------
golang.org/x/tools/gopls v0.12.4
    golang.org/x/tools/gopls@v0.12.4 h1:nce5etAamR46d9oNGxop1aRK5rDQ0NqcY/SHIcyfEKY=
    github.com/BurntSushi/toml@v1.2.1 h1:9F2/+DoOYIOksmaJFPw1tGFy1eDnIJXg+UHjuD8lTak=
    github.com/google/go-cmp@v0.5.9 h1:O2Tfq5qg4qc4AmwVlvv0oLiVAGB7enBSJ2x2DqQFi38=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/exp@v0.0.0-20220722155223-a9213eeb770e h1:+WEEuIdZHnUeJJmEUjyYC2gfUMj69yZXw17EnHg/otA=
    golang.org/x/exp/typeparams@v0.0.0-20221212164502-fae10dda9338 h1:2O2DON6y3XMJiQRAS1UWU+54aec2uopH3x7MAiqGW6Y=
    golang.org/x/mod@v0.11.0 h1:bUO06HqtnRcc/7l71XBe4WcqTZ+3AH1J59zWDDwLKgU=
    golang.org/x/sync@v0.3.0 h1:ftCYgMx6zT/asHUrPw8BLLscYtGznsLAnjq5RH9P66E=
    golang.org/x/sys@v0.9.0 h1:KS/R3tvhPqvJvwcKfnBHJwwthS11LRhmM5D59eEXa0s=
    golang.org/x/text@v0.10.0 h1:UpjohKhiEgNc0CSauXmwYftY1+LlaC75SJwh0SgCX58=
    golang.org/x/tools@v0.10.1-0.20230622221742-0622ad2359a7 h1:5PWemM67wMSPpO0Y3lOPlyvgO3z56YkZRxPFcdd300g=
    golang.org/x/vuln@v0.0.0-20230110180137-6ad3e3d07815 h1:A9kONVi4+AnuOr1dopsibH6hLi1Huy54cbeJxnq4vmU=
    honnef.co/go/tools@v0.4.2 h1:6qXr+R5w+ktL5UkwEbPp+fEvfyoMPche6GkOpGHZcLc=
    mvdan.cc/gofumpt@v0.4.0 h1:JVf4NN1mIpHogBj7ABpgOyZc65/UUOkKQFkoURsz4MM=
    mvdan.cc/xurls/v2@v2.4.0 h1:tzxjVAj+wSBmDcF6zBB7/myTy3gX9xvi8Tyr28AuQgc=
go: go1.20.2
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
	- 1.80.1
74f6148eb9ea00507ec113ec51c489d6ffb4b771
x64
* Check your installed extensions to get the version of the VS Code Go extension
	- v0.39.1
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
	- GOBIN: undefined
toolsGopath: 
gopath: /home/joshuaring/go
GOROOT: /usr/local/go
PATH: /home/joshuaring/.nvm/versions/node/v18.12.1/bin:/home/joshuaring/miniconda3/bin:/home/joshuaring/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/usr/local/go/bin:/home/joshuaring/zig/zig-linux-x86_64-0.11.0-dev.53+cbed6bb08:/home/joshuaring/zls/bin:/home/joshuaring/apps/blender-3.3.1-linux-x64:/usr/local/go/bin:/home/joshuaring/zig/zig-linux-x86_64-0.11.0-dev.53+cbed6bb08:/home/joshuaring/zls/bin:/home/joshuaring/apps/blender-3.3.1-linux-x64:/home/joshuaring/Projects/data_team_monorepo/infrastructure/node_modules/.bin

	go:	/usr/local/go/bin/go: go version go1.20.6 linux/amd64

	gotests:	not installed
	gomodifytags:	not installed
	impl:	not installed
	goplay:	not installed
	dlv:	/home/joshuaring/go/bin/dlv	(version: v1.21.0 built with go: go1.20.6)
	staticcheck:	not installed
	gopls:	/home/joshuaring/go/bin/gopls	(version: v0.12.4 built with go: go1.20.2)

go env
Workspace Folder (test): /home/joshuaring/Projects/test
	GO111MODULE="on"
	GOARCH="amd64"
	GOBIN=""
	GOCACHE="/home/joshuaring/.cache/go-build"
	GOENV="/home/joshuaring/.config/go/env"
	GOEXE=""
	GOEXPERIMENT=""
	GOFLAGS=""
	GOHOSTARCH="amd64"
	GOHOSTOS="linux"
	GOINSECURE=""
	GOMODCACHE="/home/joshuaring/go/pkg/mod"
	GONOPROXY="github.com/silverdoorapartments"
	GONOSUMDB="github.com/silverdoorapartments"
	GOOS="linux"
	GOPATH="/home/joshuaring/go"
	GOPRIVATE="github.com/silverdoorapartments"
	GOPROXY="https://proxy.golang.org,direct"
	GOROOT="/usr/local/go"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
	GOVCS=""
	GOVERSION="go1.20.6"
	GCCGO="gccgo"
	GOAMD64="v1"
	AR="ar"
	CC="gcc"
	CXX="g++"
	CGO_ENABLED="0"
	GOMOD="/home/joshuaring/Projects/go.mod"
	GOWORK="/home/joshuaring/Projects/test/go.work"
	CGO_CFLAGS="-O2 -g"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-O2 -g"
	CGO_FFLAGS="-O2 -g"
	CGO_LDFLAGS="-O2 -g"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -m64 -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build1384710745=/tmp/go-build -gno-record-gcc-switches"
</details>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

    "go.testFlags": [
        "-v"
    ],
    "go.testTimeout": "99999s",

### Describe the bug
**A clear and concise description of what the bug.**
- In VScode see errors on highlight of each module's `package PACKAGE_NAME_HERE` line like:
> This file is within module "bar", which is not included in your workspace.
To fix this problem, you can add this module to your go.work file (/home/joshuaring/Projects/test/go.work)
See the documentation for more information on setting up your workspace:
https://github.com/golang/tools/blob/master/gopls/doc/workspace.md.go list

- In VScode see errors on hover of the import from the other module:
```
import (
	"example-foo.com/foo_package"
)
```
error:
> could not import example-foo.com/foo_package (current file is not included in a workspace module)compiler[BrokenImport]

**A clear and concise description of what you expected to happen.**
- Expect to be able to ctrl click into each module's functions
- Expect to be able hover and see description of function
- Expect to be able to import module from within workspace
- Expect the workspace file to be read

### Steps to reproduce the behavior:
- create two directories `foo` and `bar`
- in the foo directory init a module via `go mod init example-foo.com`
- in the bar directory init a module via `go mod init example-bar.com`
- in the parent directory above the module directories  `go work init` and `go work use foo bar`
- This gives a `go.work` like:
```
go 1.20

use (
	./bar
	./foo
)
```
- The `go.mod` file in directory `foo`:
```
module example-foo.com

go 1.20
```
- The `go.mod` file in the directory `bar` **edited to the following, so it can import the foo module**
```
module example-bar.com

go 1.20

require (
	example-foo.com/foo_package v0.0.0
)

replace example-foo.com/foo_package v0.0.0 => ../foo

```
- added a `main.go` to `foo` directory:
```
package foo_package

import "log"

func GreatSandra() {
	log.Print("hello from foo")
}
```
- added a `main.go` to `bar` directory:
```
package main

import (
	"log"

	"example-foo.com/foo_package"
)

func GreatScot() {
	foo_package.GreatSandra()
}

func main() {
	GreatScot()
}

```
- Program runs correctly outputting:
```
2023/07/21 14:46:49 hello from foo
```

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.

![image](https://github.com/golang/vscode-go/assets/110227972/635b258b-53d4-413d-97e7-1911bb15d585)
![image](https://github.com/golang/vscode-go/assets/110227972/bb23685d-e37a-434a-86ff-502c50aa6710)

### output from `Go pls` :
https://pastebin.com/qhb6LXGR

**Comment by findleyr** [comment]
Hi, thanks for the report. This is strange, and clearly very confusing. However, I can't reproduce this with your reproducer.  I expected something obvious, but nothing obvious jumps out at me from your logs (thanks for providing them).

Could you please try the following: restart gopls (`Go: Restart Language Server`) in the command palette. Does the problem persist? If so, I'm very confused.

I need more information to diagnose this. Could you please collect full RPC logs from a short session demonstrating the problem, following the instructions here: https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md#collect-gopls-information

Thanks!

**Comment by Josh-Ring-SD** [comment]
**Log (Extension Host)**
<details>
2023-08-01 13:49:06.684 [info] Extension host with pid 272058 started
2023-08-01 13:49:06.684 [info] Skipping acquiring lock for /home/joshuaring/.config/Code/User/workspaceStorage/26ac9007df1a271fa574b9172138ee02.
2023-08-01 13:49:06.801 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2023-08-01 13:49:06.812 [info] ExtensionService#_doActivateExtension golang.go, startup: false, activationEvent: 'onLanguage:go'
2023-08-01 13:49:07.264 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
2023-08-01 13:49:07.313 [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
2023-08-01 13:49:07.346 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2023-08-01 13:49:07.432 [info] Eager extensions activated
2023-08-01 13:49:07.504 [error] [golang.go] provider FAILED
2023-08-01 13:49:07.517 [error] Error: semantictokens are disabled
	at handleResponse (/home/joshuaring/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:2126:40)
	at handleMessage (/home/joshuaring/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:1936:11)
	at processMessageQueue (/home/joshuaring/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:1951:13)
	at Immediate.<anonymous> (/home/joshuaring/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:1927:11)
	at process.processImmediate (node:internal/timers:466:21)
2023-08-01 13:49:07.519 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2023-08-01 13:49:07.525 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2023-08-01 13:49:07.679 [error] [golang.go] provider FAILED
2023-08-01 13:49:07.679 [error] Error: semantictokens are disabled
	at handleResponse (/home/joshuaring/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:2126:40)
	at handleMessage (/home/joshuaring/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:1936:11)
	at processMessageQueue (/home/joshuaring/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:1951:13)
	at Immediate.<anonymous> (/home/joshuaring/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:1927:11)
	at process.processImmediate (node:internal/timers:466:21)
2023-08-01 13:49:07.801 [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
2023-08-01 13:49:07.835 [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication, startup: false, activationEvent: 'onAuthenticationRequest:microsoft'
2023-08-01 13:49:08.451 [error] [golang.go] provider FAILED
2023-08-01 13:49:08.452 [error] Error: no package data for import "example-foo.com"
	at handleResponse (/home/joshuaring/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:2126:40)
	at handleMessage (/home/joshuaring/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:1936:11)
	at processMessageQueue (/home/joshuaring/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:1951:13)
	at Immediate.<anonymous> (/home/joshuaring/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:1927:11)
	at process.processImmediate (node:internal/timers:466:21)
2023-08-01 13:49:10.210 [error] [golang.go] provider FAILED
2023-08-01 13:49:10.210 [error] Error: no package data for import "example-foo.com"
	at handleResponse (/home/joshuaring/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:2126:40)
	at handleMessage (/home/joshuaring/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:1936:11)
	at processMessageQueue (/home/joshuaring/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:1951:13)
	at Immediate.<anonymous> (/home/joshuaring/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:1927:11)
	at process.processImmediate (node:internal/timers:466:21)
2023-08-01 13:49:19.976 [error] [golang.go] provider FAILED
2023-08-01 13:49:19.976 [error] Error: semantictokens are disabled
	at handleResponse (/home/joshuaring/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:2126:40)
	at handleMessage (/home/joshuaring/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:1936:11)
	at processMessageQueue (/home/joshuaring/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:1951:13)
	at Immediate.<anonymous> (/home/joshuaring/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:1927:11)
	at process.processImmediate (node:internal/timers:466:21)
2023-08-01 13:49:20.101 [error] [golang.go] provider FAILED
2023-08-01 13:49:20.101 [error] Error: semantictokens are disabled
	at handleResponse (/home/joshuaring/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:2126:40)
	at handleMessage (/home/joshuaring/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:1936:11)
	at processMessageQueue (/home/joshuaring/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:1951:13)
	at Immediate.<anonymous> (/home/joshuaring/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:1927:11)
	at process.processImmediate (node:internal/timers:466:21)
2023-08-01 13:49:21.662 [error] [golang.go] provider FAILED
2023-08-01 13:49:21.662 [error] Error: context canceled
	at handleResponse (/home/joshuaring/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:2126:40)
	at handleMessage (/home/joshuaring/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:1936:11)
	at processMessageQueue (/home/joshuaring/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:1951:13)
	at Immediate.<anonymous> (/home/joshuaring/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:1927:11)
	at process.processImmediate (node:internal/timers:466:21)
2023-08-01 13:49:21.663 [error] [golang.go] provider FAILED
2023-08-01 13:49:21.663 [error] Error: semantictokens are disabled
	at handleResponse (/home/joshuaring/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:2126:40)
	at handleMessage (/home/joshuaring/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:1936:11)
	at processMessageQueue (/home/joshuaring/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:1951:13)
	at Immediate.<anonymous> (/home/joshuaring/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:1927:11)
	at process.processImmediate (node:internal/timers:466:21)
2023-08-01 13:49:21.811 [error] [golang.go] provider FAILED
2023-08-01 13:49:21.811 [error] Error: semantictokens are disabled
	at handleResponse (/home/joshuaring/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:2126:40)
	at handleMessage (/home/joshuaring/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:1936:11)
	at processMessageQueue (/home/joshuaring/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:1951:13)
	at Immediate.<anonymous> (/home/joshuaring/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:1927:11)
	at process.processImmediate (node:internal/timers:466:21)
</details>

**Comment by Josh-Ring-SD** [comment]
I do still have access to that user yes.

Open to any suggestions I ran out of ideas honestly

**Comment by findleyr** [comment]
It sounds like something was broken in your go environment (via `go env -w`, perhaps?). We'd need full LSP logs (including RPCs) to determine this, not just the extension host logs (as described at https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md#collect-gopls-information).

Given that this appears to be some sort of isolated environment corruption, it may not be worth tracking down.

**Comment by Josh-Ring-SD** [comment]
> It sounds like something was broken in your go environment (via `go env -w`, perhaps?). We'd need full LSP logs (including RPCs) to determine this, not just the extension host logs (as described at https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md#collect-gopls-information).
> 
> Given that this appears to be some sort of isolated environment corruption, it may not be worth tracking down.

I could not recover the environment despite resetting everything I could find, I threw in the towel here

**Comment by andremelinski** [comment]
I had to delete my go.mod and create a new one (idk why).. setup golang is vscode looks like magic

**Comment by annybs** [comment]
I'm late to this party, but I had a similar problem as @Josh-Ring-SD this week.

I created a Go workspace that worked fine on my MacBook, but then I experienced the same issue as OP when I cloned it to my Ubuntu workstation:

> This file is within module "[...]", which is not included in your workspace.
> To fix this problem, you can add this module to your go.work file ([...]/go.work)
> See the documentation for more information on setting up your workspace:
> https://github.com/golang/tools/blob/master/gopls/doc/workspace.md.

- All typical Go extension options
- No modifications to `gopls` config. Pretty much off-the-shelf usage
- Go installed on my Ubuntu system by extracting the [tar.gz](https://go.dev/dl/) to `$HOME/go`

I experimented with restarting the language server and mucking about with env, with no luck. What clued me in to my issue was that while `GOWORK` referenced my go.work file correctly, `GOMOD` referenced `$HOME/go/src/go.mod` because I had placed my workspace inside of `$HOME/go/src/github.com/my-organisation/my-repository` causing `GOMOD` resolution to reach Go internal source. It seems like this caused `gopls` to override my Go workspace in favour of what it inferred as the root module for my VS Code window.

I figured out there are two solutions to this:

- Run `go mod init` in the workspace root and gitignore the resulting `go.mod` file. This compels gopls to treat your workspace root as the de facto root directory, and sub-packages work fine
- Move the workspace out of `$HOME/go` entirely, e.g. `$HOME/Documents/MyProject`. As long as there is no go.mod file in parent directories, GOMOD resolves to `/dev/null` (or whatever is appropriate for your OS) allowing the Go workspace to take precedence

I'm not sure whether this is a bug or expected behaviour in the VS Code extension or gopls itself, but both have worked for me (and I'm going to stick with the latter!)

**Comment by Kindred87** [comment]
@annybs Was just having this issue today on a fresh Go install with a workspace in an isolated directory.  Compiler had no trouble building workspace sub-module A which imported sub-module B, but the VS Code extension wouldn't provide Intellisense for any of the imported objects.  Running "go mod init t" in the workspace root solved the issue.

@findleyr If you would like to take a look, I removed the go.mod file, restarted the language server, and captured the output in the attached.  

[output.txt](https://github.com/golang/vscode-go/files/13243319/output.txt)

Directory tree, in case that's of use to see the relationships between modules.

![Directory Tree](https://github.com/golang/vscode-go/assets/13651460/95ad14bc-b6b0-4325-9ef7-706bd9b6022f)

**Comment by findleyr** [comment]
@Kindred87 what is the content of your `go.work` file?

**Comment by Kindred87** [comment]
@findleyr 
`go 1.21.3

use (
	./TGB
	./cwb
)`

**Comment by findleyr** [comment]
Sorry for missing the response from @annybs above.

Something is definitely wrong here:

`output.txt`:
```
go/packages.Load #1
	snapshot=0
	directory=file:///C:/Users/Kindred87/OneDrive%20-%20Company/Projects/Project%20Name/code
	query=[C:\Users\Kindred87\OneDrive - Company\Projects\Project Name\code\TGB\... C:\Users\Kindred87\OneDrive - Company\Projects\Project Name\code\cwb\... builtin]
	packages=3
```

`happy_output.txt`:
```
go/packages.Load #1
	snapshot=0
	directory=file:///C:/Users/Kindred87/OneDrive%20-%20Company/Projects/Project%20Name/code
	query=[C:\Users\Kindred87\OneDrive - Company\Projects\Project Name\code\TGB\... C:\Users\Kindred87\OneDrive - Company\Projects\Project Name\code\cwb\... builtin]
	packages=12
```

In other words, it looks like the same query, from the same workspace, is returning different results.

Digging deeper, I found it:

`output.txt`:
```
Params: {"type":3,"message":"2023/11/02 11:27:46 go info for C:\\Users\\Kindred87\\OneDrive - Company\\Projects\\Project Name\\code\n(go dir C:\\Users\\Kindred87\\OneDrive - Company\\Projects\\Project Name)\n(go version go version go1.21.3 windows/amd64)\n(valid build configuration = true)\n(build flags: [])\n(selected go env: [GO111MODULE=, GOCACHE=C:\\Users\\Kindred87\\AppData\\Local\\go-build, GOFLAGS=, GOMODCACHE=C:\\Users\\Kindred87\\go\\pkg\\mod, GOPATH=C:\\Users\\Kindred87\\go, GOPRIVATE=, GOROOT=C:\\Program Files\\Go, GOWORK=C:\\Users\\Kindred87\\OneDrive - Company\\Projects\\Project Name\\code\\go.work])\n\n"}
```

`happy_output.txt`:
```
Params: {"type":3,"message":"2023/11/02 11:42:45 go info for C:\\Users\\Kindred87\\OneDrive - Company\\Projects\\Project Name\\code\n(go dir C:\\Users\\Kindred87\\OneDrive - Company\\Projects\\Project Name\\code)\n(go version go version go1.21.3 windows/amd64)\n(valid build configuration = true)\n(build flags: [])\n(selected go env: [GO111MODULE=, GOCACHE=C:\\Users\\Kindred87\\AppData\\Local\\go-build, GOFLAGS=, GOMODCACHE=C:\\Users\\Kindred87\\go\\pkg\\mod, GOPATH=C:\\Users\\Kindred87\\go, GOPRIVATE=, GOROOT=C:\\Program Files\\Go, GOWORK=C:\\Users\\Kindred87\\OneDrive - Company\\Projects\\Project Name\\code\\go.work])\n\n"}
```

The "go dir" is being computed incorrectly. That logic is here: 
https://cs.opensource.google/go/x/tools/+/master:gopls/internal/lsp/cache/view.go;l=1005;drc=cf5aad9d898a74d0f6cd041af86762f1122b926a

So @Kindred87 can you please confirm that you have a `go.mod` file in `C:\\Users\\Kindred87\\OneDrive - Company\\Projects\\Project Name`? If that is the case, then gopls is expanding the workspace to the wrong directory. Adding another go.mod file truncates the search.

Gopls should instead be truncating that expansion at a go.work file, if present. This is just a bug, though we probably don't hit it that often as `go.mod > go.work` is relatively unlikely. All of this is being rewritten right now in https://go.dev/issue/57979, so I'm not sure if it is worth fixing this bug, which has been present for a long time. Soon gopls will "do the right thing always"...

**Comment by Kindred87** [comment]
Confirming that when ```go.mod```, with the contents
```go
module t

go 1.21.3
```
is in ``` C:\\Users\\Kindred87\\OneDrive - Company\\Projects\\Project Name ```, the same directory that ```go.work``` is in, the happy_output.txt results are produced.

**Comment by findleyr** [comment]
@Kindred87 to be absolutely clear, I think the `go.mod` file must be in `is in C:\\Users\\Kindred87\\OneDrive - Company\\Projects\\Project Name\code` (the `code` subdirectory) in order for this to work as expected.

Do you have a `go.mod` file in `C:\\Users\\Kindred87\\OneDrive - Company\\Projects\\Project Name`, which is the **parent** directory of the directory containing `go.work`? I think you must -- if you can confirm then I believe I understand the bug.

**Comment by Kindred87** [comment]
@findleyr Ah, I understand the distinction.  There was indeed a go.mod file in the parent directory, ```C:\\Users\\Kindred87\\OneDrive - Company\\Projects\\Project Name```, in addition to the one I added to ```code```.  Removing both resolves the issue.

**Comment by quenbyako** [comment]
Hi Guys, third year in a row i got absolutely similar problem.

Here is my error message:

```
This file is within module "../../../../../repositories/mtproto", which is not included in your workspace.
To fix this problem, you can add this module to your go.work file (/Users/quenbyako/repositories/mtproto/go.work)
See the documentation for more information on setting up your workspace:
https://github.com/golang/tools/blob/master/gopls/doc/workspace.md.go list
```

It's **REALLY** confusing and i have no idea what's happening, especially since i adding `go.work` files to **every** top level modules without real purpose or usage of this workspace.

One more important thing to mention: It's always no difference between single root editor (like one folder per window) and multi-root editor (files added via `code --add ./otherpkg`), error is always same: "this file within module ../../../../..(billion times)../.. which is not included in your workspace"

And also: i have **only top level modules**, so there are no submodules or something like this. One module per one root.

@findleyr May i ask you to look at this issue too?

**Comment by findleyr** [comment]
@quenbyako with the recently closed #57979 your workspace layout should be automatically detected. However, this feature has not yet been released.

Could you please try installing gopls@master?

```
git clone https://go.googlesource.com/tools && cd tools/gopls && go install
```

Let us know how it goes.

(as for the most unfunny part: if you are using an editor that automatically detects workspace folders, I suspect that you've opened an outer module before opening a nested module. Most editors will not detect this subdirectory as a logically distinct workspace folder)

**Comment by quenbyako** [comment]
@findleyr Thanks for quick response! Tried it for a whole day, unfortunately it's not helping 😢 

One thing i noticed: for some reason, if i opening file in two different folders, everything starts to die, for example: first opened file is in root, second one is in root also, but related to `package_test` package, third one, for example in sub directory (not in submodule, just a folder)

I wondering how exactly `gopls` looking into the codebase, cause every possible structure, slightly more complex than "one opened file, one root, flat module structure" continuously fails for a looong long time (3-4 years at least)

**Comment by hyangah** [comment]
@quenbyako Can you please open a separate issue and include your workspace structure (including 1. where go.mod files are, 2. where go.work files are and what they have, and 3. gopls traces)? Thanks.
