### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by Liu-Chunhui** [golang/vscode-go#2939]
gopls version: v0.13.1 (go1.20.4)
gopls flags: 
update flags: proxy
extension version: 0.39.1
go version: 1.20.4
environment: Visual Studio Code darwin
initialization error: undefined
issue timestamp: Mon, 14 Aug 2023 01:45:12 GMT
restart history:
Wed, 09 Aug 2023 05:18:59 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: unexpected composite literal type: *github.com/anzx/apis-go/fabric/service/entitlements/v1.AccountPermission

goroutine 1174359 [running]:
golang.org/x/tools/refactor/satisfy.(*Finder).expr(0x140197e23c0, {0x105be9300, 0x140059fe980})
	  find.go:389  0xb9c
golang.org/x/tools/refactor/satisfy.(*Finder).expr(0x140197e23c0, {0x105be9300, 0x140059fe9c0})
	  find.go:384  0xb40
golang.org/x/tools/refactor/satisfy.(*Finder).expr(0x140197e23c0, {0x105be9300, 0x140059feac0})
	  find.go:362  0xd50
golang.org/x/tools/refactor/satisfy.(*Finder).expr(0x140197e23c0, {0x105be9990, 0x1400e016aa0})
	  find.go:469  0x650
golang.org/x/tools/refactor/satisfy.(*Finder).stmt(0x140197e23c0, {0x105be9780%3F, 0x1400e016e60%3F})
	  find.go:573  0xdc0
golang.org/x/tools/refactor/satisfy.(*Finder).stmt(0x140197e23c0, {0x105be91e0%3F, 0x140190b5a10%3F})
	  find.go:588  0xc74
golang.org/x/tools/refactor/satisfy.(*Finder).Find(0x140197e23c0, 0x1401864ee60%3F, {0x14019790600, 0x21, 0x0%3F})
	  find.go:106  0x1f8
golang.org/x/tools/gopls/internal/lsp/source.(*renamer).satisfy(0x14018a4a700)
	  rename_check.go:836  0xbc
golang.org/x/tools/gopls/internal/lsp/source.(*renamer).checkMethod(0x14018a4a700, 0x1400b47e300)
	  rename_check.go:753  0x2c8
golang.org/x/tools/gopls/internal/lsp/source.(*renamer).check(0x14018a4a700, {0x105bf33f8, 0x1400b47e300})
	  rename_check.go:105  0x164
golang.org/x/tools/gopls/internal/lsp/source.renameObjects({0x140185e10c0%3F, 0x140195a75a8%3F}, {0x18%3F, 0x104f78700%3F}, {0x140181aa900, 0x21}, {0x105bf0be8, 0x140196af2e0}, {0x140196af490, 0x1, ...})
	  rename.go:1031  0x228
golang.org/x/tools/gopls/internal/lsp/source.renameExported({0x105bea968, 0x140182a5350}, {0x105bf7470, 0x14006c32420}, {0x14018ef9da0, 0x2, 0x105bb8780%3F}, {0x1400a4a13b0, 0x30}, {0x140195a75a8, ...}, ...)
	  rename.go:608  0x188
golang.org/x/tools/gopls/internal/lsp/source.renameOrdinary({0x105bea968, 0x140182a5350}, {0x105bf7470, 0x14006c32420}, {0x105beb800, 0x14015606840}, {0x185e14f8%3F, 0x140%3F}, {0x140181aa900, 0x21})
	  rename.go:448  0x748
golang.org/x/tools/gopls/internal/lsp/source.Rename({0x105bea968%3F, 0x140182a5200%3F}, {0x105bf7470, 0x14006c32420}, {0x105beb800, 0x14015606840}, {0x10855ad0%3F, 0x140%3F}, {0x140181aa900, 0x21})
	  rename.go:234  0x120
golang.org/x/tools/gopls/internal/lsp.(*Server).rename(0x140180e8bc0%3F, {0x105bea8c0, 0x1401598b950}, 0x140180e8bc0)
	  rename.go:29  0x1a4
golang.org/x/tools/gopls/internal/lsp.(*Server).Rename(0x14013a37e10%3F, {0x105bea8c0%3F, 0x1401598b950%3F}, 0x105a6ed40%3F)
	  server_gen.go:216  0x24
golang.org/x/tools/gopls/internal/lsp/protocol.serverDispatch({0x105bea8c0, 0x1401598b950}, {0x105bfa3e8, 0x1400042cc40}, 0x140182a5110, {0x105beab98, 0x14018121400})
	  tsserver.go:537  0xb6c
golang.org/x/tools/gopls/internal/lsp/protocol.ServerHandler.func1({0x105bea8c0, 0x1401598b950}, 0x140182a5110, {0x105beab98, 0x14018121400})
	  protocol.go:157  0x6c
golang.org/x/tools/gopls/internal/lsp/lsprpc.handshaker.func1({0x105bea8c0, 0x1401598b950}, 0x140182a5110, {0x105beab98%3F, 0x14018121400%3F})
	  lsprpc.go:519  0x768
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1({0x105bea8c0, 0x1401598b950}, 0x14015a21ba8, {0x105beab98%3F, 0x14018121400%3F})
	  handler.go:35  0xf0
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2()
	  handler.go:103  0x90
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x1dc
[Error - 11:44:55] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by smyrman** [comment]
I get the same error for go1.21:

---

gopls version: v0.13.1 (go1.21.0)
gopls flags: 
update flags: proxy
extension version: 0.39.1
go version: 1.21.0
environment: Visual Studio Code darwin
initialization error: undefined
issue timestamp: Mon, 14 Aug 2023 13:36:16 GMT
restart history:
Mon, 14 Aug 2023 08:30:12 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: unexpected composite literal type: *cloud.google.com/go/bigquery.FieldSchema

goroutine 264091 [running]:
golang.org/x/tools/refactor/satisfy.(*Finder).expr(0xc014f61e30, {0x100d66eb0, 0xc0067a7f80})
	  find.go:389  0xd94
golang.org/x/tools/refactor/satisfy.(*Finder).expr(0xc014f61e30, {0x100d66eb0, 0xc01874c100})
	  find.go:384  0xd1d
golang.org/x/tools/refactor/satisfy.(*Finder).valueSpec(0xc014f61e30, 0xc00fffedc0)
	  find.go:249  0x1a5
golang.org/x/tools/refactor/satisfy.(*Finder).Find(0xc014f61e30, 0xc00de35f40%3F, {0xc00b7ff280, 0xa, 0x0%3F})
	  find.go:99  0x25b
golang.org/x/tools/gopls/internal/lsp/source.(*renamer).satisfy(0xc00169bf80)
	  rename_check.go:836  0xc9
golang.org/x/tools/gopls/internal/lsp/source.(*renamer).checkMethod(0xc00169bf80, 0xc00a93f7a0)
	  rename_check.go:753  0x3ac
golang.org/x/tools/gopls/internal/lsp/source.(*renamer).check(0xc00169bf80, {0x100d71b78, 0xc00a93f7a0})
	  rename_check.go:105  0x165
golang.org/x/tools/gopls/internal/lsp/source.renameObjects({0xc00d8bfc00%3F, 0x100a76120%3F}, {0x100d68668%3F, 0xc01f653200%3F}, {0xc01647b5a0, 0xc}, {0x100d6f270, 0xc006b49f10}, {0xc01b38cdb0, 0x1, ...})
	  rename.go:1031  0x25f
golang.org/x/tools/gopls/internal/lsp/source.renameExported({0x100d68668, 0xc00b062630}, {0x100d76130, 0xc007227ce0}, {0xc00f551000, 0x74, 0x100ada019%3F}, {0xc0014aa190, 0x21}, {0xc00ac7f990, ...}, ...)
	  rename.go:608  0x259
golang.org/x/tools/gopls/internal/lsp/source.renameOrdinary({0x100d68668, 0xc00b062630}, {0x100d76130, 0xc007227ce0}, {0x100d69788, 0xc0095fc240}, {0x9bbca0%3F, 0x1%3F}, {0xc01647b5a0, 0xc})
	  rename.go:448  0x8c8
golang.org/x/tools/gopls/internal/lsp/source.Rename({0x100d68668%3F, 0xc00b0624e0%3F}, {0x100d76130, 0xc007227ce0}, {0x100d69788, 0xc0095fc240}, {0x16bf27a8%3F, 0xc0%3F}, {0xc01647b5a0, 0xc})
	  rename.go:234  0x1c5
golang.org/x/tools/gopls/internal/lsp.(*Server).rename(0x1009466a0%3F, {0x100d686a0, 0xc00f393040}, 0xc006d7ce80)
	  rename.go:29  0x22f
golang.org/x/tools/gopls/internal/lsp.(*Server).Rename(0xc00e4ead80%3F, {0x100d686a0%3F, 0xc00f393040%3F}, 0x1009466a0%3F)
	  server_gen.go:216  0x1d
golang.org/x/tools/gopls/internal/lsp/protocol.serverDispatch({0x100d686a0, 0xc00f393040}, {0x100d79cd0, 0xc0002e41c0}, 0xc00b0623f0, {0x100d68860, 0xc0182b2340})
	  tsserver.go:537  0xd5a
golang.org/x/tools/gopls/internal/lsp/lsprpc.(*StreamServer).ServeStream.ServerHandler.func3({0x100d686a0, 0xc00f393040}, 0xc00b0623f0, {0x100d68860, 0xc0182b2340})
	  protocol.go:157  0x7e
golang.org/x/tools/gopls/internal/lsp/lsprpc.(*StreamServer).ServeStream.handshaker.func4({0x100d686a0, 0xc00f393040}, 0xc00b0623f0, {0x100d68860%3F, 0xc0182b2340%3F})
	  lsprpc.go:519  0x923
golang.org/x/tools/gopls/internal/lsp/protocol.Handlers.MustReplyHandler.func1({0x100d686a0, 0xc00f393040}, 0xc0104b1338, {0x100d68860%3F, 0xc0182b2340%3F})
	  handler.go:35  0xe5
golang.org/x/tools/gopls/internal/lsp/protocol.Handlers.AsyncHandler.func2.2()
	  handler.go:103  0x96
created by golang.org/x/tools/gopls/internal/lsp/protocol.Handlers.AsyncHandler.func2 in goroutine 129
	  handler.go:100  0x1ed
[Error - 3:36:06 PM] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment]
Yes, this is a dupe of https://go.dev/issue/61813; thank you for investigating.

The fix is in gopls@v0.13.2-pre.1, which we're releasing shortly.
