### ISSUE TITLE
Request textDocument/semanticTokens/range failed - semantictokens are disabled

### ISSUE THREAD

**Issue by lucasgrvarela** [golang/vscode-go#3005]
On Output for "gopls (server)"
```
[Error - 11:13:36 PM] Request textDocument/semanticTokens/range failed.
  Message: semantictokens are disabled
```

On VSCode Developer Tools
```
  ERR semantictokens are disabled: Error: semantictokens are disabled
	at handleResponse (/home/lucas/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:2126:40)
	at handleMessage (/home/lucas/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:1936:11)
	at processMessageQueue (/home/lucas/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:1951:13)
	at Immediate.<anonymous> (/home/lucas/.vscode/extensions/golang.go-0.39.1/dist/goMain.js:1927:11)
	at process.processImmediate (node:internal/timers:476:21)
```

Versions
```
$ go version
go version go1.21.3 linux/amd64

$ gopls -v version
Build info
----------
golang.org/x/tools/gopls v0.13.2
    golang.org/x/tools/gopls@v0.13.2 h1:Pyvx6MKvatbX3zzZmdGiFRfQZl0ohPlt2sFxO/5j6Ro=
    github.com/BurntSushi/toml@v1.2.1 h1:9F2/+DoOYIOksmaJFPw1tGFy1eDnIJXg+UHjuD8lTak=
    github.com/google/go-cmp@v0.5.9 h1:O2Tfq5qg4qc4AmwVlvv0oLiVAGB7enBSJ2x2DqQFi38=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/exp@v0.0.0-20220722155223-a9213eeb770e h1:+WEEuIdZHnUeJJmEUjyYC2gfUMj69yZXw17EnHg/otA=
    golang.org/x/exp/typeparams@v0.0.0-20221212164502-fae10dda9338 h1:2O2DON6y3XMJiQRAS1UWU+54aec2uopH3x7MAiqGW6Y=
    golang.org/x/mod@v0.12.0 h1:rmsUpXtvNzj340zd98LZ4KntptpfRHwpFOHG188oHXc=
    golang.org/x/sync@v0.3.0 h1:ftCYgMx6zT/asHUrPw8BLLscYtGznsLAnjq5RH9P66E=
    golang.org/x/sys@v0.10.0 h1:SqMFp9UcQJZa+pmYuAKjd9xq1f0j5rLcDIk0mj4qAsA=
    golang.org/x/text@v0.11.0 h1:LAntKIrcmeSKERyiOh0XMV39LXS8IE9UL2yP7+f5ij4=
    golang.org/x/tools@v0.11.2-0.20230810185051-cc6b5804b8cf h1:Oush7UwPamr2/iNeNFBuNFj89YyHn0YY69EKDdvANnk=
    golang.org/x/vuln@v0.0.0-20230110180137-6ad3e3d07815 h1:A9kONVi4+AnuOr1dopsibH6hLi1Huy54cbeJxnq4vmU=
    honnef.co/go/tools@v0.4.2 h1:6qXr+R5w+ktL5UkwEbPp+fEvfyoMPche6GkOpGHZcLc=
    mvdan.cc/gofumpt@v0.4.0 h1:JVf4NN1mIpHogBj7ABpgOyZc65/UUOkKQFkoURsz4MM=
    mvdan.cc/xurls/v2@v2.4.0 h1:tzxjVAj+wSBmDcF6zBB7/myTy3gX9xvi8Tyr28AuQgc=
go: go1.21.3

$ code -v
1.83.1
f1b07bd25dfad64b0167beb15359ae573aecd2cc
x64
```

Settings.json that interact with Gopls
```
"editor.semanticHighlighting.enabled": true,
```

The bug is not affecting anything on my workflow but I realized this error message on the logs of gopls server when checking the gopls output inside vscode.

Screenshot below
![image](https://github.com/golang/vscode-go/assets/37870368/6feb7310-acd5-439f-b347-c670c184cfdd)

**Comment by lucasgrvarela** [comment]
Ok, defining this setting below fixed the issue because now semantic token is enabled ...

```
    "gopls": {
        "ui.semanticTokens": true
    },
```

**Comment by rahulkarmore** [comment]
Hey @lucasgrvarela, 
I made the changes you suggested and it worked for a while, but after restarting VS Code, the error recurred.

**Comment by sagitarriuss** [comment]
It is working for me, even after restarting VS Code.
