### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by opsanatoliy** [golang/vscode-go#3021]
gopls version: v0.13.2 (go1.21.0)
gopls flags: 
update flags: proxy
extension version: 0.39.1
go version: 1.21.3
environment: Visual Studio Code darwin
initialization error: undefined
issue timestamp: Mon, 23 Oct 2023 12:40:27 GMT
restart history:
Mon, 23 Oct 2023 12:08:39 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x100ff9084]

goroutine 897 [running]:
golang.org/x/tools/gopls/internal/lsp/cache.localPackageKey({{0x140005245d0, 0x17}, {0x140005245d0, 0x17}, {0x140004e4ab0, 0x5}, {0x140003fe000, 0x1, 0x1}, {0x140003fe020, ...}, ...})
	  check.go:1402  0x554
golang.org/x/tools/gopls/internal/lsp/cache.(*packageHandleBuilder).buildPackageHandle(0x1400139a060, {0x10155dcc0, 0x140000e11d0}, 0x140000e0820)
	  check.go:1090  0x234
golang.org/x/tools/gopls/internal/lsp/cache.(*snapshot).getPackageHandles.func2.1()
	  check.go:891  0xb0
golang.org/x/sync/errgroup.(*Group).Go.func1()
	  errgroup.go:75  0x58
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1033
	  errgroup.go:72  0x98
[Error - 14:40:21] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by adonovan** [comment]
There are a number of  overlapping things here but the primary cause is missing error checks when converting from go list output to types.Sizes (and the logic has changed but there are different errors in both the old and the new logic).

The crash can be readily reproduced (in v0.13.2 and on master) by giving a bad GOARCH:
```
xtools$ git checkout gopls/v0.13.2
xtools$ go build -o x ./gopls
xtools$ GOARCH=386x ./x references  ~/w/xtools/go/packages/golist.go:#5171
...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1054dcc84]

goroutine 176 [running]:
golang.org/x/tools/gopls/internal/lsp/cache.localPackageKey({{0x140005c4320, 0x44}, {0x1400062e0c0, 0x5c}, {0x0, 0x0}, {0x140006b4860, 0x1, 0x1}, {0x140006b4880, ...}, ...})
    /Users/adonovan/w/xtools/gopls/internal/lsp/cache/check.go:1402 +0x554
golang.org/x/tools/gopls/internal/lsp/cache.(*packageHandleBuilder).buildPackageHandle(0x140003704b0, {0x105a42060, 0x1400013c460}, 0x1400013c410)
    /Users/adonovan/w/xtools/gopls/internal/lsp/cache/check.go:1090 +0x234
golang.org/x/tools/gopls/internal/lsp/cache.(*snapshot).getPackageHandles.func2.1()
    /Users/adonovan/w/xtools/gopls/internal/lsp/cache/check.go:891 +0xb0
golang.org/x/sync/errgroup.(*Group).Go.func1()
    /Users/adonovan/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75 +0x58
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1
    /Users/adonovan/go/pkg/mod/golang.org/x/sync@v0.3.0/errgroup/errgroup.go:72 +0x98
xtools$ 
```
Fix (for tip) pending. I don't intend to fix v0.13.2.
