### ISSUE TITLE
Saving actions (and debugging) very  slow. Maybe Clam AV

### ISSUE THREAD

**Issue by paulgmiller** [golang/vscode-go#3224]
Type: <b>Bug</b>

Not really sure I can reproduce. This is an azure cloud vm I am using to build golang code and it worked fine for years but started breaking sometime in jan/feb. 

When I pull up the developers tool console I see alot of extension host timeouts
```
INFO [remote-connection][ExtensionHost][56d8f…][reconnect] received socket timeout event (unacknowledgedMsgCount: 1680, timeSinceOldestUnacknowledgedMsg: 20014, timeSinceLastReceivedSomeData: 20014).
log.ts:417  INFO [remote-connection][ExtensionHost][56d8f…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
log.ts:417  INFO [remote-connection][ExtensionHost][56d8f…][reconnect] resolving connection...
log.ts:417  INFO [remote-connection][Extensio
```
and when I try and profile the extension that also fails. 
```
INFO [remote-connection][ExtensionHost][56d8f…][reconnect] received socket timeout event (unacknowledgedMsgCount: 1680, timeSinceOldestUnacknowledgedMsg: 20014, timeSinceLastReceivedSomeData: 20014).
log.ts:417  INFO [remote-connection][ExtensionHost][56d8f…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
log.ts:417  INFO [remote-connection][ExtensionHost][56d8f…][reconnect] resolving connection...
log.ts:417  INFO [remote-connection][Extensio
```

There is a clamav virus scanner installed on this machine by policy I don't have much control over. 

I'm paul.miller@gmail.com and work at microsoft if you want to reach out. 

Extension version: 0.41.1
VS Code version: Code 1.86.2 (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:40:56.878Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.0-1037-azure
Remote OS version: Linux x64 5.15.0-1037-azure
Remote OS version: Linux x64 5.15.0-1037-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600G with Radeon Graphics          (12 x 3893)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.41GB (19.51GB free)|
|Process Argv|--crash-reporter-id 4b3d1f6b-7cbf-4829-9cc0-82229b2a4c7b|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: millercloud|
|OS|Linux x64 5.15.0-1037-azure|
|CPUs|AMD EPYC 7763 64-Core Processor (16 x 2445)|
|Memory (System)|62.80GB (53.58GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: millercloud|
|OS|Linux x64 5.15.0-1037-azure|
|CPUs|AMD EPYC 7763 64-Core Processor (16 x 2445)|
|Memory (System)|62.80GB (53.58GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: millercloud|
|OS|Linux x64 5.15.0-1037-azure|
|CPUs|AMD EPYC 7763 64-Core Processor (16 x 2445)|
|Memory (System)|62.80GB (53.58GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww1:30959800
cppperfcontrol:30979541
d34g3935:30971562
edj9j583:30969295
fegfb526:30973843
bg6jg535:30979843
78248357:30976999
dsvsc020:30976470

```

</details>

**Comment by paulgmiller** [comment]
After many connection resets ther are some failures but I can't really profile because that gets an error as above.

```
workbench.desktop.main.js:sourcemap:655   ERR Canceled: Canceled
    at Object.w [as $6] (vscode-file://vscode-app/c:/Users/pmiller/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:11:1032)
    at vscode-file://vscode-app/c:/Users/pmiller/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1590:10800
    at Array.forEach (<anonymous>)
    at m.dispose (vscode-file://vscode-app/c:/Users/pmiller/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1590:10738)
    at s.dispose (vscode-file://vscode-app/c:/Users/pmiller/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1590:22710)
    at Y.yb (vscode-file://vscode-app/c:/Users/pmiller/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2751:1126)
    at Y.yb (vscode-file://vscode-app/c:/Users/pmiller/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2751:9202)
    at Y.xb (vscode-file://vscode-app/c:/Users/pmiller/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2751:860)
    at a.value (vscode-file://vscode-app/c:/Users/pmiller/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2751:420)
    at o.y (vscode-file://vscode-app/c:/Users/pmiller/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at o.fire (vscode-file://vscode-app/c:/Users/pmiller/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2119)
    at n.D (vscode-file://vscode-app/c:/Users/pmiller/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1590:7202)
    at a.value (vscode-file://vscode-app/c:/Users/pmiller/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1590:6613)
    at o.y (vscode-file://vscode-app/c:/Users/pmiller/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at o.fire (vscode-file://vscode-app/c:/Users/pmiller/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2119)
    at s.fire (vscode-file://vscode-app/c:/Users/pmiller/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:628:14470)
    at f.acceptDisconnect (vscode-file://vscode-app/c:/Users/pmiller/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:628:17219)
    at U (vscode-file://vscode-app/c:/Users/pmiller/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:688:23317)
    at F.D (vscode-file://vscode-app/c:/Users/pmiller/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:688:22908)
    at F.C (vscode-file://vscode-app/c:/Users/pmiller/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:688:22832)
    at F.z (vscode-file://vscode-app/c:/Users/pmiller/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:688:21227)
    at async F.y (vscode-file://vscode-app/c:/Users/pmiller/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:688:19839)
workbench.desktop.main.js:sourcemap:655   ERR Extension host (Remote) terminated unexpectedly with code null.
workbench.desktop.main.js:sourcemap:655   ERR Extension host (Remote) terminated unexpectedly. The following extensions were running: vscode.emmet, golang.go, vscode.git-base, redhat.vscode-yaml, vscode.git, vscode.github, 42Crunch.vscode-openapi, vscode.debug-auto-launch, vscode.merge-conflict, ecmel.vscode-html-css, vscode.npm, vscode
```

**Comment by paulgmiller** [comment]
Hmmm sorry this should maybe goto vscode itself. and I can't repro so far after uninstalling vscode from remote machine and reinstalling  We'll see what tommorow brings
