### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by yavuzyurtbegendi** [golang/vscode-go#3231]
panic: nil metadata for "github.com/mailru/easyjson/easyjson [command-line-arguments.test]"

goroutine 17198 [running]:
golang.org/x/tools/gopls/internal/cache.(*Snapshot).getPackageHandles.func1(0x1400f59ba40, {0x1400d165900, 0x41})
	/Users/yavuzyurtbegendi/go/pkg/mod/golang.org/x/tools/gopls@v0.15.1/internal/cache/check.go:872 +0x53c
golang.org/x/tools/gopls/internal/cache.(*Snapshot).getPackageHandles.func1(0x0, {0x14008832000, 0x7a})
	/Users/yavuzyurtbegendi/go/pkg/mod/golang.org/x/tools/gopls@v0.15.1/internal/cache/check.go:889 +0x468
golang.org/x/tools/gopls/internal/cache.(*Snapshot).getPackageHandles(0x1400c2d77a0, {0x102f7b168, 0x140140b05d0}, {0x14010965610, 0x1, 0x0?})
	/Users/yavuzyurtbegendi/go/pkg/mod/golang.org/x/tools/gopls@v0.15.1/internal/cache/check.go:899 +0x17c
golang.org/x/tools/gopls/internal/cache.(*Snapshot).forEachPackage(0x102f7b1a0?, {0x102f7b168, 0x140140b0420}, {0x14010965610, 0x1, 0x1}, 0x1028162e0?, 0x1400c2d77e8?)
	/Users/yavuzyurtbegendi/go/pkg/mod/golang.org/x/tools/gopls@v0.15.1/internal/cache/check.go:343 +0x134
golang.org/x/tools/gopls/internal/cache.(*Snapshot).PackageDiagnostics(0x14008832000?, {0x102f7b1a0?, 0x1400b59d400?}, {0x14010965610, 0x1, 0x1})
	/Users/yavuzyurtbegendi/go/pkg/mod/golang.org/x/tools/gopls@v0.15.1/internal/cache/snapshot.go:686 +0x1b0
golang.org/x/tools/gopls/internal/cache.(*Snapshot).orphanedFileDiagnostics(0x1400c2d77a0, {0x102f7b1a0, 0x1400b59d400}, {0x1401dc9bf40, 0x4, 0x10288c630?})
	/Users/yavuzyurtbegendi/go/pkg/mod/golang.org/x/tools/gopls@v0.15.1/internal/cache/snapshot.go:1452 +0x1c8
golang.org/x/tools/gopls/internal/cache.(*Session).OrphanedFileDiagnostics(0x1400043e150, {0x102f7b1a0, 0x1400b59d400})
	/Users/yavuzyurtbegendi/go/pkg/mod/golang.org/x/tools/gopls@v0.15.1/internal/cache/session.go:1165 +0x464
golang.org/x/tools/gopls/internal/server.(*server).diagnoseChangedViews(0x14000374000, {0x102f7b1a0, 0x1400b59d400}, 0x4, 0x140001b4d98?, 0x0)
	/Users/yavuzyurtbegendi/go/pkg/mod/golang.org/x/tools/gopls@v0.15.1/internal/server/diagnostics.go:157 +0x504
golang.org/x/tools/gopls/internal/server.(*server).didModifyFiles.func2()
	/Users/yavuzyurtbegendi/go/pkg/mod/golang.org/x/tools/gopls@v0.15.1/internal/server/text_synchronization.go:269 +0x3c
created by golang.org/x/tools/gopls/internal/server.(*server).didModifyFiles in goroutine 115
	/Users/yavuzyurtbegendi/go/pkg/mod/golang.org/x/tools/gopls@v0.15.1/internal/server/text_synchronization.go:268 +0x4c0
[Error - 11:09:17]

**Comment by findleyr** [comment]
Thank you for reporting. This looks like a dupe of https://github.com/golang/go/issues/66109, which is fixed in master.

We'll be cutting a prerelease with the fix soon (today or tomorrow). If you want to test the fix now, you can install from master as follows:

```
git clone https://go.googlesource.com/tools
cd tools/gopls
go install
```

Otherwise, I'll ping this bug once the prerelease is out for testing. Would appreciate confirmation that this fixes the bug for you.
