### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by liumingmin** [golang/vscode-go#3234]
gopls version: v0.15.1 (go1.20.13)
gopls flags: 
update flags: proxy
extension version: 0.39.1
go version: 1.21.6
environment: Visual Studio Code win32
initialization error: undefined
issue timestamp: Fri, 08 Mar 2024 06:09:49 GMT
restart history:
Fri, 08 Mar 2024 02:16:19 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: invalid Go version "go1.21.6" (should be something like "go1.12")

goroutine 9724 [running]:
go/types.NewChecker(0xc000bb7950%3F, 0xc006eb10c0, 0xc008a6f360, 0x7%3F)
	  check.go:237  0x24e
golang.org/x/tools/gopls/internal/cache.(*typeCheckBatch).checkPackageForImport(0xc0091a0a20, {0x111aa38, 0xc009654180}, 0xc0021f7b00)
	  check.go:702  0x4df
golang.org/x/tools/gopls/internal/cache.(*typeCheckBatch).getImportPackage(0xc0091a0a20, {0x111aa38, 0xc009654180}, {0xc000bb7950, 0x2f})
	  check.go:469  0x767
golang.org/x/tools/gopls/internal/cache.(*Snapshot).forEachPackageInternal.func1()
	  check.go:396  0x2d
golang.org/x/sync/errgroup.(*Group).Go.func1()
	  errgroup.go:78  0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	  errgroup.go:75  0xa5
[Error - 10:16:36] </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment]
Thank you for attaching the panicking stack. We should try to fix this for our next patch release (scheduled for Monday).

**Comment by findleyr** [comment]
(I should note, this may be fixed by upgrading to Go 1.22).
