### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by dougmendes** [golang/vscode-go#3275]
gopls version: v0.15.2/go1.19.2
gopls flags: 
update flags: proxy
extension version: 0.41.2
environment: Visual Studio Code darwin
initialization error: undefined
issue timestamp: Fri, 22 Mar 2024 12:59:44 GMT
restart history:
Fri, 22 Mar 2024 12:59:34 GMT: activation (enabled: true)
Fri, 22 Mar 2024 12:59:44 GMT: installation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: invalid Go version "go1.22.1" (should be something like "go1.12")

goroutine 3367 [running]:
go/types.NewChecker(0x1400021fa78%3F, 0x1400015fc00, 0x140032819a0, 0x0%3F)
	  check.go:240  0x1e8
golang.org/x/tools/gopls/internal/cache.(*analysisNode).typeCheck(0x14001148840, {0x140046e5ac0, 0x1, 0x1})
	  analysis.go:1028  0x5f8
golang.org/x/tools/gopls/internal/cache.(*analysisNode).run(0x14001148840, {0x1010b3120, 0x14002245f80})
	  analysis.go:810  0xa0
golang.org/x/tools/gopls/internal/cache.(*analysisNode).runCached(0x14001148840, {0x1010b3120%3F, 0x14002245f80})
	  analysis.go:672  0x11c
golang.org/x/tools/gopls/internal/cache.(*Snapshot).Analyze.func6.1()
	  analysis.go:398  0xa4
golang.org/x/sync/errgroup.(*Group).Go.func1()
	  errgroup.go:78  0x5c
created by golang.org/x/sync/errgroup.(*Group).Go
	  errgroup.go:75  0xa4
</pre>

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 3,
    "TestdataFiles": 0,
    "GoFiles": 1,
    "ModFiles": 1,
    "Dirs": 1
  },
  "GOARCH": "arm64",
  "GOOS": "darwin",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.22.1",
  "GoplsVersion": "v0.15.2",
  "InitialWorkspaceLoadDuration": "458.566042ms",
  "MemStats": {
    "HeapAlloc": 21558400,
    "HeapInUse": 33488896,
    "TotalAlloc": 275859912
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 1402,
      "Largest": 395026,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.22.1",
        "AllPackages": {
          "Packages": 246,
          "LargestPackage": 155,
          "CompiledGoFiles": 1398,
          "Modules": 19
        },
        "WorkspacePackages": {
          "Packages": 1,
          "LargestPackage": 1,
          "CompiledGoFiles": 1,
          "Modules": 1
        },
        "Diagnostics": 1
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by suzmue** [comment]
Duplicate of #3276
