### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by edp1096** [golang/vscode-go#3361]
gopls version: v0.15.3/go1.22.1
gopls flags: 
update flags: proxy
extension version: 2024.4.1916
environment: Visual Studio Code win32
initialization error: undefined
issue timestamp: Wed, 24 Apr 2024 06:26:05 GMT
restart history:
Wed, 24 Apr 2024 06:26:04 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: runtime error: slice bounds out of range [:-1]

goroutine 689 [running]:
golang.org/x/tools/gopls/internal/protocol.(*Mapper).LineCol8Position(0xc0001069c0, 0x1, 0x0)
	  mapper.go:151  0x1ad
golang.org/x/tools/gopls/internal/cache.goPackagesErrorDiagnostics.func1({{0x0, 0x0}, {0xc000563b60, 0x51}, 0x1}, 0x51%3F, {0x186ffc0, 0xc0005547e0}, {0x1878340, 0xc00044f680})
	  errors.go:58  0x145
golang.org/x/tools/gopls/internal/cache.goPackagesErrorDiagnostics({0x1878340, 0xc00044f680}, {{0x0, 0x0}, {0xc000563b60, 0x51}, 0x1}, 0xc00051fb00, {0x186ffc0, 0xc0005547e0})
	  errors.go:69  0xf5
golang.org/x/tools/gopls/internal/cache.computeLoadDiagnostics({0x1878340, 0xc00044f680}, 0xc0005547e0, 0xc00051fb00)
	  load.go:541  0x185
golang.org/x/tools/gopls/internal/cache.(*packageHandleBuilder).buildPackageHandle(0xc0004ae860, {0x1878340, 0xc00044f680}, 0xc00044e460)
	  check.go:1129  0x2b7
golang.org/x/tools/gopls/internal/cache.(*Snapshot).getPackageHandles.func2.1()
	  check.go:932  0xce
golang.org/x/sync/errgroup.(*Group).Go.func1()
	  errgroup.go:78  0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 688
	  errgroup.go:75  0x96
</pre>

<details><summary>gopls stats -anon</summary>
gopls stats -anon failed after 277 ms. Please check if gopls is killed by OS.
</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by edp1096** [comment]
Sorry
