### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by bakhankov** [golang/vscode-go#3398]
gopls version: v0.15.3/go1.21.6
gopls flags: 
update flags: proxy
extension version: 0.41.4
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Wed, 22 May 2024 10:06:06 GMT
restart history:
Wed, 22 May 2024 10:05:56 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa67e73]

goroutine 12560 [running]:
golang.org/x/tools/gopls/internal/cache.(*analysisNode).typeCheck(0xc002cfe840, {0xc005d8d140, 0x8, 0x8})
	  analysis.go:1078  0xaf3
golang.org/x/tools/gopls/internal/cache.(*analysisNode).run(0xc002cfe840, {0x124c7e8%3F, 0xc00576f350})
	  analysis.go:826  0x206
golang.org/x/tools/gopls/internal/cache.(*analysisNode).runCached(0xc002cfe840, {0x124c7e8%3F, 0xc00576f350})
	  analysis.go:687  0x12d
golang.org/x/tools/gopls/internal/cache.(*Snapshot).Analyze.func6.1()
	  analysis.go:397  0xc9
golang.org/x/sync/errgroup.(*Group).Go.func1()
	  errgroup.go:78  0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 12559
	  errgroup.go:75  0x96
</pre>

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 9626,
    "TestdataFiles": 12,
    "GoFiles": 5599,
    "ModFiles": 2,
    "Dirs": 1498
  },
  "GOARCH": "amd64",
  "GOOS": "linux",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.21.6",
  "GoplsVersion": "v0.15.3",
  "InitialWorkspaceLoadDuration": "1.240260707s",
  "MemStats": {
    "HeapAlloc": 148121704,
    "HeapInUse": 229654528,
    "TotalAlloc": 1659043360
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 5500,
      "Largest": 1654451,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.21.6",
        "AllPackages": {
          "Packages": 1073,
          "LargestPackage": 200,
          "CompiledGoFiles": 5805,
          "Modules": 137
        },
        "WorkspacePackages": {
          "Packages": 244,
          "LargestPackage": 200,
          "CompiledGoFiles": 1101,
          "Modules": 1
        },
        "Diagnostics": 28
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

```

**Comment by hyangah** [comment]
@bakhankov Thanks for the report! 
Is this crash reproducible? In other words, "Go: Restart Go Language Server" or reloading the window doesn't fix the issue?

Transferring to the gopls issue tracker for investigation.

https://github.com/golang/tools/blob/429c9f0c2c0d52afd4862e9734511a94fea841b7/gopls/internal/cache/analysis.go#L1078
