### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by inquestruss** [golang/vscode-go#3477]
gopls version: v0.16.1/go1.22.4
gopls flags: 
update flags: proxy
extension version: 0.42.0
environment: Visual Studio Code linux
initialization error: undefined
issue timestamp: Sun, 04 Aug 2024 16:54:32 GMT
restart history:
Thu, 01 Aug 2024 11:47:06 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: runtime error: slice bounds out of range [3922:3920]

goroutine 111 [running]:
golang.org/x/tools/gopls/internal/template.(*completer).complete(0xc001b6f2c0)
	  completion.go:117  0xd25
golang.org/x/tools/gopls/internal/template.Completion({0xc0017d4980%3F, 0x3f%3F}, 0x8%3F, {0x131d6c0, 0xc0006928a0}, {0x230488%3F, 0xc0%3F}, {0x1, {0x0, 0x0}})
	  completion.go:56  0x308
golang.org/x/tools/gopls/internal/server.(*server).Completion(0xc000002000, {0x131a9b0, 0xc0005acc00}, 0xc001bfaaf0)
	  completion.go:54  0x499
golang.org/x/tools/gopls/internal/protocol.serverDispatch({0x131a9e8, 0xc000484500}, {0x1336050, 0xc000002000}, 0xc0005ac690, {0x131aba8, 0xc000268500})
	  tsserver.go:361  0x2587
golang.org/x/tools/gopls/internal/lsprpc.(*streamServer).ServeStream.ServerHandler.func3({0x131a9e8, 0xc000484500}, 0xc0005ac690, {0x131aba8, 0xc000268500})
	  protocol.go:160  0x85
golang.org/x/tools/gopls/internal/lsprpc.(*streamServer).ServeStream.handshaker.func4({0x131a9e8, 0xc000484500}, 0xc0005ac690, {0x131aba8, 0xc000268500})
	  lsprpc.go:509  0x923
golang.org/x/tools/gopls/internal/protocol.Handlers.MustReplyHandler.func1({0x131a9e8, 0xc000484500}, 0xc000558648, {0x131aba8, 0xc000268500})
	  handler.go:35  0xc6
golang.org/x/tools/gopls/internal/protocol.Handlers.AsyncHandler.func2.2()
	  handler.go:103  0x96
created by golang.org/x/tools/gopls/internal/protocol.Handlers.AsyncHandler.func2 in goroutine 126
	  handler.go:100  0x1c5
</pre>

<details><summary>gopls stats -anon</summary>
{
  "DirStats": {
    "Files": 499,
    "TestdataFiles": 0,
    "GoFiles": 37,
    "ModFiles": 1,
    "Dirs": 235
  },
  "GOARCH": "amd64",
  "GOOS": "linux",
  "GOPACKAGESDRIVER": "",
  "GOPLSCACHE": "",
  "GoVersion": "go1.22.4",
  "GoplsVersion": "v0.16.1",
  "InitialWorkspaceLoadDuration": "1.038147239s",
  "MemStats": {
    "HeapAlloc": 40071888,
    "HeapInUse": 65822720,
    "TotalAlloc": 522628488
  },
  "WorkspaceStats": {
    "Files": {
      "Total": 1323,
      "Largest": 1578502,
      "Errs": 0
    },
    "Views": [
      {
        "GoCommandVersion": "go1.22.4",
        "AllPackages": {
          "Packages": 209,
          "LargestPackage": 161,
          "CompiledGoFiles": 1338,
          "Modules": 30
        },
        "WorkspacePackages": {
          "Packages": 16,
          "LargestPackage": 13,
          "CompiledGoFiles": 55,
          "Modules": 1
        },
        "Diagnostics": 0
      }
    ]
  }
}

</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by hyangah** [comment]
Dup of https://github.com/golang/go/issues/57621

**Comment by hyangah** [comment]
Closing in favor of golang/go#57621
