### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by Rajendro1** [golang/vscode-go#3641]
gopls version: v0.12.2/go1.23.4
gopls flags: 
update flags: proxy
extension version: 0.44.0
environment: Visual Studio Code win32
initialization error: undefined
issue timestamp: Sun, 29 Dec 2024 15:35:33 GMT
restart history:
Sun, 29 Dec 2024 14:50:45 GMT: activation (enabled: true)

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xce78ba]

goroutine 940 [running]:
golang.org/x/tools/gopls/internal/lsp/cache.localPackageKey({{0xc00050d25a, 0x6}, {0xc00050d25a, 0x6}, {0xc00050d410, 0x6}, {0xc0006aa080, 0x1, 0x1}, {0x18caea0, ...}, ...})
	  check.go:1247  0x93a
golang.org/x/tools/gopls/internal/lsp/cache.(*packageHandleBuilder).buildPackageHandle(0xc00056cd20, {0x125e480, 0xc0004a1810}, {0xc00050d25a%3F, 0xc00095d9c0%3F}, 0xc000329200)
	  check.go:929  0x385
golang.org/x/tools/gopls/internal/lsp/cache.(*snapshot).getPackageHandles.func2()
	  check.go:808  0x188
golang.org/x/sync/errgroup.(*Group).Go.func1()
	  errgroup.go:75  0x50
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 939
	  errgroup.go:72  0x96
</pre>

<details><summary>gopls stats -anon</summary>
gopls stats -anon failed after 2329 ms. Please check if gopls is killed by OS.
</details>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by findleyr** [comment]
Hi, please update gopls to the latest version (v0.17.1).

```
go install golang.org/x/tools/gopls@latest
```

This was fixed a while ago (see for example https://github.com/golang/vscode-go/issues/3014).
