### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by jmesyan** [golang/vscode-go#435]
ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.
Error - 6:18:46 PM] Request textDocument/definition failed.
  Message: no identifier found
  Code: 0 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x13dda2a]

goroutine 32121 [running]:
go/types.(*Named).Obj(...)
	/usr/local/go/src/go/types/type.go:473
golang.org/x/tools/internal/lsp/source.pathLinkAndSymbolName(0xc01b4f78c0, 0xc01fa905f0, 0xc00d7c5ec0, 0xc014cc7480, 0x34, 0xc01bf92801, 0x1)
	/usr/local/code/pkg/mod/golang.org/x/tools@v0.0.0-20200727221057-f479e347a516/internal/lsp/source/hover.go:169 +0xa7a
golang.org/x/tools/internal/lsp/source.HoverIdentifier(0x1ab1d20, 0xc01bb8c4b0, 0xc01b4f78c0, 0x0, 0x0, 0x0)
	/usr/local/code/pkg/mod/golang.org/x/tools@v0.0.0-20200727221057-f479e347a516/internal/lsp/source/hover.go:112 +0x261
golang.org/x/tools/internal/lsp/source.Hover(0x1ab1c60, 0xc01d07f580, 0x1ac53c0, 0xc020784f00, 0x1ab5aa0, 0xc008266f00, 0x4045000000000000, 0x403e000000000000, 0x1ab5aa0, 0xc008266f00, ...)
	/usr/local/code/pkg/mod/golang.org/x/tools@v0.0.0-20200727221057-f479e347a516/internal/lsp/source/hover.go:56 +0xde
golang.org/x/tools/internal/lsp.(*Server).hover(0xc00040e600, 0x1ab1c60, 0xc01d07f580, 0xc01c2a2e40, 0x0, 0x0, 0xc0224d4f20)
	/usr/local/code/pkg/mod/golang.org/x/tools@v0.0.0-20200727221057-f479e347a516/internal/lsp/hover.go:24 +0x20b
golang.org/x/tools/internal/lsp.(*Server).Hover(0xc00040e600, 0x1ab1c60, 0xc01d07f580, 0xc01c2a2e40, 0xc01c2a2e40, 0x0, 0x0)
	/usr/local/code/pkg/mod/golang.org/x/tools@v0.0.0-20200727221057-f479e347a516/internal/lsp/server_gen.go:96 +0x49
golang.org/x/tools/internal/lsp/protocol.serverDispatch(0x1ab1c60, 0xc01d07f580, 0x1acc780, 0xc00040e600, 0xc01c2a2e10, 0x1ab1ea0, 0xc01d07f500, 0x0, 0x0, 0x1a9f6e0)
	/usr/local/code/pkg/mod/golang.org/x/tools@v0.0.0-20200727221057-f479e347a516/internal/lsp/protocol/tsserver.go:269 +0x1315
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0x1ab1c60, 0xc01d07f580, 0xc01c2a2e10, 0x1ab1ea0, 0xc01d07f500, 0xbfc071235de04120, 0x6fb12d121)
	/usr/local/code/pkg/mod/golang.org/x/tools@v0.0.0-20200727221057-f479e347a516/internal/lsp/protocol/protocol.go:62 +0xc0
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0x1ab1c60, 0xc01d07f580, 0xc01c2a2e10, 0x1ab1ea0, 0xc01d07f500, 0x0, 0x0)
	/usr/local/code/pkg/mod/golang.org/x/tools@v0.0.0-20200727221057-f479e347a516/internal/lsp/lsprpc/lsprpc.go:521 +0x417
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0x1ab1c60, 0xc01d07f580, 0xc00d1fc520, 0x1ab1ea0, 0xc01d07f500, 0x0, 0xc0000627b8)
	/usr/local/code/pkg/mod/golang.org/x/tools@v0.0.0-20200727221057-f479e347a516/internal/jsonrpc2/handler.go:35 +0xd3
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc00d0a9d40, 0xc01c170720, 0xc000400540, 0x1ab1c60, 0xc01d07f580, 0xc00d1fc520, 0x1ab1ea0, 0xc01d07f500)
	/usr/local/code/pkg/mod/golang.org/x/tools@v0.0.0-20200727221057-f479e347a516/internal/jsonrpc2/handler.go:103 +0x86
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	/usr/local/code/pkg/mod/golang.org/x/tools@v0.0.0-20200727221057-f479e347a516/internal/jsonrpc2/handler.go:100 +0x171
[Error - 6:18:53 PM] Connection to server got closed. Server will not be restarted.
[Error - 6:18:53 PM] Request textDocument/hover failed.
Error: Connection got disposed.
	at Object.dispose (/Users/admin/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/main.js:904:25)
	at Object.dispose (/Users/admin/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-languageclient/lib/client.js:74:35)
	at LanguageClient.handleConnectionClosed (/Users/admin/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-languageclient/lib/client.js:2309:42)
	at LanguageClient.handleConnectionClosed (/Users/admin/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-languageclient/lib/main.js:155:15)
	at closeHandler (/Users/admin/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-languageclient/lib/client.js:2296:18)
	at CallbackList.invoke (/Users/admin/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/Users/admin/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at closeHandler (/Users/admin/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/main.js:240:26)
	at CallbackList.invoke (/Users/admin/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/Users/admin/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at StreamMessageReader.fireClose (/Users/admin/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at Socket.<anonymous> (/Users/admin/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/messageReader.js:151:46)
	at Socket.emit (events.js:208:15)
	at Pipe.<anonymous> (net.js:588:12)

Please attach the stack trace from the crash.
A window with the error message should have popped up in the lower half of your screen.
Please copy the stack trace from that window and paste it in this issue.

<PASTE STACK TRACE HERE>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by stamblerre** [comment]
This should be fixed in the latest `gopls` pre-release - please run the following command to update: `GO111MODULE=on go get golang.org/x/tools/gopls@v0.4.4-pre2`.
