### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by damonallison** [golang/vscode-go#443]
I was editing a file, and needed to restart the language server (which I need to do quite frequently). Unlike most language server restarts, this one prompted me to report it.

```

[Info  - 6:36:31 AM] 2020/07/30 06:36:31 go env for /Users/damon/ateam/go-learn
(valid build configuration = true)
(build flags: [])
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/damon/Library/Caches/go-build"
GOENV="/Users/damon/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY="github.com/shipt/*,github.com/newshipt/*"
GONOSUMDB="github.com/shipt/*,github.com/newshipt/*"
GOOS="darwin"
GOPATH="/Users/damon/go1.14"
GOPRIVATE="github.com/shipt/*,github.com/newshipt/*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/opt/go/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/damon/ateam/go-learn/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/24/72w6m2l95qg55ncjkctb6mdm0000gn/T/go-build519947545=/tmp/go-build -gno-record-gcc-switches -fno-common"


[Info  - 6:36:31 AM] 2020/07/30 06:36:31 go/packages.Load
	snapshot=0
	directory=/Users/damon/ateam/go-learn
	query=[./... builtin]
	packages=32

[Info  - 6:36:34 AM] 2020/07/30 06:36:34 go/packages.Load
	snapshot=5
	package_path="github.com/damonallison/go-learn/language"
	files=[/Users/damon/ateam/go-learn/language/doc.go]

[Info  - 6:36:34 AM] 2020/07/30 06:36:34 go/packages.Load
	snapshot=5
	directory=/Users/damon/ateam/go-learn
	query=[github.com/damonallison/go-learn/language]
	packages=3

[Info  - 6:36:34 AM] 2020/07/30 06:36:34 go/packages.Load
	snapshot=5
	package_path="github.com/damonallison/go-learn/language"
	files=[/Users/damon/ateam/go-learn/language/doc.go /Users/damon/ateam/go-learn/language/const_test.go /Users/damon/ateam/go-learn/language/constants_test.go /Users/damon/ateam/go-learn/language/control_statements_test.go /Users/damon/ateam/go-learn/language/error_test.go /Users/damon/ateam/go-learn/language/functions_test.go /Users/damon/ateam/go-learn/language/low_level_test.go /Users/damon/ateam/go-learn/language/panic_test.go /Users/damon/ateam/go-learn/language/pointers_test.go /Users/damon/ateam/go-learn/language/types_basic_test.go /Users/damon/ateam/go-learn/language/types_custom_test.go]

[Info  - 6:36:34 AM] 2020/07/30 06:36:34 go/packages.Load
	snapshot=5
	package_path="github.com/damonallison/go-learn/language.test"
	files=[/Users/damon/Library/Caches/go-build/c5/c5bddf3a5e5063e885c59f69a4f4c99d23437654a896099a2ee245e9ddadd6d4-d]

[Info  - 6:36:34 AM] 2020/07/30 06:36:34 go/packages.Load
	snapshot=5
	directory=/Users/damon/ateam/go-learn
	query=[file=/Users/damon/ateam/go-learn/language/low_level_test.go]
	packages=1

[Info  - 6:36:34 AM] 2020/07/30 06:36:34 go/packages.Load
	snapshot=5
	package_path="github.com/damonallison/go-learn/language"
	files=[/Users/damon/ateam/go-learn/language/doc.go /Users/damon/ateam/go-learn/language/const_test.go /Users/damon/ateam/go-learn/language/constants_test.go /Users/damon/ateam/go-learn/language/control_statements_test.go /Users/damon/ateam/go-learn/language/error_test.go /Users/damon/ateam/go-learn/language/functions_test.go /Users/damon/ateam/go-learn/language/low_level_test.go /Users/damon/ateam/go-learn/language/panic_test.go /Users/damon/ateam/go-learn/language/pointers_test.go /Users/damon/ateam/go-learn/language/types_basic_test.go /Users/damon/ateam/go-learn/language/types_custom_test.go]

[Error - 6:36:59 AM] Request textDocument/codeAction failed.
  Message: computing fix edits: /Users/damon/ateam/go-learn/language/low_level_test.go:51:79: missing ',' in composite literal
  Code: 0 
[Error - 6:37:00 AM] Request textDocument/codeAction failed.
  Message: computing fix edits: /Users/damon/ateam/go-learn/language/low_level_test.go:51:79: missing ',' in composite literal
  Code: 0 
[Error - 6:37:00 AM] Request textDocument/codeAction failed.
  Message: computing fix edits: /Users/damon/ateam/go-learn/language/low_level_test.go:51:79: missing ',' in composite literal (and 10 more errors)
  Code: 0 
[Error - 6:37:00 AM] 2020/07/30 06:37:00 DocumentSymbols failed: invalid pos
	URI=file:///Users/damon/ateam/go-learn/language/low_level_test.go

[Error - 6:37:01 AM] Request textDocument/codeAction failed.
  Message: computing fix edits: /Users/damon/ateam/go-learn/language/low_level_test.go:51:79: missing ',' in composite literal
  Code: 0 
[Info  - 6:37:02 AM] 2020/07/30 06:37:02 background imports cache refresh starting

[Info  - 6:37:02 AM] 2020/07/30 06:37:02 background refresh finished after 22.504345ms

[Error - 6:37:03 AM] Request textDocument/codeAction failed.
  Message: computing fix edits: /Users/damon/ateam/go-learn/language/low_level_test.go:51:79: missing ',' in composite literal
  Code: 0 
[Error - 6:37:04 AM] Request textDocument/codeAction failed.
  Message: computing fix edits: /Users/damon/ateam/go-learn/language/low_level_test.go:51:79: missing ',' in composite literal
  Code: 0 
[Error - 6:37:04 AM] Request textDocument/codeAction failed.
  Message: computing fix edits: /Users/damon/ateam/go-learn/language/low_level_test.go:51:79: missing ',' in composite literal
  Code: 0 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x13ec3c0]

goroutine 6196 [running]:
golang.org/x/tools/internal/lsp/source.newBuiltinSignature(0x1a686a0, 0xc009699800, 0x1a7a680, 0xc000354000, 0x18ebd7e, 0x6, 0x261cf0f50448fd01, 0xc0050dec00, 0xc0096a1350)
	/Users/damon/go1.14/pkg/mod/golang.org/x/tools@v0.0.0-20200708181441-6004c8539734/internal/lsp/source/types_format.go:82 +0xd0
golang.org/x/tools/internal/lsp/source.builtinSignature(0x1a686a0, 0xc009699800, 0x1a7a680, 0xc000354000, 0xc00267f700, 0x18ebd7e, 0x6, 0x84bc46, 0xc0053db900, 0xc0002e3d40, ...)
	/Users/damon/go1.14/pkg/mod/golang.org/x/tools@v0.0.0-20200708181441-6004c8539734/internal/lsp/source/signature_help.go:140 +0x81
golang.org/x/tools/internal/lsp/source.SignatureHelp(0x1a686a0, 0xc009699800, 0x1a7b6e0, 0xc009454f00, 0x1a6c4a0, 0xc0036ba5a0, 0x4049000000000000, 0x4053c00000000000, 0x0, 0x0, ...)
	/Users/damon/go1.14/pkg/mod/golang.org/x/tools@v0.0.0-20200708181441-6004c8539734/internal/lsp/source/signature_help.go:81 +0x11aa
golang.org/x/tools/internal/lsp.(*Server).signatureHelp(0xc0002f0100, 0x1a685e0, 0xc002571040, 0xc0095f9800, 0x0, 0x0, 0xc0095f0dc0)
	/Users/damon/go1.14/pkg/mod/golang.org/x/tools@v0.0.0-20200708181441-6004c8539734/internal/lsp/signature_help.go:21 +0xf6
golang.org/x/tools/internal/lsp.(*Server).SignatureHelp(0xc0002f0100, 0x1a685e0, 0xc002571040, 0xc0095f9800, 0xc0095f9800, 0x0, 0x0)
	/Users/damon/go1.14/pkg/mod/golang.org/x/tools@v0.0.0-20200708181441-6004c8539734/internal/lsp/server_gen.go:188 +0x49
golang.org/x/tools/internal/lsp/protocol.serverDispatch(0x1a685e0, 0xc002571040, 0x1a82a60, 0xc0002f0100, 0xc0096993e0, 0x1a68820, 0xc002570fc0, 0x0, 0x0, 0xbfc0ca18688d4d48)
	/Users/damon/go1.14/pkg/mod/golang.org/x/tools@v0.0.0-20200708181441-6004c8539734/internal/lsp/protocol/tsserver.go:276 +0x494a
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0x1a685e0, 0xc002571040, 0xc0096993e0, 0x1a68820, 0xc002570fc0, 0x0, 0x0)
	/Users/damon/go1.14/pkg/mod/golang.org/x/tools@v0.0.0-20200708181441-6004c8539734/internal/lsp/protocol/protocol.go:62 +0xc0
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0x1a685e0, 0xc002571040, 0xc0096993e0, 0x1a68820, 0xc002570fc0, 0x0, 0x0)
	/Users/damon/go1.14/pkg/mod/golang.org/x/tools@v0.0.0-20200708181441-6004c8539734/internal/lsp/lsprpc/lsprpc.go:509 +0x40e
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0x1a685e0, 0xc002571040, 0xc00529faa0, 0x1a68820, 0xc002570fc0, 0xc001533000, 0x5d4)
	/Users/damon/go1.14/pkg/mod/golang.org/x/tools@v0.0.0-20200708181441-6004c8539734/internal/jsonrpc2/handler.go:35 +0xd3
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc007ad7bc0, 0xc004c43e60, 0xc0002c7610, 0x1a685e0, 0xc002571040, 0xc00529faa0, 0x1a68820, 0xc002570fc0)
	/Users/damon/go1.14/pkg/mod/golang.org/x/tools@v0.0.0-20200708181441-6004c8539734/internal/jsonrpc2/handler.go:103 +0x86
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	/Users/damon/go1.14/pkg/mod/golang.org/x/tools@v0.0.0-20200708181441-6004c8539734/internal/jsonrpc2/handler.go:100 +0x171
[Error - 6:37:05 AM] Connection to server got closed. Server will not be restarted.
[Error - 6:37:05 AM] Request textDocument/signatureHelp failed.
Error: Connection got disposed.
	at Object.dispose (/Users/damon/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/main.js:904:25)
	at Object.dispose (/Users/damon/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-languageclient/lib/client.js:74:35)
	at LanguageClient.handleConnectionClosed (/Users/damon/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-languageclient/lib/client.js:2309:42)
	at LanguageClient.handleConnectionClosed (/Users/damon/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-languageclient/lib/main.js:155:15)
	at closeHandler (/Users/damon/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-languageclient/lib/client.js:2296:18)
	at CallbackList.invoke (/Users/damon/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/Users/damon/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at closeHandler (/Users/damon/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/main.js:240:26)
	at CallbackList.invoke (/Users/damon/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/Users/damon/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at StreamMessageReader.fireClose (/Users/damon/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at Socket.<anonymous> (/Users/damon/.vscode/extensions/golang.go-0.15.2/node_modules/vscode-jsonrpc/lib/messageReader.js:151:46)
	at Socket.emit (events.js:208:15)
	at Pipe.<anonymous> (net.js:588:12)

```

**Comment by stamblerre** [comment]
Thanks for the report! I believe this crash has already been fixed at master and will be part of the `gopls/v0.4.4` release coming soon.
