### ISSUE TITLE
vscode-go hangs - mac  hard reboot mac is the only option

### ISSUE THREAD

**Issue by chandradeepak** [golang/vscode-go#534]
Please direct general questions to:
- [`#vscode` channel in Gophers Slack](https://invite.slack.golangbridge.org/messages/vscode)

Please review the [documentation](https://github.com/golang/vscode-go/tree/master/docs) before filing an issue.
Helpful pages include:

- [GOPATH](https://github.com/golang/vscode-go/tree/master/docs/gopath.md)
- [Module Support](https://github.com/golang/vscode-go/tree/master/docs/modules.md)
- [Debugging](https://github.com/golang/vscode-go/tree/master/docs/debugging.md)

I disabled all extensions except go lang for vscode and still got the issue. 

Please answer these questions before submitting your issue. Thanks!

### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
    go version go1.14 darwin/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
   1.47.3
   91899dcef7b8110878ea59626991a18c8a6a1b3e
   x64
- Check your installed extensions to get the version of the VS Code Go extension 
	- <Paste Go extension version here>
- Run `go env` to get the go development environment details
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/myuser/Library/Caches/go-build"
GOENV="/Users/myuser/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY="github.com,go.googlesource.com,gopkg.in,localhost,go.uber.org"
GOOS="darwin"
GOPATH="/Users/myuser/workspace/go/"
GOPRIVATE="myenterpiserserverrepos"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.14/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/53/hjtfgcyx565bfnxtj1d2s3340000gn/T/go-build630458320=/tmp/go-build -gno-record-gcc-switches -fno-common"

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

{
    "window.zoomLevel": 0,
    "explorer.openEditors.visible": 0,
    "editor.fontSize": 18,
    "files.autoSave": "off",
    "editor.minimap.enabled": false,
    "editor.scrollBeyondLastLine": false,
    "editor.renderIndentGuides": true,
    "vsicons.dontShowNewVersionMessage": true,
    "terminal.integrated.copyOnSelection": true,
    "workbench.activityBar.visible": true,
    "editor.matchBrackets": "always",
    "editor.suggestSelection": "first",
    "workbench.iconTheme": "vscode-icons",    
    "files.autoSaveDelay": 5000,
    "java.semanticHighlighting.enabled": true,
    "files.exclude": {
      "**/.classpath": true,
      "**/.project": true,
      "**/.settings": true,
      "**/.factorypath": true
    },
    "java.requirements.JDK11Warning": false,
    "editor.codeActionsOnSave":{},
    "extensions.autoCheckUpdates": false,
    "editor.tokenColorCustomizations": null,
    "update.mode": "manual",    
    "extensions.autoUpdate": false,    
    "go.formatTool": "goimports",
    "go.languageServerFlags": [
        "serve",
        "-rpc.trace",
        "--debug=localhost:6060",
        "-logfile=/Users/chandrakasiraju/Downloads/gopls.log"
      ],
    "go.useLanguageServer": true,
    "[go]": {
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true,
        },
        "editor.snippetSuggestions": "none",
    },
    "[go.mod]": {
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true,
        },
    },
    "gopls": {
        "usePlaceholders": true,
        "staticcheck": false,
    }    
 }

### Describe the bug
vscode freezes the mac. 

### Steps to reproduce the behavior:
when ever i try editing a file, especially if that file is big or if i replace whole content of a file , or if i change package name  or rename a variable or add a new package which brings new dependency the whole vscode hangs. I can't even move my mouse. i can not get out of vscode window and then kill vscode to restart. the only way is to force restart mac. this happened so many times in my mac.  To make sure it is not a linting problem i even tried to disables file.autosave to false. I think it has some thing to do with gopls or language server. I tried using atom editor for this issue. when i tried enabling gopls there as well it made my mac hang.  This happens once in a while when code file is big , you try to import a new dependency etc.

1. open a project preferrably a big project using iTerm in mac using the command line option code .
2. now copy a dir which contains 5 or more go files
3.  rename the dir to newdir or something.  
4. go the newdir using vscode editor navigation bar and click on the go files and try changing their package name to newdir
5. first time when this got reproduced it hanged when i did this in my project
6.  (after this i rebooted it)
7. tried to repeat same.  next time it didn't come immediately. this time i changed package name. it went through
8. now i deleted one file at a time . 
9. i saw mac freezed again
10. after this i rebooted mac
11. now tried to do same . changing package name , delete file didn't reproduce this time. 
12. tried deleting whole folder. 
13. mac hanged again. hard reboot .
14. in between in this multiple attempts i tried renaming fields once. i saw a crash in gopls(server) output which i am pasting in next comment.
15. the toughest thing is can not capture view->output logs also since whole mac is hanged. but when i tried renaming gopls crashed that i was able to catpture below. 
16. this kind of things happened so many times on mac . i tried following the various issues logged for hanging but none of them solved this. this still hanges my mac occasionally. 

### Screenshots or recordings
If applicable, add screenshots or recordings to help explain your problem.

**Comment by chandradeepak** [comment]
i caught a crash for the renaming a field . but this didn't hang my mac it only crashed the gopls server.  this is the output i see output i get when i see in view->outputs->gopls(server)
the other one is hard to capture since i can't even take a copy from vscode since it is hanged already. t


`[Info  - 3:39:20 AM] 2020/08/17 03:39:20 go/packages.Load
	snapshot=7
	directory=/Users/chandrakasiraju/workspace/go/src/pathtoproject
	query=[github.com/pathtoproject]
	packages=1

[Info  - 3:39:20 AM] 2020/08/17 03:39:20 go/packages.Load
	snapshot=7
	package_path="github.com/pathtoproject"
	files=[/Users/chandrakasiraju/workspace/go/src/github.com/pathtoproject/authenticate.go /Users/chandrakasiraju/workspace/go/src/github.com/pathtoproject/seed.go]

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x13efbc4]

goroutine 13316 [running]:
golang.org/x/tools/internal/lsp/source.(*renamer).checkInPackageBlock(0xc00ed12d20, 0x1ac3e80, 0xc01195c0f0)
	/Users/chandrakasiraju/workspace/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/source/rename_check.go:125 +0x424
golang.org/x/tools/internal/lsp/source.(*renamer).check(0xc00ed12d20, 0x1ac3e80, 0xc01195c0f0)
	/Users/chandrakasiraju/workspace/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/source/rename_check.go:42 +0x39a
golang.org/x/tools/internal/lsp/source.Rename(0x1ab1980, 0xc008a10120, 0x1ac5020, 0xc005bec280, 0x1ab5700, 0xc00c2798c0, 0x4031000000000000, 0x4022000000000000, 0xc00c116bc2, 0x3, ...)
	/Users/chandrakasiraju/workspace/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/source/rename.go:126 +0x631
golang.org/x/tools/internal/lsp.(*Server).rename(0xc0000bcf80, 0x1ab18c0, 0xc008d81e00, 0xc00b8481c0, 0x0, 0x0, 0xc00a457ce0)
	/Users/chandrakasiraju/workspace/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/rename.go:19 +0x117
golang.org/x/tools/internal/lsp.(*Server).Rename(0xc0000bcf80, 0x1ab18c0, 0xc008d81e00, 0xc00b8481c0, 0xc00b8481c0, 0x0, 0x0)
	/Users/chandrakasiraju/workspace/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/server_gen.go:148 +0x49
golang.org/x/tools/internal/lsp/protocol.serverDispatch(0x1ab18c0, 0xc008d81e00, 0x1acc3e0, 0xc0000bcf80, 0xc008a10000, 0x1ab1b00, 0xc008d81cc0, 0x0, 0x0, 0x1a9f300)
	/Users/chandrakasiraju/workspace/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/protocol/tsserver.go:374 +0x1147
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0x1ab18c0, 0xc008d81e00, 0xc008a10000, 0x1ab1b00, 0xc008d81cc0, 0xbfc679b2db3c55f8, 0xa60c9743d)
	/Users/chandrakasiraju/workspace/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/protocol/protocol.go:62 +0xc0
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0x1ab18c0, 0xc008d81e00, 0xc008a10000, 0x1ab1b00, 0xc008d81cc0, 0x0, 0x0)
	/Users/chandrakasiraju/workspace/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/lsprpc/lsprpc.go:521 +0x417
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0x1ab18c0, 0xc008d81e00, 0xc00c9dbe60, 0x1ab1b00, 0xc008d81cc0, 0xc00c0ed540, 0x1990118)
	/Users/chandrakasiraju/workspace/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/jsonrpc2/handler.go:35 +0xd3
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc0128b8480, 0xc00410e2a0, 0xc0000ab870, 0x1ab18c0, 0xc008d81e00, 0xc00c9dbe60, 0x1ab1b00, 0xc008d81cc0)
	/Users/chandrakasiraju/workspace/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/jsonrpc2/handler.go:103 +0x86
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	/Users/chandrakasiraju/workspace/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/jsonrpc2/handler.go:100 +0x171
[Info  - 3:39:23 AM] Connection to server got closed. Server will restart.
[Error - 3:39:23 AM] Request textDocument/rename failed.
Error: Connection got disposed.
	at Object.dispose (/Users/chandrakasiraju/.vscode/extensions/golang.go-0.16.1/dist/goMain.js:13824:25)
	at Object.dispose (/Users/chandrakasiraju/.vscode/extensions/golang.go-0.16.1/dist/goMain.js:10459:35)
	at LanguageClient.handleConnectionClosed (/Users/chandrakasiraju/.vscode/extensions/golang.go-0.16.1/dist/goMain.js:12694:42)
	at LanguageClient.handleConnectionClosed (/Users/chandrakasiraju/.vscode/extensions/golang.go-0.16.1/dist/goMain.js:70276:15)
	at closeHandler (/Users/chandrakasiraju/.vscode/extensions/golang.go-0.16.1/dist/goMain.js:12681:18)
	at CallbackList.invoke (/Users/chandrakasiraju/.vscode/extensions/golang.go-0.16.1/dist/goMain.js:24070:39)
	at Emitter.fire (/Users/chandrakasiraju/.vscode/extensions/golang.go-0.16.1/dist/goMain.js:24129:36)
	at closeHandler (/Users/chandrakasiraju/.vscode/extensions/golang.go-0.16.1/dist/goMain.js:13160:26)
	at CallbackList.invoke (/Users/chandrakasiraju/.vscode/extensions/golang.go-0.16.1/dist/goMain.js:24070:39)
	at Emitter.fire (/Users/chandrakasiraju/.vscode/extensions/golang.go-0.16.1/dist/goMain.js:24129:36)
	at StreamMessageReader.fireClose (/Users/chandrakasiraju/.vscode/extensions/golang.go-0.16.1/dist/goMain.js:28049:27)
	at Socket.<anonymous> (/Users/chandrakasiraju/.vscode/extensions/golang.go-0.16.1/dist/goMain.js:28089:46)
	at Socket.emit (events.js:208:15)
	at Pipe.<anonymous> (net.js:588:12)
[Info  - 3:39:23 AM] 2020/08/17 03:39:23 Build info

`


the output of gopls.log which i gave in setting doesn't have any crash logs. i see logs like 

`[Trace - 03:47:21.719 AM] Sending request 'textDocument/codeAction - (21)'.
Params: {"textDocument":{"uri":"file:///Users/chandrakasiraju/workspace/go/src/pathtoproject/authenticate.go"},"range":{"start":{"line":17,"character":9},"end":{"line":17,"character":9}},"context":{"diagnostics":[]}}


[Trace - 03:47:21.719 AM] Received response 'textDocument/codeAction - (21)' in 0ms.
Result: null


[Trace - 03:50:40.071 AM] Received notification 'window/logMessage'.
Params: {"type":3,"message":"2020/08/17 03:50:40 background imports cache refresh starting\n"}


[Trace - 03:50:40.461 AM] Received notification 'window/logMessage'.
Params: {"type":3,"message":"2020/08/17 03:50:40 background refresh finished after 389.893368ms\n"}`

**Comment by stamblerre** [comment]
Do you mind providing a full `gopls` log when you see the issue that causes you to reboot your computer? Instructions for capturing logs can be found [here](https://github.com/golang/tools/blob/master/gopls/doc/troubleshooting.md#capturing-logs).

I've mailed a change to fix the nil pointer you encountered.
