### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by byteshiva** [golang/vscode-go#585]
The VS failed to install gopls for latest go version  1.15

```
   "go.gopath": "/home/xyz/.asdf/installs/golang/1.15/packages",
    "go.goroot": "/home/xyz/.asdf/installs/golang/1.15/go",
    "go.buildOnSave": "workspace",
    "go.enableCodeLens": {


        "references": false,
        "runtest": true
    },
    "go.useLanguageServer": true,
    "[go]": {
        "editor.snippetSuggestions": "none",
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true,
        }
    },
    "go.languageServerExperimentalFeatures": {
        "diagnostics": true,
    },
    "go.languageServerFlags": [
        "-rpc.trace", // for more detailed debug logging
        "serve",
        "--debug=localhost:6060", // to investigate memory usage, see profiles 
    ],
    "gopls": {
        "usePlaceholders": true, // add parameter placeholders when completing a function

        // Experimental settings
        "completeUnimported": true, // autocomplete unimported packages
        "deepCompletion": true,     // enable deep completion
    },
```

<ANSWER HERE>
uname -a 
Linux Ubuntu 5.4.0-45-generic x86_64 x86_64 x86_64 GNU/Linux

```
goroutine 100 [running]:
golang.org/x/tools/internal/span.URI.Filename(...)
	/home/xyz/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/span/uri.go:32
golang.org/x/tools/internal/lsp/cache.(*View).setBuildInformation(0xc0013c2000, 0xea8b00, 0xc0003f8690, 0xc0004f2000, 0x167, 0xc000034b00, 0x52, 0x52, 0x1, 0x1, ...)
	/home/xyz/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/cache/view.go:814 +0x5a6
golang.org/x/tools/internal/lsp/cache.(*Session).createView(0xc00020fa00, 0xea8b00, 0xc0003f8690, 0xc000042820, 0x44, 0xc0004f2000, 0x167, 0x4000000000000000, 0x10101, 0xc0004db360, ...)
	/home/xyz/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/cache/session.go:163 +0x4f8
golang.org/x/tools/internal/lsp/cache.(*Session).NewView(0xc00020fa00, 0xea8b00, 0xc0003f8690, 0xc000042820, 0x44, 0xc0004f2000, 0x167, 0x4000000000000000, 0x10101, 0xc0004db360, ...)
	/home/xyz/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/cache/session.go:113 +0x12b
golang.org/x/tools/internal/lsp.(*Server).addView(0xc000242300, 0xea8b00, 0xc0003f8690, 0xc000042820, 0x44, 0xc0004f2000, 0x167, 0xeb84c0, 0xc00025d800, 0xeb89e0, ...)
	/home/xyz/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/workspace.go:41 +0x1f5
golang.org/x/tools/internal/lsp.(*Server).addFolders(0xc000242300, 0xea8b00, 0xc0003f8690, 0xc0004c2680, 0xd, 0xd, 0x0, 0x0)
	/home/xyz/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/general.go:206 +0x23c
golang.org/x/tools/internal/lsp.(*Server).initialized(0xc000242300, 0xea8b00, 0xc0003f8690, 0x13244d8, 0x0, 0x0)
	/home/xyz/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/general.go:157 +0x385
golang.org/x/tools/internal/lsp.(*Server).Initialized(0xc000242300, 0xea8b00, 0xc0003f8690, 0x13244d8, 0x13244d8, 0x0)
	/home/xyz/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/server_gen.go:112 +0x49
golang.org/x/tools/internal/lsp/protocol.serverDispatch(0xea8b00, 0xc0003f8690, 0xebbfc0, 0xc000242300, 0xc000294390, 0x7f3ae44539d8, 0xc0003f8510, 0xe963e0, 0xc00027a630, 0xea8b00)
	/home/xyz/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/protocol/tsserver.go:92 +0x662
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0xea8b00, 0xc0003f8690, 0xc000294390, 0x7f3ae44539d8, 0xc0003f8510, 0x12f2b80, 0xea6dc0)
	/home/xyz/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/protocol/protocol.go:62 +0xc5
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0xea8b00, 0xc0003f8690, 0xc000294390, 0x7f3ae44539d8, 0xc0003f8510, 0x0, 0x0)
	/home/xyz/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/lsprpc/lsprpc.go:521 +0x432
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0xea8b00, 0xc0003f8690, 0xc0003d6240, 0x7f3ae44539d8, 0xc0003f8510, 0x0, 0xc00003c840)
	/home/xyz/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/jsonrpc2/handler.go:35 +0xcf
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc00003cba0, 0xc0003f8d80, 0xc00024e310, 0xea8b00, 0xc0003f8690, 0xc0003d6240, 0x7f3ae44539d8, 0xc0003f8510)
	/home/xyz/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/jsonrpc2/handler.go:103 +0x86
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	/home/xyz/go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/jsonrpc2/handler.go:100 +0x173
[Error - 8:04:37 pm] Connection to server got closed. Server will not be restarted.

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by stamblerre** [comment]
What is the output of `gopls version`?

**Comment by byteshiva** [comment]
> What is the output of `gopls version`?

```
$gopls version
golang.org/x/tools/gopls 0.4.4
    golang.org/x/tools/gopls@v0.4.4 h1:8djGYsaZ0ByP0vaXg4T+mnyfDcHpWKSZ+tpQSGv9ahk=
```

**Comment by stamblerre** [comment]
Are you able to share the path of the file you are trying to open in VS Code?
Also, does this issue reproduce with `gopls` at master? You can download it by running `GO111MODULE=on go get golang.org/x/tools/gopls@master golang.org/x/tools@master`).

**Comment by byteshiva** [comment]
> Are you able to share the path of the file you are trying to open in VS Code?
> Also, does this issue reproduce with `gopls` at master? You can download it by running `GO111MODULE=on go get golang.org/x/tools/gopls@master golang.org/x/tools@master`.

The same issue with master as well.
```
 gopls version
golang.org/x/tools/gopls master
    golang.org/x/tools/gopls@v0.0.0-20200831203904-5a2aa26beb65 h1:MWud5v5bRpmz4RyaPSQpHN3mUrRFC2gnpc0/n27tu9Y=
```

**Comment by byteshiva** [comment]
I got it, is there way to not scan all projects under a workspace. Maybe some kind of ignore file to avoid scanning all projects in a workspace. 
 
Here it is, 
```
panic: only file URIs are supported, got "codeql-zip-archive" from "codeql-zip-archive://0-332/home//.var/app/com.visualstudio.code/config/Code/User/workspaceStorage/3a5c4dde7072c90c7ba5f8fa2f9772ac/GitHub.vscode-codeql/byteshiva_ideal-octo-fortnight-web-scrapper_javascript-srcVersion_c393bd99e160611c08cfb44e420f37364db4920d-dist_odasa-2020-08-12-12806-linux64/byteshiva_ideal-octo-fortnight-web-scrapper_c393bd9/src.zip/"

goroutine 133 [running]:
golang.org/x/tools/internal/span.URI.Filename(...)
	/home//go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/span/uri.go:32
golang.org/x/tools/internal/lsp/cache.(*View).setBuildInformation(0xc000c02000, 0xea8b00, 0xc000582990, 0xc0004f6000, 0x167, 0xc0002fc580, 0x52, 0x52, 0x1, 0x1, ...)
	/home//go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/cache/view.go:814 +0x5a6
golang.org/x/tools/internal/lsp/cache.(*Session).createView(0xc0002a69c0, 0xea8b00, 0xc000582990, 0xc0002a26e0, 0x44, 0xc0004f6000, 0x167, 0x4000000000000000, 0x10101, 0xc0004e2be0, ...)
	/home//go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/cache/session.go:163 +0x4f8
golang.org/x/tools/internal/lsp/cache.(*Session).NewView(0xc0002a69c0, 0xea8b00, 0xc000582990, 0xc0002a26e0, 0x44, 0xc0004f6000, 0x167, 0x4000000000000000, 0x10101, 0xc0004e2be0, ...)
	/home//go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/cache/session.go:113 +0x12b
golang.org/x/tools/internal/lsp.(*Server).addView(0xc0002a0c80, 0xea8b00, 0xc000582990, 0xc0002a26e0, 0x44, 0xc0004f6000, 0x167, 0xeb84c0, 0xc0006c3b00, 0xeb89e0, ...)
	/home//go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/workspace.go:41 +0x1f5
golang.org/x/tools/internal/lsp.(*Server).addFolders(0xc0002a0c80, 0xea8b00, 0xc000582990, 0xc0002a7520, 0xd, 0xd, 0x0, 0x0)
	/home//go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/general.go:206 +0x23c
golang.org/x/tools/internal/lsp.(*Server).initialized(0xc0002a0c80, 0xea8b00, 0xc000582990, 0x13244d8, 0x0, 0x0)
	/home//go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/general.go:157 +0x385
golang.org/x/tools/internal/lsp.(*Server).Initialized(0xc0002a0c80, 0xea8b00, 0xc000582990, 0x13244d8, 0x13244d8, 0x0)
	/home//go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/server_gen.go:112 +0x49
golang.org/x/tools/internal/lsp/protocol.serverDispatch(0xea8b00, 0xc000582990, 0xebbfc0, 0xc0002a0c80, 0xc000618000, 0x7f71c41c4128, 0xc000582930, 0xe963e0, 0xc000608000, 0xea8b00)
	/home//go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/protocol/tsserver.go:92 +0x662
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0xea8b00, 0xc000582990, 0xc000618000, 0x7f71c41c4128, 0xc000582930, 0x12f2b80, 0xea6dc0)
	/home//go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/protocol/protocol.go:62 +0xc5
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0xea8b00, 0xc000582990, 0xc000618000, 0x7f71c41c4128, 0xc000582930, 0x0, 0x0)
	/home//go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/lsp/lsprpc/lsprpc.go:521 +0x432
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0xea8b00, 0xc000582990, 0xc000585280, 0x7f71c41c4128, 0xc000582930, 0x0, 0x0)
	/home//go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/jsonrpc2/handler.go:35 +0xcf
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc000292780, 0xc000582db0, 0xc0002833b0, 0xea8b00, 0xc000582990, 0xc000585280, 0x7f71c41c4128, 0xc000582930)
	/home//go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/jsonrpc2/handler.go:103 +0x86
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	/home//go/pkg/mod/golang.org/x/tools@v0.0.0-20200729181040-64cdafbe085c/internal/jsonrpc2/handler.go:100 +0x173
[Error - 10:01:59 pm] Connection to server got closed. Server will not be restarted.
```
