### ISSUE TITLE
Linting and suggestions are too slow

### ISSUE THREAD

**Issue by anton7r** [golang/vscode-go#669]
**Is your feature request related to a problem? Please describe.**
Linting with `golint` and suggestions by `gocode` seem to be quite slow.
 
To my knowledge the speed issues seem to be related to the linter needing to fetch all of the files (the current package and its dependencies) from disk and then parsing it everytime a file is changed. And the same thing seems to be going with the suggestions. 

Or the issue is that linting is executed synchronously first before suggestions is executed.

**Describe the solution you'd like**
That the linter and tools alike should have a inmemory cache of the parsed code. And then on file updates it would only reload the parts of files that changed.

**Other solutions**
Im pretty sure that there is already a solution to this issue which im not aware of.

**Comment by anton7r** [comment]
gopls seems to be solution that im after. 

However when i toggle it on i get the following error:

`Error: command 'generate' already exists
    at _.registerCommand (...\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:674:270)
    at Object.registerCommand (...\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:977:119)
    at ExecuteCommandFeature.register (...\.vscode\extensions\golang.go-0.17.0\dist\goMain.js:12031:53)
    at ExecuteCommandFeature.initialize (...\.vscode\extensions\golang.go-0.17.0\dist\goMain.js:12011:14)
    at LanguageClient.initializeFeatures (...\.vscode\extensions\golang.go-0.17.0\dist\goMain.js:12843:21)
    at ...\.vscode\extensions\golang.go-0.17.0\dist\goMain.js:12528:18
`

**Comment by anton7r** [comment]
and also im using go 1.15.2 and gopls 0.5.0

**Comment by anton7r** [comment]
after a restart of vscode that seems to fix the issue, now it is just complaining about packages not found etc...

**Comment by anton7r** [comment]
and the reason why it is complaining is because on vscode im not in the root of module
