### ISSUE TITLE
gopls: automated issue report (crash)

### ISSUE THREAD

**Issue by BradHarris** [golang/vscode-go#732]
gopls version: v0.5.0
gopls flags: 

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

When attempting to restart gopls in vscode I get this error. However go is executable and it is in my $PATH. When I execute `go version` in terminal I get "go version go1.15.2 linux/amd64"

<pre>panic: err: go command required, not found: exec: "go": executable file not found in $PATH: stderr: 

goroutine 78 [running]:
golang.org/x/tools/internal/lsp/debug.PrintVersionInfo.func2()
	  info.go:58  0x233
golang.org/x/tools/internal/lsp/debug.section(0xec5e40, 0xc00049c2a0, 0x0, 0xd98f28, 0x7, 0xc00048af28)
	  info.go:69  0x322
golang.org/x/tools/internal/lsp/debug.PrintVersionInfo(0xed9d60, 0xc00037b140, 0xec5e40, 0xc00049c2a0, 0x1, 0x0)
	  info.go:52  0x1a7
golang.org/x/tools/internal/lsp.(*Server).initialize(0xc000406280, 0xed9d60, 0xc00037b140, 0xc000174c00, 0x0, 0x0, 0x0)
	  general.go:87  0x585
golang.org/x/tools/internal/lsp.(*Server).Initialize(0xc000406280, 0xed9d60, 0xc00037b140, 0xc000174c00, 0xc000174c00, 0x0, 0x0)
	  server_gen.go:108  0x49
golang.org/x/tools/internal/lsp/protocol.serverDispatch(0xed9d60, 0xc00037b140, 0xeed8e0, 0xc000406280, 0xc0002fc2d0, 0xed9fa0, 0xc00037b0c0, 0x0, 0xec7680, 0xc0001729a0)
	  tsserver.go:235  0x4d2
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0xed9d60, 0xc00037b140, 0xc0002fc2d0, 0xed9fa0, 0xc00037b0c0, 0x4ae6ce1, 0x132dce0)
	  protocol.go:63  0xc5
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0xed9d60, 0xc00037b140, 0xc0002fc2d0, 0xed9fa0, 0xc00037b0c0, 0x0, 0x0)
	  lsprpc.go:557  0x452
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0xed9d60, 0xc00037b140, 0xc000404500, 0xed9fa0, 0xc00037b0c0, 0x0, 0x0)
	  handler.go:35  0xcf
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc0000b2fc0, 0xc00037de90, 0xc0003749b0, 0xed9d60, 0xc00037b140, 0xc000404500, 0xed9fa0, 0xc00037b0c0)
	  handler.go:103  0x86
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x173
[Error - 2:35:54 PM] </pre>

**Comment by BradHarris** [comment]
Sorry I didn't see that this is a duplicate and there is already a workaround: #713
