### ISSUE TITLE
nightly: release has been blocked for a week due to test failures 

### ISSUE THREAD

**Issue by hyangah** [golang/vscode-go#886]
https://github.com/golang/vscode-go/actions?query=workflow%3A%22Release+%28golang.go-nightly%29%22

https://github.com/golang/vscode-go/runs/1327344295?check_suite_focus=true

```
$ build/all.bash prepare_nightly
$ npm ci
$ npm run vscode:prepublish
```

Then, run `Launch Extension Tests`.

Relevant error message:
```
  Code lenses for testing and benchmarking

Using GOPATH: /home/runner/go

rejected promise not handled within 1 second: TypeError: Cannot add property allExperiments, object is not extensible

stack trace: TypeError: Cannot add property allExperiments, object is not extensible
	at /home/runner/work/vscode-go/vscode-go/dist/goMain.js:24150:38
	at Generator.next (<anonymous>)
	at fulfilled (/home/runner/work/vscode-go/vscode-go/dist/goMain.js:23785:58)

```
/cc @stamblerre @suzmue

**Comment by hyangah** [comment]
Just released a new version  2020.11.415

Closing.

I still have a trouble with reliably running tests in my local machine, but will look into it further after the pending https://go-review.googlesource.com/c/vscode-go/+/266418
