### ISSUE TITLE
gopls: automated issue report (crash) - Stops suddenly

### ISSUE THREAD

**Issue by jcbritobr** [golang/vscode-go#923]
gopls version: v0.5.3
gopls flags: 

Auto complete stops suddenly, then it crashes

<pre>panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x38 pc=0xce6f05]

goroutine 81 [running]:
golang.org/x/tools/internal/lsp/source/completion.(*completer).deepSearch(0xc00010ea00, 0x1081900, 0xc007eb4cc0)
	  deep_completion.go:136  0x1125
golang.org/x/tools/internal/lsp/source/completion.Completion(0x1081900, 0xc007eb4cc0, 0x1093c80, 0xc005e204e0, 0x1081b40, 0xc00aaf0060, 0x4035000000000000, 0x4008000000000000, 0x3ff0000000000000, 0x0, ...)
	  completion.go:552  0xcd4
golang.org/x/tools/internal/lsp.(*Server).completion(0xc000352b60, 0x1081880, 0xc0002860c0, 0xc007eb4c00, 0x0, 0x0, 0x0)
	  completion.go:31  0xe8c
golang.org/x/tools/internal/lsp.(*Server).Completion(0xc000352b60, 0x1081880, 0xc0002860c0, 0xc007eb4c00, 0xc007eb4c00, 0x0, 0x0)
	  server_gen.go:24  0x50
golang.org/x/tools/internal/lsp/protocol.serverDispatch(0x1081880, 0xc0002860c0, 0x1096220, 0xc000352b60, 0xc0024cef30, 0x1081ac0, 0xc000286000, 0x0, 0x106f120, 0xc00120b8c0)
	  tsserver.go:285  0x22c2
golang.org/x/tools/internal/lsp/protocol.ServerHandler.func1(0x1081880, 0xc0002860c0, 0xc0024cef30, 0x1081ac0, 0xc000286000, 0x1248f89d1, 0x14dbcc0)
	  protocol.go:63  0xc7
golang.org/x/tools/internal/lsp/lsprpc.handshaker.func1(0x1081880, 0xc0002860c0, 0xc0024cef30, 0x1081ac0, 0xc000286000, 0x0, 0x0)
	  lsprpc.go:559  0x452
golang.org/x/tools/internal/jsonrpc2.MustReplyHandler.func1(0x1081880, 0xc0002860c0, 0xc00018a3c0, 0x1081ac0, 0xc000286000, 0xc0001c1fb0, 0x1)
	  handler.go:35  0xda
golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1.2(0xc0002bc060, 0xc0005469c0, 0xc000332230, 0x1081880, 0xc0002860c0, 0xc00018a3c0, 0x1081ac0, 0xc000286000)
	  handler.go:103  0x8d
created by golang.org/x/tools/internal/jsonrpc2.AsyncHandler.func1
	  handler.go:100  0x179
[Error - 14:05:11] </pre>

**Comment by jcbritobr** [comment]
It happens when I was typing the docs of an exportable method like this
// MyMethod ///// crashes here
func (...) MyMethod()

**Comment by jcbritobr** [comment]
@stamblerre you fixed it too fast :)
